### ISSUE TITLE
模板中使用filters

### ISSUE THREAD

**Issue by nyrf** [didi/chameleon#100]
试了下，好像不支持filters?

**Comment by beatles-chameleon** [comment]
是的，请使用computed指令代替 https://cmljs.org/doc/logic/computed.html

**Comment by nyrf** [comment]
> 是的，请使用computed指令代替 https://cmljs.org/doc/logic/computed.html
computed不能传参的，比如我有一组件，

```
<image :src="imageUrl" />
```

比如这样，我现在要根据传的参数显示图片尺寸

```
methods : {
  formatUrl (url, style) {
    if (style ===  'small')  { 
       return url + '!small'
    } else {
       return url + '!large'
    }
  }
}
```

这个时候是不是没办法了？

**Comment by nyrf** [comment]
@beatles-chameleon 请问下后面会支持模板中使用methods和filters么？

**Comment by beatles-chameleon** [comment]
> @beatles-chameleon 请问下后面会支持模板中使用methods和filters么？
解决方案：
1、写多个 computed
2、在逻辑层先格式化拼装需要的格式

描述：cml是考虑真正跨所有端的框架，所以只保留必要的设计，避免影响扩展性。

**Comment by nyrf** [comment]
> > @beatles-chameleon 请问下后面会支持模板中使用methods和filters么？
> 
> 解决方案：
> 1、如果这个url全局公用且动态变化的则写2个 computed
> 2、如果这是一个list里面的数据，则在逻辑层先格式化拼装需要的数据格式
> 
> 思考：
> 我们认为dsl模板层只用来拼装界面结构的代码，方法逻辑调用应该都在js逻辑层处理，所以只支持computed （逻辑写在js层）映射最终数据到dsl模板层。
> 
> cml是考虑真正跨所有端的框架，所以只保留必要的设计，不做过多**语法糖**，避免影响扩展性（例如以后支持flutter这类终端）。

感谢解释，了解
