### ISSUE TITLE
支付宝小程序样式编译不一致

### ISSUE THREAD

**Issue by ALiuGuanyan** [didi/chameleon#101]
**bug描述**
同一套css 支付宝小程序编译出来的样式与其他小程序不一致

**复现bug的步骤**
css

<img width="324" alt="WechatIMG1303" src="https://user-images.githubusercontent.com/42351146/55209074-c8532e80-521b-11e9-89a6-db6a4f161e02.png">

cml

<img width="522" alt="WechatIMG1305" src="https://user-images.githubusercontent.com/42351146/55209165-27b13e80-521c-11e9-9c25-b8a47d5b40cd.png">

**问题截图**
支付宝小程序显示
<img width="294" alt="WechatIMG2005" src="https://user-images.githubusercontent.com/42351146/55209098-df921c00-521b-11e9-8989-e06626dd5f10.png">

支付宝小程序调试器显示
<img width="323" alt="WechatIMG1302" src="https://user-images.githubusercontent.com/42351146/55209103-ea4cb100-521b-11e9-8046-1ed3cd47e7db.png">

微信与百度小程序显示
<img width="275" alt="WechatIMG2004" src="https://user-images.githubusercontent.com/42351146/55209109-f5074600-521b-11e9-8c87-310818f7ce96.png">

微信调试器显示
<img width="365" alt="WechatIMG1304" src="https://user-images.githubusercontent.com/42351146/55209130-02bccb80-521c-11e9-873c-fed05b31cccf.png">

**编译环境信息**
 - chameleon-tool 版本：[e.g.0.1.0-alpha.4]

**Comment by startheart** [comment]
按你代码写了，没发现不一致呢，升级支付宝开发工具试试？
![image](https://user-images.githubusercontent.com/10693888/55215719-b3839480-5235-11e9-8658-461584163fb8.png)
