### ISSUE TITLE
video组件在百度小程序端显示不正常

### ISSUE THREAD

**Issue by zhenjs** [didi/chameleon#104]
**bug描述**
video组件在百度小程序端显示不正常

**复现bug的步骤**
直接使用video组件即可

**问题截图**
<img width="404" alt="WX20190330-174832@2x" src="https://user-images.githubusercontent.com/23137213/55274612-c4ef9e00-5314-11e9-8eb7-71ae24a64e9e.png">

**编译环境信息**
 - chameleon-tool 版本：[0.1.1]
 - nodejs版本、npm版本：[node v8.4.0、npm 5.3.0]
 - 电脑操作系统： [e.g. macOS High Sierra 10.14]

**运行环境信息**
百度开发者工具

ps：给原生video标签增加id属性似乎可以解决该问题
![image](https://user-images.githubusercontent.com/23137213/55274679-cb324a00-5315-11e9-8f30-b7a55045e8a3.png)

**Comment by jimwmg** [comment]
chameleon-tool@0.1.1
刚试了一下没有复现这个问题，你直接复制文档中的demo再试下
https://cmljs.org/doc/example/video.html
