### ISSUE TITLE
全局字体应该在哪里设置？

### ISSUE THREAD

**Issue by ACChe** [didi/chameleon#108]
想用其他字体替换掉默认的那些字体，不知道应该在哪里可以设置？

**Comment by yylgit** [comment]
没有提供全局样式的设置

**Comment by ACChe** [comment]
那应该怎么统一换字体啊？要每个page里逐一替换？

**Comment by beatles-chameleon** [comment]
是的，原生小程序 和 weex 都有这个问题，无法全局替换

**Comment by shenmissing** [comment]
微信小程序不是可以嘛  放在 app.wxss 里面就是全局的样式

**Comment by startheart** [comment]
chameleon-tool@1.0.5-alpha.1

支持全局样式，使用参考demo：https://github.com/chameleon-team/cml-global-style

**Comment by ACChe** [comment]
Awesome...
