### ISSUE TITLE
能支持一下小程序·云开发吗？

### ISSUE THREAD

**Issue by ACChe** [didi/chameleon#109]
原来的项目是用了微信的小程序·云开发，有很多云函数，现在搬过来的时候，没有生成对应的目录存放已用的云函数。不知道应该可以怎么配置一下？

**Comment by yylgit** [comment]
我们需要调研一下

**Comment by ACChe** [comment]
@yylgit 短期内能支持吗？

**Comment by beatles-chameleon** [comment]
短期不会支持，后期规划：https://github.com/didi/chameleon/wiki/%E5%90%8E%E6%9C%9F%E8%A7%84%E5%88%92

**Comment by startheart** [comment]
请看云开发demo：https://github.com/chameleon-team/cml-cloudbase

**Comment by ACChe** [comment]
oh no, I have been not use this fw for a long time, but please keep going.
