### ISSUE TITLE
文档中示例代码的问题

### ISSUE THREAD

**Issue by beiguancyc** [didi/chameleon#113]
按照文档中list部分（https://cml.js.org/doc/component/base/layout/list.html）
代码复制粘贴测试，只选择生成微信小程序和web，如果使用component实现，小程序可以正常，web一片空白。

如果使用page不使用component，则都可以正常显示

**Comment by startheart** [comment]
使用page不使用component具体指什么？请贴上完整代码和环境信息

**Comment by beatles-chameleon** [comment]
按你说的操作了，没有出现问题，请确认自定义`<listcom/>`组件的引用方式是否正确。
`<script cml-type="json">
{
  "base": {
    "usingComponents": {
      "listcom": "/components/listcom/listcom"
    }
  }
}
</script>`

**Comment by beiguancyc** [comment]
抱歉，我个人觉得不是这个原因，不然为什么小程序一切正常呢?代码如下
```
<template>
  <page title="chameleon">
      <listcom></listcom>
  </page>
</template>

<script>

class Index  {
  data = {
    title: "chameleon",
    chameleonSrc: require('../../assets/images/chameleon.png')
  }
}

export default new Index();

</script>
<style>

.scroller-wrap {
  display: flex;
  flex-direction: column;
  align-items: center;
}

</style>
<script cml-type="json">
{
  "base": {
    "usingComponents": {
      "listcom": "/components/listcom/listcom"
    }
  },
  "wx": {
    "navigationBarTitleText": "index",
    "backgroundTextStyle": "dark",
    "backgroundColor": "#E2E2E2"
  }

}
</script>

```

**Comment by beiguancyc** [comment]
抱歉，我个人觉得不是这个原因，不然为什么小程序一切正常呢?
我已经仔细对照了好几遍，确实没找到原因，方便把你的page和component两页的代码贴上来吗，我贴到我的ide试试

**Comment by beiguancyc** [comment]
我用替换法把每一段代码进行了替换，最后为题定位在示例代码的样式container
`.container {
  position: absolute;
  top: 88cpx;
  left: 0;
  right: 0;
  bottom: 0;
}`
使用这个样式safari和chrome都显示为空白。
