### ISSUE TITLE
生命周期多态

### ISSUE THREAD

**Issue by xujiupeng** [didi/chameleon#117]
项目根目录执行 cml init component，选择 multimode-interface 多态接口，输入interface name: lifecycleInterface，自动生成src/components/lifecycleInterface 

在src/components/lifecycleInterface/lifecycleInterface.cml多态接口中，添加如下代码：

![image](https://user-images.githubusercontent.com/44659837/55699570-f136a900-59fd-11e9-8301-45964d28e2fc.png)

在 home.cml 文件，使methods合并lifecycleInterface多态方法
![image](https://user-images.githubusercontent.com/44659837/55699592-01e71f00-59fe-11e9-97a1-2efa8758f032.png)

在手机端打开不触发onHIde

**Comment by startheart** [comment]
要使用npm i chameleon-runtime@0.1.3 ，最新alpha版本生命周期增加了页面onShow 和 onHide ，写在interface里面会无效
