### ISSUE TITLE
支持头条小程序嘛

### ISSUE THREAD

**Issue by Just-focus** [didi/chameleon#118]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by beatles-chameleon** [comment]
本月支持快捷的标准扩展新端接口：https://github.com/didi/chameleon/issues/36
你可以自由扩展。

**Comment by beatles-chameleon** [comment]
https://github.com/didi/chameleon/issues/157
