### ISSUE TITLE
支持市面上得第三方小程序ui库嘛？

### ISSUE THREAD

**Issue by rainbowMorelhahahah** [didi/chameleon#119]
我看到文档上没有说明这一点 不知道支持嘛？

**Comment by beatles-chameleon** [comment]
1、官方基础组件库和扩展组件库：https://cml.js.org/doc/component/component.html
2、各端组件使用方式：https://juejin.im/post/5ca387cff265da30d47b134b

**Comment by Evahog33** [comment]
是不是推荐使用原生来写啊，毕竟库很难做到多方兼容，在cml没出库之前我感觉ui库会有不少坑

**Comment by beatles-chameleon** [comment]
> 是不是推荐使用原生来写啊，毕竟库很难做到多方兼容，在cml没出库之前我感觉ui库会有不少坑

请仔细看回答：
1、有ui组件库
2、推荐用cml写。
