### ISSUE TITLE
调用cml.request在百度小程序发起post请求时，设置成form格式，data数据不会被拼装

### ISSUE THREAD

**Issue by Bian2017** [didi/chameleon#121]
**bug描述**
调用cml.request在百度小程序发起post请求时，将contentType设置成form格式，data数据不会被拼装到body里。在支付宝、微信、H5均无此问题；

**问题截图**
支付宝小程序OK
![image](https://user-images.githubusercontent.com/28329190/55768558-e9cfd800-5aaf-11e9-8909-25b02eb0de9d.png)

百度小程序有问题
![image](https://user-images.githubusercontent.com/28329190/55768595-0ff57800-5ab0-11e9-8a95-54e3a4a094cc.png)

**编译环境信息**
  "chameleon-api": "^0.3.0",
    "chameleon-bridge": "^0.1.1",
    "chameleon-runtime": "^0.1.0",
    "chameleon-store": "0.0.3",
    "chameleon-ui-builtin": "^0.1.0",
    "cml-ui": "^0.1.2",

**Comment by beatles-chameleon** [comment]
你好，升级一下百度小程序开发者工具到最新版，就可以看到了。貌似是百度小程序的bug。
![image](https://user-images.githubusercontent.com/44267840/55799858-f4688c80-5b04-11e9-8b6a-9c5cb0b30f51.png)
