### ISSUE TITLE
关于列表的选中高亮功能疑问

### ISSUE THREAD

**Issue by beiguancyc** [didi/chameleon#123]
在使用c-for生成的列表中要实现选中项高亮功能，以前在vue下是可用的，比如
`<div class="collection">
    <a href="#!" class="collection-item"
       v-for="gameName in gameNames"
       @click="selected(gameName)"
       :class="{active: activeName == gameName}">{{gameName}}</a>
  </div>`
但是在cml下这段代码无效，请问关于class应该如何处理呢

**Comment by jimwmg** [comment]
类vue语法
  <view v-for="(gameName ,index) in gameNames" class="collection-item" 
  :class="(activeName===gameName) ? 'active':' '"
  @click="selected(gameName)"
  ></view>

文档链接：https://cmljs.org/doc/view/css-vue.html
多看下文档

**Comment by beiguancyc** [comment]
> 类vue语法
> <view v-for="(gameName ,index) in gameNames" class="collection-item"
> :class="(activeName===gameName) ? 'active':' '"
> @click="selected(gameName)"
> 
> > 
> 
> 文档链接：https://cmljs.org/doc/view/css-vue.html
> 多看下文档

这段代码只能在web上正常，小程序上无效

**Comment by jimwmg** [comment]
声明template   Lang＝"vue"了吗？如果还不行贴下完整的代码，我们测下。

**Comment by beiguancyc** [comment]
加上template Lang＝"vue"小程序依然不行。我用来测试的是cml-yanxuan的classify组件，代码如下
`<template Lang＝"vue">
  <view class="wrapper">
    <classify-header></classify-header>
    <view class="wrapper-content">
      <view class="class-list" style="{{scrollerHeight}}cpx">
        <scroller height="{{scrollerHeight}}">
          <view class="class-wrapper" c-for="{{classes}}" >
            <text class="class-txt" :class="(activeName===item) ? 'i-name':' '"  @click="forbinding(item)">{{item}}</text>
          </view>
        </scroller>
      </view>

      <view class="main-list" style="{{scrollerHeight}}cpx">
        <image class="ad-img" resize="cover" src="https://cmljs.org/cml-demo/src/assets/images/yanxuan/3ebd7addcc0d101d116052a57cec2f16.png"></image>
        <text class="sub-tlt"> --- 推荐区分类 --- </text>
        <view class="sub-box">
          <view class="sub-i" c-for="{{subclasses}}" c-bind:tap="godetail">
            <image class="i-img" resize="contain" src="{{item.img}}"></image>
            <text class="i-name">{{item.name}}</text>
          </view>
        </view>
      </view>
    </view>

  </view>
</template>
<script>
  import cml from "chameleon-api";
  import yanxuanData from '../../assets/json/yanxuan.json'
  const headerHeight = 114;
  const tabbarHeight = 90;
  class Classify   {
    data = {
      classes: [],
      subclasses : [],
      scrollerHeight: -1,
      activeName:''
    }
    methods = {
      godetail(){
        cml.navigateTo({
          "path": "/pages/detail/detail"
        });
      },
      forbinding(e){
        this.activeName=e
      }
    }

    created() {
      let result = yanxuanData.data.result;
      this.classes = result.classes;
      this.subclasses = result.subclasses;
    }

    mounted() {
      cml.getSystemInfo().then((info)=>{
        this.scrollerHeight = Number(info.viewportHeight) - headerHeight - tabbarHeight
      })
    }
  }

  export default new Classify();
</script>
<style scoped>

  .class-wrapper {
    display: flex;
    flex-direction: column;
  }
  .wrapper-content{
    display: flex;
    flex-direction: row;
    justify-content: space-between;
  }
  .class-list{
    width: 150cpx;
    /*height: 1000cpx;*/
    border-right-color: #d9d9d9;
    background-color: #fff;
    border-right-style:solid;
  }
  .class-txt{
    font-size: 28cpx;
    margin-top: 22cpx;
    margin-bottom: 26cpx;
    margin-left: 10cpx;
    margin-right: 10cpx;
    text-align: center;
    color:#333;
  }
  .main-list{
    width: 600cpx;
    /*height: 1000cpx;*/
    display: flex;
    flex-direction: column;
    flex-wrap: nowrap;
    background-color: #fff;
  }
  .ad-img{
    width: 532cpx;
    height: 194cpx;
    border-radius: 6cpx;
    margin: 28cpx;
  }
  .sub-tlt{
    display:block;
    text-align: center;
    font-size: 24cpx;
    color:#333;
    margin-top: 10cpx;
    margin-bottom: 30cpx;
  }
  .sub-box{
    padding-left: 26cpx;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
  }
  .sub-i{
    display:flex;
    flex-direction:column;
    width: 178cpx;
    height: 200cpx;
  }
  .i-img{
    width: 150cpx;
    margin-left: 14cpx;
    margin-right: 14cpx;
    height: 150cpx;
  }
  .i-name{
    color: red;
    font-size: 22cpx;
    text-align: center;
  }
</style>
<script cml-type="json">
  {
    "base": {
      "usingComponents": {
        "classify-header": "../common/classify-header"
      }
    }
  }
</script>
`

**Comment by beiguancyc** [comment]
加上template Lang＝"vue"小程序依然不行。我用来测试的是cml-yanxuan的classify组件，代码如下
```
<template Lang＝"vue">
  <view class="wrapper">
    <classify-header></classify-header>
    <view class="wrapper-content">
      <view class="class-list" style="{{scrollerHeight}}cpx">
        <scroller height="{{scrollerHeight}}">
          <view class="class-wrapper" c-for="{{classes}}" >
            <text class="class-txt" :class="(activeName===item) ? 'i-name':' '"  @click="forbinding(item)">{{item}}</text>
          </view>
        </scroller>
      </view>

      <view class="main-list" style="{{scrollerHeight}}cpx">
        <image class="ad-img" resize="cover" src="https://cmljs.org/cml-demo/src/assets/images/yanxuan/3ebd7addcc0d101d116052a57cec2f16.png"></image>
        <text class="sub-tlt"> --- 推荐区分类 --- </text>
        <view class="sub-box">
          <view class="sub-i" c-for="{{subclasses}}" c-bind:tap="godetail">
            <image class="i-img" resize="contain" src="{{item.img}}"></image>
            <text class="i-name">{{item.name}}</text>
          </view>
        </view>
      </view>
    </view>

  </view>
</template>
<script>
  import cml from "chameleon-api";
  import yanxuanData from '../../assets/json/yanxuan.json'
  const headerHeight = 114;
  const tabbarHeight = 90;
  class Classify   {
    data = {
      classes: [],
      subclasses : [],
      scrollerHeight: -1,
      activeName:''
    }
    methods = {
      godetail(){
        cml.navigateTo({
          "path": "/pages/detail/detail"
        });
      },
      forbinding(e){
        this.activeName=e
      }
    }

    created() {
      let result = yanxuanData.data.result;
      this.classes = result.classes;
      this.subclasses = result.subclasses;
    }

    mounted() {
      cml.getSystemInfo().then((info)=>{
        this.scrollerHeight = Number(info.viewportHeight) - headerHeight - tabbarHeight
      })
    }
  }

  export default new Classify();
</script>
<style scoped>

  .class-wrapper {
    display: flex;
    flex-direction: column;
  }
  .wrapper-content{
    display: flex;
    flex-direction: row;
    justify-content: space-between;
  }
  .class-list{
    width: 150cpx;
    /*height: 1000cpx;*/
    border-right-color: #d9d9d9;
    background-color: #fff;
    border-right-style:solid;
  }
  .class-txt{
    font-size: 28cpx;
    margin-top: 22cpx;
    margin-bottom: 26cpx;
    margin-left: 10cpx;
    margin-right: 10cpx;
    text-align: center;
    color:#333;
  }
  .main-list{
    width: 600cpx;
    /*height: 1000cpx;*/
    display: flex;
    flex-direction: column;
    flex-wrap: nowrap;
    background-color: #fff;
  }
  .ad-img{
    width: 532cpx;
    height: 194cpx;
    border-radius: 6cpx;
    margin: 28cpx;
  }
  .sub-tlt{
    display:block;
    text-align: center;
    font-size: 24cpx;
    color:#333;
    margin-top: 10cpx;
    margin-bottom: 30cpx;
  }
  .sub-box{
    padding-left: 26cpx;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
  }
  .sub-i{
    display:flex;
    flex-direction:column;
    width: 178cpx;
    height: 200cpx;
  }
  .i-img{
    width: 150cpx;
    margin-left: 14cpx;
    margin-right: 14cpx;
    height: 150cpx;
  }
  .i-name{
    color: red;
    font-size: 22cpx;
    text-align: center;
  }
</style>
<script cml-type="json">
  {
    "base": {
      "usingComponents": {
        "classify-header": "../common/classify-header"
      }
    }
  }
</script>

```

**Comment by jimwmg** [comment]
你先看下文档在来提issue吧，cml语法和vue语法到底怎么用先看明白了。

**Comment by beiguancyc** [comment]
> 你先看下文档在来提issue吧，cml语法和vue语法到底怎么用先看明白了。

惭愧。
多谢。
