### ISSUE TITLE
Native端背景图无效

### ISSUE THREAD

**Issue by github-gage** [didi/chameleon#125]
**bug描述**
Native端背景图无效，微信、WEB端正常
`.header-container{
  width: 750cpx;
  height: 639cpx;
  background-image: url("http://static.dxy.chinatbe.checil.com/app/my/bg.png");
  background-size: 750cpx 639cpx;
}`

**编译环境信息**
 - chameleon-tool 版本：0.2.0
 - nodejs版本、npm版本：node v11.14.0、npm 6.7.0

**Comment by beatles-chameleon** [comment]
weex不支持css background-image设置图片，可以使用<image />使用实现
