### ISSUE TITLE
什么时候可以支持scss呢？less相比较scss功能缺失太多了

### ISSUE THREAD

**Issue by ChenXiaoSong12321** [didi/chameleon#128]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by beatles-chameleon** [comment]
请自行扩展：https://cml.js.org/doc/framework/config.html#%E4%BF%AE%E6%94%B9webpack%E9%85%8D%E7%BD%AE

**Comment by ChenXiaoSong12321** [comment]
> 请自行扩展：https://cml.js.org/doc/framework/config.html#%E4%BF%AE%E6%94%B9webpack%E9%85%8D%E7%BD%AE

解决了，谢谢

**Comment by ChenXiaoSong12321** [comment]
// 解决支持scss，希望可以帮助到正在坑中或即将入坑的同学
cml.utils.plugin('webpackConfig', function({ type, media, webpackConfig }, cb) {
  const findRule = test => {
    let rules = {}
    webpackConfig.module.rules.some((item, index) => {
      if (new RegExp(item.test).test(test)){
        rules = {rule:item, index}
        return true
      } 
    })
    return rules
  }

  // 支持scss
  const cmlFile = findRule('.cml')
  console.log(cmlFile)
  cmlFile.rule.use = cmlFile.rule.use.map(use => {
    use.options.loaders.scss = JSON.parse(JSON.stringify(use.options.loaders.less)).map(item => {
      if (item.loader === 'less-loader') item.loader = 'sass-loader'
      return item
    })
    return use
  })
  webpackConfig.module.rules[cmlFile.index] = cmlFile.rule

  cb({
    type,
    media,
    webpackConfig
  })
})

**Comment by ChenXiaoSong12321** [comment]
`// 解决支持scss，希望可以帮助到正在坑中或即将入坑的同学
cml.utils.plugin('webpackConfig', function({ type, media, webpackConfig }, cb) {
  const findRule = test => {
    let rules = {}
    webpackConfig.module.rules.some((item, index) => {
      if (new RegExp(item.test).test(test)){
        rules = {rule:item, index}
        return true
      } 
    })
    return rules
  }

  // 支持scss
  const cmlFile = findRule('.cml')
  cmlFile.rule.use = cmlFile.rule.use.map(use => {
    use.options.loaders.scss = JSON.parse(JSON.stringify(use.options.loaders.less)).map(item => {
      if (item.loader === 'less-loader') item.loader = 'sass-loader'
      return item
    })
    return use
  })
  webpackConfig.module.rules[cmlFile.index] = cmlFile.rule

  cb({
    type,
    media,
    webpackConfig
  })
})`

**Comment by ChenXiaoSong12321** [comment]
`
// 解决支持scss，希望可以帮助到正在坑中或即将入坑的同学
cml.utils.plugin('webpackConfig', function({ type, media, webpackConfig }, cb) {
  const findRule = test => {
    let rules = {}
    webpackConfig.module.rules.some((item, index) => {
      if (new RegExp(item.test).test(test)){
        rules = {rule:item, index}
        return true
      } 
    })
    return rules
  }

  // 支持scss
  const cmlFile = findRule('.cml')
  cmlFile.rule.use = cmlFile.rule.use.map(use => {
    use.options.loaders.scss = JSON.parse(JSON.stringify(use.options.loaders.less)).map(item => {
      if (item.loader === 'less-loader') item.loader = 'sass-loader'
      return item
    })
    return use
  })
  webpackConfig.module.rules[cmlFile.index] = cmlFile.rule

  cb({
    type,
    media,
    webpackConfig
  })
})
`

**Comment by ChenXiaoSong12321** [comment]
```js
// 解决支持scss，希望可以帮助到正在坑中或即将入坑的同学
cml.utils.plugin('webpackConfig', function({ type, media, webpackConfig }, cb) {
  const findRule = test => {
    let rules = {}
    webpackConfig.module.rules.some((item, index) => {
      if (new RegExp(item.test).test(test)){
        rules = {rule:item, index}
        return true
      } 
    })
    return rules
  }

  // 支持scss
  const cmlFile = findRule('.cml')
  cmlFile.rule.use = cmlFile.rule.use.map(use => {
    use.options.loaders.scss = JSON.parse(JSON.stringify(use.options.loaders.less)).map(item => {
      if (item.loader === 'less-loader') item.loader = 'sass-loader'
      return item
    })
    return use
  })
  webpackConfig.module.rules[cmlFile.index] = cmlFile.rule

  cb({
    type,
    media,
    webpackConfig
  })
})
```

**Comment by ChenXiaoSong12321** [comment]
```js
// 解决支持scss，希望可以帮助到正在坑中或即将入坑的同学
cml.utils.plugin('webpackConfig', function({ type, media, webpackConfig }, cb) {
  const findRule = test => {
    let rules
    webpackConfig.module.rules.some((item, index) => {
      if (new RegExp(item.test).test(test)){
        rules = {rule:item, index}
        return true
      } 
    })
    return rules
  }

  // 支持scss
  const cmlFile = findRule('.cml')
  if(cmlFile){
    cmlFile.rule.use = cmlFile.rule.use.map(use => {
      use.options.loaders.scss = JSON.parse(JSON.stringify(use.options.loaders.less)).map(item => {
        if (item.loader === 'less-loader') item.loader = 'sass-loader'
        return item
      })
      return use
    })
    webpackConfig.module.rules[cmlFile.index] = cmlFile.rule
  }

  cb({
    type,
    media,
    webpackConfig
  })
})
```

**Comment by beatles-chameleon** [comment]
相当优秀了
@ChenXiaoSong12321

**Comment by ChenXiaoSong12321** [comment]
```js
const uiComp = 'xxx-ui' // 企业自己项目开发的 ui 库
cml.utils.plugin('webpackConfig', function({ type, media, webpackConfig }, cb) {
  const findRule = test => {
    let rules
    webpackConfig.module.rules.some((item, index) => {
      if (new RegExp(item.test).test(test)) {
        rules = { rule: item, index }
        return true
      }
    })
    return rules
  }

  // 解决项目 node_modules 中私有 ui库的js和interface文件未使用相应的 loader 编译，导致私有ui库中es6语法报错
  const _interface = findRule('.interface')
  _interface.rule.include.push(`${webpackConfig.context}\\node_modules\\${uiComp}`)
  webpackConfig.module.rules[_interface.index] = _interface.rule

  const js = findRule('.js')
  js.rule.include.push(`${webpackConfig.context}\\node_modules\\${uiComp}`)
  webpackConfig.module.rules[js.index] = js.rule

  // 支持scss
  const cmlFile = findRule('.cml')
  if (cmlFile) {
    cmlFile.rule.use = cmlFile.rule.use.map(use => {
      use.options.loaders.scss = JSON.parse(JSON.stringify(use.options.loaders.less)).map(item => {
        if (item.loader === 'less-loader') item.loader = 'sass-loader'
        return item
      })
      return use
    })
    webpackConfig.module.rules[cmlFile.index] = cmlFile.rule
  }

  cb({
    type,
    media,
    webpackConfig
  })
})
```

@beatles-chameleon  解决项目 node_modules 中私有 ui库的js和interface文件未使用相应的 loader 编译，导致私有ui库中es6语法报错，chameleon-tool为什么没有开源呢？

**Comment by zyhlast** [comment]
除以上配置外，还需安装node-sass sass-loader依赖，npm i sass-loader@6.x --save-dev   npm install --save-dev node-sass ， 高版本sass-loader不行，6.x版本可用。
