### ISSUE TITLE
请问目前 chameleon 支持类 Vue 的 $attrs 和 $listenters 吗？

### ISSUE THREAD

**Issue by wawIsready** [didi/chameleon#136]
在指令中没有找到这一项。目前组件之间通信只支持 props 是吗？

**Comment by beatles-chameleon** [comment]
父组件传递子组件使用props，子组件传递父组件使用事件回调：https://cmljs.org/doc/view/event.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BA%8B%E4%BB%B6

**Comment by wawIsready** [comment]
> 父组件传递子组件使用props，子组件传递父组件使用事件回调：https://cmljs.org/doc/view/event.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BA%8B%E4%BB%B6

有没有暴露的能使用 eventBus 的实例？

**Comment by beatles-chameleon** [comment]
@wawIsready 你看看文档，不是用eventBus，直接`this.$cmlEmit`调用父组件事件绑定回调。

**Comment by wawIsready** [comment]
> @wawIsready 你看看文档，不是用eventBus，直接`this.$cmlEmit`调用父组件事件绑定回调。

我可能表述的不清楚。实际上我想问: 兄弟组件，跨路由组件或者是多级组件有没有相应的指令可以使用？

**Comment by beatles-chameleon** [comment]
> > @wawIsready 你看看文档，不是用eventBus，直接`this.$cmlEmit`调用父组件事件绑定回调。
> 
> 我可能表述的不清楚。实际上我想问: 兄弟组件，跨路由组件或者是多级组件有没有相应的指令可以使用？

使用[store](https://cmljs.org/doc/logic/store.html)进行跨多个组件解耦和通信

**Comment by wawIsready** [comment]
> > > @wawIsready 你看看文档，不是用eventBus，直接`this.$cmlEmit`调用父组件事件绑定回调。
> > 
> > 
> > 我可能表述的不清楚。实际上我想问: 兄弟组件，跨路由组件或者是多级组件有没有相应的指令可以使用？
> 
> 使用[store](https://cmljs.org/doc/logic/store.html)进行跨多个组件解耦和通信
好的，谢谢解答。

**Comment by wawIsready** [comment]
> > > @wawIsready 你看看文档，不是用eventBus，直接`this.$cmlEmit`调用父组件事件绑定回调。
> > 
> > 
> > 我可能表述的不清楚。实际上我想问: 兄弟组件，跨路由组件或者是多级组件有没有相应的指令可以使用？
> 
> 使用[store](https://cmljs.org/doc/logic/store.html)进行跨多个组件解耦和通信

好的，谢谢解答。
