### ISSUE TITLE
dev启动项目报错

### ISSUE THREAD

**Issue by tsker** [didi/chameleon#138]
**bug描述**
dev启动项目，报 UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, readlink 'F:\website\demo\c\node_modules\chameleon-runtime\.temp\router.js'
好像是权限的问题，但是操作文件没有问题

**复现bug的步骤**
1.cml dev
**问题截图**
![image](https://user-images.githubusercontent.com/5285733/56492816-81591000-651f-11e9-93eb-f21b99ea2069.png)

**编译环境信息**
 - chameleon-tool 版本：[e.g.0.2.1]
 - nodejs版本、npm版本：[node v11.9.0、npm 6.5.0]
 - 电脑操作系统： [e.g. win10 10.0.17763]

**运行环境信息**
 - 端版本： [e.g. ]
 - 手机机型: [e.g. ]

**Comment by jimwmg** [comment]
我刚试了下没有复现：
只启动wx：cml wx dev 有问题吗，还是只有 cml web  dev有问题吗？

**Comment by tsker** [comment]
具体流程就是根据快速上手走，到dev这一块的时候就会有这个问题。
cml dev，cml wx dev, cml web dev....等都尝试无效

**Comment by tsker** [comment]
问题找到。
电脑多个系统，为了在多个系统间共享文件，创建了一个fat分区，cml项目就在这个分区上。
node的fs.readlink[Sync]方法在fat分区上貌似有问题。

把项目放到Ntfs分区上，解决问题。
