### ISSUE TITLE
[支付宝小程序]cml.request 支付宝请求my.httpRequest后续不再支持

### ISSUE THREAD

**Issue by z-mirror** [didi/chameleon#139]
**bug描述**
同样的接口，同样的参数，cml.request post请求在支付宝开发工具请求正常，支付宝真机调试请求报错；
排查发现支付宝开发工具请求时，payload正常json，支付宝真机调试时，payload变成string

**问题截图**
支付宝开发工具请求payload
![0423-1](https://user-images.githubusercontent.com/27213974/56548488-cbd79c80-65b2-11e9-87db-a6fd787005b6.png)

支付宝真机payload
![0423-2](https://user-images.githubusercontent.com/27213974/56548786-9ed7b980-65b3-11e9-8019-4a5d769f7ebd.png)

**问题解决思路**
支付宝开发工具提示my.httpRequest后续不再支持
![0423-3](https://user-images.githubusercontent.com/27213974/56548888-de9ea100-65b3-11e9-9b56-421d67fd1cbf.png)
于是更改本地request->index.interface
![image](https://user-images.githubusercontent.com/27213974/56549082-697f9b80-65b4-11e9-8fa8-a3cb9fc572e6.png)
![image](https://user-images.githubusercontent.com/27213974/56549178-aa77b000-65b4-11e9-8c1b-1c8b207a94c9.png)

更改后问题解决，支付宝开发工具和真机调试均正常

**支付宝api说明**

![image](https://user-images.githubusercontent.com/27213974/56549347-1e19bd00-65b5-11e9-94e0-9a62668a2f33.png)

**编译环境信息**
 - chameleon-tool 版本：[e.g.0.2.0-alpha.0]
 - nodejs版本、npm版本：[node v10.15.3、npm 6.9.0]
 - 电脑操作系统： [e.g. macOS High Sierra 10.13.6]
 - chameleon-api@0.3.0

**运行环境信息**
 - 端版本： [e.g. 支付宝 10.1.60 ]

**Comment by beatles-chameleon** [comment]
优秀，感谢反馈，欢迎提交issue。

**Comment by z-mirror** [comment]
> 优秀，感谢反馈，欢迎提交pull request。

已提交

**Comment by AdamEleven** [comment]
感谢反馈, 已修复, 升级chameleon-api@0.4.7版本即可

**Comment by beatles-chameleon** [comment]
感谢成为外部贡献者之一，欢迎继续提交PR：https://github.com/didi/chameleon/commit/bafb4c3900f9b0ab11644868817e1d68249deb4f#diff-04c6e90faac2675aa89e2176d2eec7d8L110

![image](https://user-images.githubusercontent.com/44267840/56658013-16990780-66cc-11e9-9f19-98348499ca24.png)
