### ISSUE TITLE
可以支持sass语法吗

### ISSUE THREAD

**Issue by lmw6412036** [didi/chameleon#14]
可以支持sass语法吗

**Comment by beatles-chameleon** [comment]
由于 native 端样式渲染的限制，强烈建议开发者使用[CMSS](https://cml.js.org/doc/view/cmss.html)的语法，如果[只跨web和小程序](https://cml.js.org/doc/example/web_wx.html)，可以使用less和stylus ，框架后续可以考虑支持sasss

**Comment by ChenXiaoSong12321** [comment]
> 可以支持SASS语法吗

https://github.com/didi/chameleon/issues/128
