### ISSUE TITLE
androi集成加载JS降级为H5

### ISSUE THREAD

**Issue by W1913** [didi/chameleon#145]
**bug描述**
加载使用工具打包出来的JS降级为H5页面

**复现bug的步骤**
直接 CmlEngine.getInstance().launchPage(this, URL_JS_BUNDLE_OK, null);

**问题截图**
04-26 10:36:41.501 29629-29655/com.didi.chameleon.example E/WeexCore:  ReportException : Exception: SyntaxError: Unexpected token '<'
    at (global function):6
    Function@[native code]
    Function@[native code]
    (weex framework):1:151029
    ni@(weex framework):1:151047
    createInstance@(weex framework):1:154254
    (weex framework):1:178788
04-26 10:36:41.501 29629-29649/com.didi.chameleon.example E/weex: reportJSException >>>> instanceId:1, exception function:createInstance, exception:Exception: SyntaxError: Unexpected token '<'
    at (global function):6
    Function@[native code]
    Function@[native code]
    (weex framework):1:151029
    ni@(weex framework):1:151047
    createInstance@(weex framework):1:154254
    (weex framework):1:178788
04-26 10:36:41.501 29629-29629/com.didi.chameleon.example E/CmlWeexInstance: onException msg = degradeToH5|createInstance fail|wx_create_instance_error, reportJSException >>>> instanceId:1, exception function:createInstance, exception:Exception: SyntaxError: Unexpected token '<'
    at (global function):6
    Function@[native code]
    Function@[native code]
    (weex framework):1:151029
    ni@(weex framework):1:151047
    createInstance@(weex framework):1:154254
    (weex framework):1:178788
    
     getTemplateInfo== template md5 51f566d78137624fcf2618fc490203ab length 870 base64 md5 UfVm14E3Yk/PJhj8SQIDqw== response header {"templateSourceBase64MD5":["UfVm14E3Yk/PJhj8SQIDqw=="],"templateSourceMD5":["51f566d78137624fcf2618fc490203ab"]}, extInitTime:6054ms, extInitErrorMsg:| weex JS framework from assets, isSandBoxContext: true | pieSupport:true

**编译环境信息**
android studio 3.4

**运行环境信息**
小米6 vivo x7

**Comment by beatles-chameleon** [comment]
JS包代码是什么？

**Comment by sxychenjing** [comment]
加微信官方群，直接联系change

**Comment by KSKjust** [comment]
应该jsbundle问题，麻烦确认哈，后续有问题再交流
