### ISSUE TITLE
input的文本（包括输入的和placeholder的）跑到最上层

### ISSUE THREAD

**Issue by ACChe** [didi/chameleon#147]
把按钮固定在最下方，滑动时，左边的text能被按钮遮挡，右边的电话号码会跑到最上层。【微信端】

![image](https://user-images.githubusercontent.com/1592763/56795650-841b7400-6843-11e9-8738-fc31bfc372a6.png)

`<view>
    <view>
        <view class="contact-item-box">
            <view class="addr-title-txt"><text>联系方式</text></view>
            <view class="addr-txt"><input placeholder="{{contact}}" cstyle="border: 0cpx;" focus="{{isContactFocus}}" c-bind:input="inputContactEvent" c-bind:blur="bindcontactblurevent"></input></view>
          </view>
    </view>
 </view>`

`
      <view style="position: fixed; bottom: 0cpx; background-color: #000079; height: 88cpx; width: 750cpx; display: flex; justify-content: center; align-items: center;">
        <text style="color: rgb(255, 192, 0); font-size: 28cpx;"> 提交发布 </text>
      </view>`

**Comment by beatles-chameleon** [comment]
input textarea video这类组件在小程序下是原生渲染，层级最高，如果希望覆盖它们，可以使用<cover-view/>标签包裹你的内容

**Comment by eeve** [comment]
@beatles-chameleon 能举个栗子？
