### ISSUE TITLE
事件回调函数传参

### ISSUE THREAD

**Issue by WJer** [didi/chameleon#149]
**bug描述**
事件回调函数传汉字or对象，weex Compiling... 每次启动时，花费超过1min的时间
事件回调函数传单词，weex Compiling... 每次启动时，花费不超过9s的时间

**问题截图**
传汉字：
![image](https://user-images.githubusercontent.com/9282663/56860810-2155e400-69cd-11e9-938f-cfa0170230a0.png)
传英文：
![image](https://user-images.githubusercontent.com/9282663/56860844-69750680-69cd-11e9-8bcc-a74395aa5497.png)

**编译环境信息**
 - chameleon-tool 版本：0.2.x
 - nodejs版本、npm版本：[node v9.3.0、npm 5.5.1]
 - 电脑操作系统： [e.g. macOS High Sierra 10.12]

**Comment by WJer** [comment]
补充：
![image](https://user-images.githubusercontent.com/9282663/56860872-bce75480-69cd-11e9-9f8e-ae7b37bdef3b.png)
事件回调函数传参如上图的方式传参

**Comment by beatles-chameleon** [comment]
感谢反馈，排查中

**Comment by jimwmg** [comment]
已解决  等发完稳定版在回复你
