### ISSUE TITLE
android 选择图片和mix2上面视图展示兼容问题

### ISSUE THREAD

**Issue by wobiancao** [didi/chameleon#158]
**bug描述**
1、api接口cml.chooseImage点击选择拍照、相册 安卓上没反应（权限已给）h5、微信小程序正常
2、mix2上展示视图不兼容

**问题截图**
![image](https://user-images.githubusercontent.com/8624954/57218017-d2402c80-7026-11e9-86f8-1ee052fd875a.png)

![image](https://user-images.githubusercontent.com/8624954/57218008-cc4a4b80-7026-11e9-9fe7-ed0a4353a8ff.png)

**编译环境信息**
 - chameleon-tool 版本：[@0.0.16]
 - nodejs版本、npm版本：[node v10.15.1、npm 6.4.1]
 - 电脑操作系统： [e.g. macOS High Sierra 10.13.5]

**运行环境信息**
 - 手机机型: [e.g. MIX 2 ]
 - OS Version: [Android8.0.0]

**Comment by beatles-chameleon** [comment]
你好，问题已经收到，问题2我们进行一下调整。问题1：“1、api接口cml.chooseImage点击选择拍照、相册 安卓上没反应（权限已给）h5、微信小程序正常” 是说的h5上正常还是不正常？问题是出在h5上还是weex上？

**Comment by wobiancao** [comment]
> 你好，问题已经收到，问题2我们进行一下调整。问题1：“1、api接口cml.chooseImage点击选择拍照、相册 安卓上没反应（权限已给）h5、微信小程序正常” 是说的h5上正常还是不正常？问题是出在h5上还是weex上？

用安卓demo chameleon-sdk-android-master 打开相应链接 CmlEngine.getInstance().launchPage、CmlWebEngine.getInstance().launchPage、CmlWeexEngine.getInstance().launchPage 会出现上述情况，h5在浏览器打开没问题 这样的

**Comment by beatles-chameleon** [comment]
你好，我们相关同学已经进行了修复，请稍后更新sdk代码。
