### ISSUE TITLE
c-radio-group的间距不可控？

### ISSUE THREAD

**Issue by ACChe** [didi/chameleon#159]
![image](https://user-images.githubusercontent.com/1592763/57220943-c6a53380-702f-11e9-8aef-71eb03d1459a.png)
【微信端】

c-radio-group貌似不能定制样式，也不能嵌入自定义view，
分开来写，不能正常对齐啊。

**Comment by shenmissing** [comment]
实话告诉你 我就用了 view text image 这几个标签  而且基础样式都是关闭的

**Comment by beatles-chameleon** [comment]
c-radio-group 会增加自定义样式属性
