### ISSUE TITLE
<c-picker>组件在微信小程序上过快选择选项，导致无法选择其他选项，移动到其他选项会强制回弹。

### ISSUE THREAD

**Issue by AnselRain** [didi/chameleon#163]
**bug描述**
<c-picker>组件在微信小程序上过快选择选项，导致无法选择其他选项，移动到其他选项会强制回弹。

**复现bug的步骤**
1. 将c-picker组件官方代码copy进项目中
2. 打开微信小程序，打开c-picker组件
3. 在c-picker组件中刚滑动到一个选项就点击确认
4. 再次打开c-picker组件
5. See error

**问题截图**
![newone2](https://user-images.githubusercontent.com/16009788/57277074-e68f3280-70d5-11e9-906c-50a92d9c0a5f.gif)
![newone3](https://user-images.githubusercontent.com/16009788/57277164-2229fc80-70d6-11e9-8987-55b1c886e90a.gif)

**编译环境信息**
 - chameleon-tool 版本：[ 0.3.2 ]
 - nodejs版本、npm版本：[node v10.11.0、npm 6.7.0]
 - 电脑操作系统： [macOS High Sierra 10.14.4 ]

**运行环境信息**
 - 端版本： [微信小程序 7.0.4]
 - 手机机型: [iPhone8 12.2]

**Comment by beatles-chameleon** [comment]
直接copy了[官网的代码示例](https://cml.js.org/doc/component/expand/compound/c-picker.html#%E7%A4%BA%E4%BE%8B)，没有复现，请确认传入的`default-index`是否一直在变更导致的

**Comment by AnselRain** [comment]
@beatles-chameleon 
![newone4](https://user-images.githubusercontent.com/16009788/57280923-76d07600-70dc-11e9-8a79-c927c9c34423.gif)

**Comment by AnselRain** [comment]
这个问题我在微信小程序上触发的了，在h5上不会出现。

**Comment by beatles-chameleon** [comment]
代码示例有些问题，将`this.provinsIndex = this.defaultIndex = e.detail.index;`改成`this.provinsIndex =  e.detail.index;`

**Comment by AnselRain** [comment]
可以了，谢谢
