### ISSUE TITLE
h5端当scroller偶遇input时，input以滑动的形式取消焦点时，页面滚动计算有问题

### ISSUE THREAD

**Issue by shenmissing** [didi/chameleon#170]
**相关代码**
![TIM图片20190513092128](https://user-images.githubusercontent.com/26575154/57590780-8f1f1580-7560-11e9-8e2b-2e45548a9138.png)

**复现bug的步骤**
1、input聚焦
2、往上滑动取消焦点时，有30%概率轻轻滑动会往下滚动很远的距离
3、上图的代码中input是顶着头部的，往下滑动取消焦点时，偶尔也会出现往下滚动一段距离

**问题补充**
1、发现如果scroller里的第一个子标签就是input的话，就是没有 top_banner 时，没有上述的问题

**编译环境信息**
 - chameleon-tool 版本：@0.3.2

**运行环境信息**
 - iphone 6s 12.2  （安卓上没有上述问题）

**Comment by huyuangang** [comment]
更新一下chameleon-ui-builtin@0.2.10-alpha.2

**Comment by shenmissing** [comment]
更新了  刚试了下  貌似还有这个问题

**Comment by huyuangang** [comment]
滚动取消焦点时是会触发滚动的，往下滚动很远的距离问题还存在吗

**Comment by shenmissing** [comment]
概率稍小了点，但是还是会出现，   往下滑动取消焦点时  页面也会向下滚动

**Comment by huyuangang** [comment]
往下滑动取消焦点，页面是会滑动的。

**Comment by shenmissing** [comment]
我描述的不太对   是下滑手势   下拉的意思   上面已经顶着页面顶部了   页面不应该滚动啊

**Comment by startheart** [comment]
微信浏览器阻止整个页面的下拉效果（Google搜索下）`document.body.addEventListener('touchstart',function(e){e.preventDefault()}, true)`

**Comment by shenmissing** [comment]
貌似跟这个并没有关系   就这么几行简单的代码  你们真的亲测过么  
我测试的场景：input聚焦时， 下滑 取消焦点时，页面小概率会向下滚动

**Comment by beatles-chameleon** [comment]
当然测过了，下滑手势，触发input失焦，键盘收起，如果下滑手势也触摸了页面，页面向下滚动，有什么问题？

**Comment by shenmissing** [comment]
下滑手势。。页面向下滚动   这个没问题吗？   正常是上滑手势 页面才向下滚动撒

**Comment by shenmissing** [comment]
正常情况下应该是：下滑手势，页面向上滚动。上滑手势，页面向下滚动。

**Comment by huyuangang** [comment]
更新chameleon-ui-builtin@0.2.10-alpha.7试一下
