### ISSUE TITLE
过了一遍文档，希望这个并不是一个KPI的开源项目。感谢开源..

### ISSUE THREAD

**Issue by webkong** [didi/chameleon#18]
过了文档看好Chameleon的。最起码写法相对更友好。设计更合理吧。

用了Taro感觉设计上有点违和，我猜一开始肯定是想弄一个小程序的工具，后来不得已要兼容很多模式。😝

希望不是一个KPI的项目。开源加油..

**Comment by liub1934** [comment]
vue的语法  很好上手😝 希望能持久更新

**Comment by beatles-chameleon** [comment]
beatles是一个有理想的团队，不是为了KPI。
期望大家一起为生态努力。

**Comment by topperCao** [comment]
请问目前有做这个做成的开源项目吗？
