### ISSUE TITLE
【已完成】【新端扩展】快应用共建计划

### ISSUE THREAD

**Issue by beatles-chameleon** [didi/chameleon#185]
## 更新已支持快应用：
https://cml.js.org/doc/example/quickapp_miniapp.html

## CML的跨端标准协议

Chameleon 规范了一套跨端标准，称之为MVVM+协议；开发者只需要按照[标准扩展流程](https://cmljs.org/doc/extend/quickstart.html)，即可快速扩展任意MVVM架构模式的新端。并让已有项目无缝运行新端。

## 目标
按照<a href="https://cmljs.org/doc/extend/quickstart.html">新端扩展标准</a>支持快应用

## 参与方
快应用官方研发团队

**Comment by zheyizhifeng** [comment]
# Chameleon扩展快应用排期

## 目标
按照新端扩展标准支持cml转换快应用

## 参与方
滴滴CML团队、OPPO

## 具体工作拆分和排期

## 具体工作拆分和排期

- cml-quickapp-api的工作是独立的 不依赖其他npm包的开发
- cml-quickapp-runtime 运行时的工作也是独立的 不依赖其他npm包
- cml-quickapp-plugin中的模板编译 在事件绑定的代理函数中依赖runtime 其他的工作不依赖
- cml-quickapp-ui-builtin和 cml-quickapp-ui依赖cml-quickapp-runtime和cml-quickapp-plugin的完成 才能正确执行。
- cml-quickapp-store的工作也是独立的，基本上小程序端实现是相同的。

<table>
   <tr>
    <th>工作</th><th>总体工作量</th><th>排期</th><th>负责人</th><th>进度</th><th>需要单测</th><th>备注</th>
  </tr>
  <tr>
    <td>
    <!--工作 -->
      cml-quickapp-api
    </td>
    <td>
    <!--工作量 -->
    7天
    </td>
    <td>
    <!--排期 -->5/30启动
    </td>
    <td>
    <!--负责人 -->陈磊
    </td>
    <td>
    <!--进度 -->已启动
    </td>
    <td>
    <!--是否需要单测 -->
    是
    </td>
    <td>
    <!--备注 -->
    31个chameleon的api方法对应快应用
    10个类别45个模块[每个模块有多个方法]每天5个模块
    </td>
  </tr>
  <tr>
    <td>
    <!--工作 -->
      cml-quickapp-runtime
    </td>
    <td>
    <!--工作量 -->
    7天
    </td>
    <td>
    <!--排期 -->
    6/10启动
    </td>
    <td>
    <!--负责人 -->
    陈磊
    </td>
    <td>
    <!--进度 -->
    初步完成生命周期的适配
    </td>
    <td>
    <!--是否需要单测 -->
    是
    </td>
    <td>
    <!--备注 -->
    参照chameleon-runtime，然后进行相应前端的改动。
    </td>
  </tr>
  <tr>
    <td>
    <!--工作 -->
      cml-quickapp-plugin
    </td>
    <td>
    <!--工作量 -->
    5天
    </td>
    <td>
    <!--排期 -->
    6/16启动
    </td>
    <td>
    <!--负责人 -->
    陈磊
    </td>
    <td>
    <!--进度 -->
    初步完成目录结构以及源码的编译
    </td>
    <td>
    <!--是否需要单测 -->
    是
    </td>
    <td>
    <!--备注 -->
    已实现针对CML的ProjectGraph生成相应的快应用目录结构以及源码文件
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
      cml-quickapp-ui-builtin
    </td>
    <td>
    <!--工作量 -->
    7天
    </td>
    <td>
    <!--排期 -->
    6/21启动
    </td>
    <td>
    <!--负责人 -->
    陈磊
    </td>
    <td>
    <!--进度 -->
    未启动
    </td>
    <td>
    <!--是否需要单测 -->
    否
    </td>
    <td>
    <!--备注 -->
    11个多态组件，其他的组件不是多态可以直接测试 需要依赖编译和运行时完成
    但也可以提前写好后测试
    </td>
  </tr>
  <tr>
    <td>
    <!--工作 -->
      cml-quickapp-ui
    </td>
    <td>
    <!--工作量 -->
    3天
    </td>
    <td>
    <!--排期 -->
    6/28启动
    </td>
    <td>
    <!--负责人 -->
    陈磊
    </td>
    <td>
    <!--进度 -->
    未启动
    </td>
    <td>
    <!--是否需要单测 -->
    否
    </td>
    <td>
    <!--备注 -->
    3个多态组件，其他的组件不是多态可以直接测试 需要依赖编译和运行时完成
    但也可以提前写好后测试
    </td>
  </tr>
  <tr>
    <td>
    <!--工作 -->
      cml-quickapp-store
    </td>
    <td>
    <!--工作量 -->
    3天
    </td>
    <td>
    <!--排期 -->
    7/5启动
    </td>
    <td>
    <!--负责人 -->
    陈磊
    </td>
    <td>
    <!--进度 -->
    未启动
    </td>
    <td>
    <!--是否需要单测 -->
    是
    </td>
    <td>
    <!--备注 -->
    参考chameleon-store
    </td>
  </tr>
  <tr>
    <td>
    <!--工作 -->
      联调测试
    </td>
    <td>
    <!--工作量 -->
    4天
    </td>
    <td>
    <!--排期 -->
    7/10启动
    </td>
    <td>
    <!--负责人 -->
    陈磊
    </td>
    <td>
    <!--进度 -->
    未启动
    </td>
    <td>
    <!--是否需要单测 -->
    </td>
    <td>
    <!--备注 -->
    各部分开发完成后进行联调测试
    </td>
  </tr>
</table>

### cml-quickapp-api

<table>
  <tr>
    <th>工作</th><th>工作量</th><th>排期</th><th>负责人</th><th>进度</th><th>备注</th>
  </tr>
  <tr>
    <td>
    <!--工作 -->
      alert方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    导入快应用的feature，实现对应方法
    </td>
    <td>
    <!--排期 -->
    5/30
    </td>
    <td>
    <!--负责人 -->
    陈磊
    </td>
    <td>
    <!--进度 -->
    已启动
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      canIUse方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    5/30
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      cancelAnimationFrame方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    5/30
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      chooseImage方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    5/30
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      close方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    5/30
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      confirm方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    5/31
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      cpx2px方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    5/31
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      createAnimation方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    5/31
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      get方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    5/31
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      getClipBoardData方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    5/31
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      getLaunchOptionsSync方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    5/31
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      getLocationInfo方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/3
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      getRect方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/3
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      getStorage方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/3
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      getSystemInfo方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/3
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      inSDK方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/3
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      initSocket方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/4
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      navigateBack方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/4
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      navigateTo方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/4
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      open方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/4
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      post方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/4
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      px2cpx方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/5
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      redirecquickappo方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/5
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      reload方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/5
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      removeStorage方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/5
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      request方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/5
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      requestAnimationFrame方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/6
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      setClipBoardData方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/6
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      setStorage方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/6
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      sequickappitle方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/6
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      <tr>
    <td>
    <!--工作 -->
      showToast方法实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/6
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

</table>



### cml-quickapp-runtime

<table>
  <tr>
    <th>工作</th><th>工作量</th><th>排期</th><th>负责人</th><th>进度</th><th>备注</th>
  </tr>
  <tr>
    <td>
    <!--工作 -->
     生命周期映射
    </td>
    <td>
    <!--工作量 -->
    适配从cml到快应用的生命周期函数映射关系，包括app、page、component各个的生命周期
    </td>
    <td>
    <!--排期 -->
    5/25
    </td>
    <td>
    <!--负责人 -->
    李恒、陈磊
    </td>
    <td>
    <!--进度 -->
    基本实现，待验证
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>  
  <tr>
    <td>适配options</td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/10
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    未启动
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
  <tr>
    <td>
    <!--工作 -->
     处理props
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/10
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    未启动
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     处理data
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/11
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    未启动
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     处理mixins
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/12
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     处理钩子hooks
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/12
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     处理methods
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/13
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td colspan="6">能力注入（在最早生命周期hook，对执行上下文 this 改造）</td>
  </tr>
  <tr>
    <td>
    <!--工作 -->
     处理 data【使具备响应式数据处理能力】
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/13
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     处理 computed【使具备计算属性能力】
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/14
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     处理 watch【使具备数据监听能力】
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/14
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

</table>


### cml-quickapp-plugin

<table>
  <tr>
    <th>工作</th><th>工作量</th><th>排期</th><th>负责人</th><th>进度</th><th>备注</th>
  </tr>
  <tr>
    <td>
    <!--工作 -->
     基础模板编译
    </td>
    <td>
    <!--工作量 -->
    快应用目录结构和源文件生成
    </td>
    <td>
    <!--排期 -->
    5/21
    </td>
    <td>
    <!--负责人 -->
    陈磊
    </td>
    <td>
    <!--进度 -->
    初步实现模板编译和生成快应用目录结构以及源代码
    </td>
    <td>
    <!--备注 -->
    manifest.json、签名文件等还需要进一步工作
    </td>
  </tr>
  <tr>
    <td>
    <!--工作 -->
     基本标签替换
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/17
    </td>
    <td>
    <!--负责人 -->
    李恒、陈磊
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    view => div
    如果需要的话，比如cell 替换成view
    slider-item替换成swiper-item
    </td>
  </tr>
  <tr>
    <td>
    <!--工作 -->
     c-if c-else c-else-if c-show c-for c-text c-key
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/17
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     component is 动态组件
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/18
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     c-model
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/18
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     c-bind 事件绑定 配合运行时mixins代理事件与处理事件对象
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/19
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     c-animation
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/20
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     style与class处理
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/20
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

</table>








### cml-quickapp-ui-builtin
<table>
  <tr>
    <th>工作</th><th>工作量</th><th>排期</th><th>负责人</th><th>进度</th><th>备注</th>
  </tr>
  <tr>
    <td>
    <!--工作 -->
      checkbox/radio/layout文件夹下的7个布局 组件实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/21--6/22
    </td>
    <td>
    <!--负责人 -->
    李恒、陈磊
    </td>
    <td>
    <!--进度 -->
    未启动
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
  <tr>
    <td>
    <!--工作 -->
      button 组件实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/22
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
      carousel 组件实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/22
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
      carousel-item 组件实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/22
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
      input 组件实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/23
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
      list 组件实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/23
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
      page 组件实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/24
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
      richtext 组件实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/24 - 6/25
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
      scroller 组件实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/25
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
      switch 组件实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/26
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
      textarea 组件实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/26
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
      video 组件实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/27
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
      
</table>


### cml-quickapp-ui
<table>
  <tr>
    <th>工作</th><th>工作量</th><th>排期</th><th>负责人</th><th>进度</th><th>备注</th>
  </tr>
  <tr>
    <td>
    <!--工作 -->
     c-picker-item 组件实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    6/28 -- 7/4
    </td>
    <td>
    <!--负责人 -->
    李恒、陈磊
    </td>
    <td>
    <!--进度 -->
    未启动
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
  <tr>
    <td>
    <!--工作 -->
      c-refresh 组件实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
      c-actionsheet,
  c-checkbox-group,
  c-dialog,
  c-loading,
  c-picker,
  c-picker-panel,
  c-popup,
  c-radio-group,
  c-tab,
  c-tab-item,
  c-tab-pane,
  c-tab-pane-item,
  c-tabbar,
  c-tip,
  c-toast 组件实现与测试demo
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
</table>


### cml-quickapp-store

<table>
  <tr>
    <th>工作</th><th>工作量</th><th>排期</th><th>负责人</th><th>进度</th><th>备注</th>
  </tr>
  <tr>
    <td>
    <!--工作 -->
     createStore
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    7/5 -- 7/10
    </td>
    <td>
    <!--负责人 -->
    李恒、陈磊
    </td>
    <td>
    <!--进度 -->
    计划中
    </td>
    <td>
    <!--备注 -->
    快应用目前以本地storage为主，未使用到redux、mobx等状态管理lib
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     commit
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     dispatch
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     mapState
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     mapGequickappers
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     mapMutations
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     mapActions
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>

  <tr>
    <td>
    <!--工作 -->
     registerModule
    </td>
    <td>
    <!--工作量 -->
    </td>
    <td>
    <!--排期 -->
    </td>
    <td>
    <!--负责人 -->
    </td>
    <td>
    <!--进度 -->
    </td>
    <td>
    <!--备注 -->
    </td>
  </tr>
</table>

**Comment by dreamHeroK** [comment]
关注中，怎么没后续了。

**Comment by deepkolos** [comment]
好专业的排期

**Comment by Tianfer** [comment]
先帝创业未半而中道崩殂，没有后续了？

**Comment by zheyizhifeng** [comment]
后续计划是有的


| |
陈磊
|
|
zheyizhifeng@126.com
|
签名由网易邮箱大师定制


在2019年12月18日 16:45，tianfer<notifications@github.com> 写道：

先帝创业未半而中道崩殂，没有后续了？

**Comment by WJCHumble** [comment]
不应该 closed 吧，问题很多....
