### ISSUE TITLE
希望增加例子与模板

### ISSUE THREAD

**Issue by KennyWho** [didi/chameleon#187]
目前准备迁移已有小程序到新框架，选择cml尝试时，样式上出现的问题比较多，全局flex导致样式异常难调试，一个上下自适应的flex布局，`flex-grow:1`的子容器无法程满高度。 无法满足要求，尝试多次后放弃。切换到 uni-app 很顺利的就把样式搞定。希望增加更多的模板和例子，这样方便熟悉框架的使用。否则切换和学习成本很大，一旦遇到问题，由于社区不完善，很难定位到问题和解决办法。

**Comment by startheart** [comment]
好的~后续会在官网文档增加在线demo和更多模板
