### ISSUE TITLE
希望能出一个整合多端的富文本组件

### ISSUE THREAD

**Issue by xujiupeng** [didi/chameleon#189]

**Comment by startheart** [comment]
后续会提供一个富文本组件，另外，你可以将对富文本组件的属性需求描述的详尽一些，我们会参考

**Comment by proshuai** [comment]
编辑文字（加粗、斜体、下划线、颜色、字体选择、编号、阴影、边框）

**Comment by beatles-chameleon** [comment]
https://cml.js.org/doc/component/expand/native/richtext.html?h=rich
