### ISSUE TITLE
web端 和 native端 的box-shadow 的样式咋不一致

### ISSUE THREAD

**Issue by chant520** [didi/chameleon#192]
#### 代码
```
//html
<view class="test"></view>

//css
.test{
  height: 600cpx;
  z-index: 9999;
  box-shadow: 1cpx 1cpx 20cpx #ccc;
}
```
#### weex IOS 效果图  
![IMG_1043](https://user-images.githubusercontent.com/19225259/58077605-7a392680-7bdf-11e9-9934-a912544585db.PNG)

#### web端效果图  
![image](https://user-images.githubusercontent.com/19225259/58077753-c2584900-7bdf-11e9-8a72-3b3957c99484.png)

不知道是不是我的问题，如果能整理一份通用样式列表就好了 ; 已经试过用 weex 的通用样式代替，但是不得行

**Comment by huyuangang** [comment]
weex端需要设置背景色，加个background: #fff;试试

**Comment by chant520** [comment]
@huyuangang 感谢指导，学艺不精 ，刚转到前端开发这一块
