### ISSUE TITLE
iconfont循环渲染有问题

### ISSUE THREAD

**Issue by WJer** [didi/chameleon#193]
**bug描述**
通过c-for去渲染iconfont，结果渲染不出来

**复现bug的步骤**
![image](https://user-images.githubusercontent.com/9282663/58235568-a5547f00-7d73-11e9-8664-813d1764f009.png)

展示的结果是unicode，而不是对应的图标

**Comment by WJer** [comment]
![image](https://user-images.githubusercontent.com/9282663/58297186-72f56100-7e09-11e9-94e0-14b6d79009e8.png)
这是先死的结果

**Comment by startheart** [comment]
这样写法当然渲染文本内容，不要将unicode作为双向绑定数据，直接在模板上使用unicode

**Comment by WJer** [comment]
考虑以下用这种循环的方式显示iconfont或者其他解决方案。这种使用场景很多，icon的位置也不确定，直接写在模板上就将icon的位置限制住了，所以需要通过这种方式灵活的展示

**Comment by xiongtingjin** [comment]
问题怎么给关闭了，同样遇到了这个问题，图标需要动态添加。
