### ISSUE TITLE
weex端 iconfont引入问题

### ISSUE THREAD

**Issue by shenmissing** [didi/chameleon#197]
**bug描述**
根据weex官方的步骤，复制官方案例的代码，然后不显示，只能通过这种方式才会显示
```
<text class="title2" :style="{fontFamily:'iconfont2'}">{{ iconFont }}</text> 
```
案例链接：http://dotwe.org/vue/4641bfd0ab806674d62cb00a9ad2dddb

**编译环境信息**
 - chameleon-tool 版本：0.3.2

**运行环境信息**
 - 手机机型: 小米8，安卓9

**Comment by startheart** [comment]
试了安卓没问题，如下图：
![image](https://user-images.githubusercontent.com/10693888/58308760-085a1a80-7e35-11e9-8f21-4f4595240eec.png)

**Comment by shenmissing** [comment]
仔细看下你的图  红色下面的第一行第二行  不是问题么

**Comment by startheart** [comment]
你说的那两行，在weex原生SDK效果就有问题。。。

**Comment by shenmissing** [comment]
确实兼容有问题，弃用改成图片了
