### ISSUE TITLE
carousel组件文档中，如何理解bug&tip里的修改current值？

### ISSUE THREAD

**Issue by bluefantasy728** [didi/chameleon#198]
在仿照内置组件carousel的时候，想要通过修改current的值使轮播图滚动，我是直接修改了data里的current值，结果在微信小程序里生效了，但在web端并没有生效，虽然web端里的current值确实变化了，但是轮播图并没有滚动。

> “如果希望修改current值时轮播滚动到对应carousel-item，则需要通过change事件同步current，以保证修改current的值与当前的值是不同的。”

然后我查了文档，发现carousel组件最后一句话
不是很理解这句话的意思，我在carousel标签里加了change事件，这个不是监听轮播图改变的事件么？微信端在改变current值得时候确实能触发change事件，但是web端不能，虽然web端的current值确实改变了

**Comment by huyuangang** [comment]
这里我们希望当修改default-index的值的时候能滚动到对应位置，如果不同步修改current，想一下这种场景，最开始current为1，此时滚动到2的位置，我希望手动触发滚动到1的位置，因为current的值原本就是1，所以此时并不能监听到current值的变化，也就不会滚动到对应位置了。
