### ISSUE TITLE
com1的文件夹在windows是无法创建的

### ISSUE THREAD

**Issue by ld0809** [didi/chameleon#201]
**bug描述**
com1的文件夹在windows是无法创建的

**复现bug的步骤**
1. 无法checkout代码，创建文件夹报错

**问题截图**

**编译环境信息**

**运行环境信息**
 windows8

请修改下文件夹名称，com1是windows内置关键词，禁止使用

**Comment by yylgit** [comment]
是哪个项目中有com1组件吗？还是你创建的时候报错的？

**Comment by ld0809** [comment]
> 是哪个项目中有com1组件吗？还是你创建的时候报错的？

你找个windows电脑，新建个文件夹，然后把项目checkout到这个文件夹，会报错的
fatal: cannot create directory at 'packages/chameleon-tool-utils/test/testlib/demo-project/com1': Invalid argument

你试试，还有个com2，都换个名字吧

**Comment by ld0809** [comment]
> 是哪个项目中有com1组件吗？还是你创建的时候报错的？

![微信截图_20190528144332](https://user-images.githubusercontent.com/3690692/58456531-0f479c80-8157-11e9-87e4-27ea6927d61a.png)

**Comment by ld0809** [comment]
> 是哪个项目中有com1组件吗？还是你创建的时候报错的？

chameleon/packages/chameleon-tool-utils/test/testlib/demo-project/
你们项目工程这个目录下有com1 com2的文件夹

**Comment by yylgit** [comment]
嗯，我们找个windows8电脑试试，这个文件是写单测的测试文件。

**Comment by beatles-chameleon** [comment]
0.3.3-alpha.1版本解决了该问题
