### ISSUE TITLE
组件多态web端引用vant事件报错

### ISSUE THREAD

**Issue by coderhou** [didi/chameleon#207]
**问题描述**
web端多态形式使用vant组件 cancel报错 confirm可以正常使用

**问题截图**

![image](https://user-images.githubusercontent.com/33509879/58698934-dfa2c980-83ce-11e9-9cb9-89abad2b13a0.png)

**代码截图**

![image](https://user-images.githubusercontent.com/33509879/58698980-fba66b00-83ce-11e9-998d-554c294bdd0b.png)
![image](https://user-images.githubusercontent.com/33509879/58699011-0cef7780-83cf-11e9-92d5-24fe2691ca10.png)

**编译环境信息**
 - chameleon-tool 版本：[e.g.0.1.0]
 - nodejs版本、npm版本：[node v8.11.4、npm 5.6.0]
 - 电脑操作系统： [e.g. macOS High Sierra 10.13.6]

**运行环境信息**
 - 端版本： [PC Chrome浏览器 1.30]

**Comment by coderhou** [comment]
![image](https://user-images.githubusercontent.com/33509879/58700188-fbf43580-83d1-11e9-8b54-049e0ab43f11.png)

**Comment by coderhou** [comment]
chameleon-tool@0.3.2

**Comment by startheart** [comment]
引用了vue第三方组件就不要使用cml的模板语法（包括事件对象都会经过cml事件系统处理），应该使用vue的语法

**Comment by startheart** [comment]
`<van-datetime-picker :maxDate="maxDate" :minHour="minHour" @cancel="cancel" />`

**Comment by coderhou** [comment]
![image](https://user-images.githubusercontent.com/33509879/59174999-491c9800-8b86-11e9-959a-54c4a3d27e52.png)
![image](https://user-images.githubusercontent.com/33509879/59175010-533e9680-8b86-11e9-96f5-1c38a0d3055b.png)
自定义多态组件 是用@click还是会报错的

**Comment by coderhou** [comment]
@startheart

**Comment by coderhou** [comment]
![image](https://user-images.githubusercontent.com/33509879/59175742-35befc00-8b89-11e9-9300-68f2999ec123.png)

**Comment by jimwmg** [comment]
chameleon-tool的版本和文件中引入vant组件的方式发一下

**Comment by jimwmg** [comment]
<template>
  <view>
    <view>0.32</view>
    <van-datetime-picker
       v-model="currentDate"
        type="datetime"
        :min-date="minDate"
        :max-date="maxDate"
        c-bind:confirm="handleConfirm"
        c-bind:cancel="handleCancel"
    ></van-datetime-picker>
  </view>
</template>

<script>
import 'vant/lib/index.css'; //这里引入样式，组件按下面的方式引入，多态组件 xxxx.web.cml


class VantComp implements VantCompInterface {
  props = {
    name: {
      type: String,
      default: '默认值'
    }
  }

  data = {
    minHour: 10,
      maxHour: 20,
      minDate: new Date(),
      maxDate: new Date(2019, 10, 1),
      currentDate: new Date()
  }

  computed = {
  }

  watch = {
  }
  
  methods = {
    handleConfirm(){
      console.log('handleConfirm')
    },
    handleCancel(){
      console.log('handleCancel')
    }
  }

  beforeCreate() {
  }

  created() {
  }

  beforeMount() {
  }

  mounted() {
    this.$cmlEmit('onshow',{
      value: this.name
    })
  }

  beforeDestroy() {
  }
  
  destroyed() {
  }
}

export default new VantComp();
</script>

<style >

</style>

<script cml-type="json">
{
  "base": {
    "usingComponents": {
      "van-datetime-picker":"vant/lib/datetime-picker/index"  
    }
  }
}
</script>
