### ISSUE TITLE
page组件的back  监听不到  在微信小程序上无反应

### ISSUE THREAD

**Issue by qinle123** [didi/chameleon#210]
**bug描述**
page组件的back  监听不到  在微信小程序上无反应

**复现bug的步骤**
page组件  监听back   在小程序的左上角点击返回   不能触发绑定的function

**问题截图**
![image](https://user-images.githubusercontent.com/32858228/58778975-00556400-8607-11e9-8181-5f1167ceddf0.png)

![image](https://user-images.githubusercontent.com/32858228/58779634-22e87c80-8609-11e9-86f2-a1ce1d8d0902.png)

![image](https://user-images.githubusercontent.com/32858228/58779667-38f63d00-8609-11e9-857b-58a8ebf9a6ab.png)

**编译环境信息**
 - chameleon-tool 版本：[e.g.0.1.0]
 - nodejs版本、npm版本：[node v8.11.4、npm 5.6.0]
 - 电脑操作系统： [e.g. macOS High Sierra 10.13.6]

**运行环境信息**
 - 端版本： [e.g. 微信小程序 7.0.3、weex 2.0、手机Safari浏览器 、PC Chrome浏览器 1.30]
 - 手机机型: [e.g. iPhone6 12.0]

**Comment by startheart** [comment]
查看文档 https://cml.js.org/doc/component/base/content/page.html ，这个<page/>组件提供的是weex端的能力，而不是小程序的

**Comment by ACChe** [comment]
也遇到这个问题，cml.navigateBack(-1) 在微信小程序没有触发任何生命周期函数。
从A->B,在B端修改了数据，使用cml.navigateBack(-1) 回到A，在A的 mounted() { 更新数据代码}，没有执行。 
![image](https://user-images.githubusercontent.com/1592763/59148932-81ff2480-8a41-11e9-81f4-19e7b71d92d3.png)
![image](https://user-images.githubusercontent.com/1592763/59148939-9e9b5c80-8a41-11e9-8576-dd83e0283fde.png)

**Comment by startheart** [comment]
贴下package.json

**Comment by ACChe** [comment]
![image](https://user-images.githubusercontent.com/1592763/59241721-5c3d6f80-8c3b-11e9-9a9a-de01e573d09c.png)

**Comment by startheart** [comment]
请参考升级指引
https://github.com/chameleon-team/chameleon-runtime/blob/master/CHANGELOG.md#020

**Comment by ACChe** [comment]
有N个page要用onShow(), onHide(), 就要同等的新建N个多态文件，开发时debug时要从page ，多态文件不断切换，同属一个层级的生命周期方法居然要分开不同地方，这设计未免有些繁琐。

**Comment by beatles-chameleon** [comment]
怎么理解“要从page ，多态文件不断切换，同属一个层级的生命周期方法居然要分开不同地方” ？

**Comment by beatles-chameleon** [comment]
> nShow(), onHide(), 就要同等的新建N个多态文件，开

 page 已经支持这 2 个生命周期了，感谢反馈:https://cml.js.org/doc/logic/lifecycle.html
