### ISSUE TITLE
  微信小程序 开发完了， 模拟器 ，debug  所有都好使， 推到微信公众平台， 用真实的小程序体验版， 说小程序样式不允许，，用的cml  的标准语法

### ISSUE THREAD

**Issue by shaoweiisno1** [didi/chameleon#211]
**bug描述**
描述出现的问题

  微信小程序 开发完了， 模拟器 ，debug  所有都好使， 推到微信公众平台， 用真实的小程序体验版， 说小程序样式不允许，，用的cml  的标准语法

 

**问题截图**
![image](https://user-images.githubusercontent.com/20853789/58930270-36bceb80-878d-11e9-9af7-e760e279cbef.png)

**Comment by startheart** [comment]
小程序规则更新使部分选择器不能使用：
https://developers.weixin.qq.com/community/develop/doc/000a443bf2c7c83cd307dd3d855400，目前这个提示不会响应代码的运行，后续会将这个error tip 修复
