### ISSUE TITLE
cml init component建立带路径组件名称创建路径异常

### ISSUE THREAD

**Issue by redwolf0302** [didi/chameleon#217]
**bug描述**
cml init component建立带路径组件名称创建路径异常

**复现bug的步骤**
1. cml init component
2. component name **ej-ui/ej-avatar**

**问题截图**
![image](https://user-images.githubusercontent.com/1282372/59199426-843fbb00-8bc8-11e9-8c8a-e77d6c0b7072.png)
![image](https://user-images.githubusercontent.com/1282372/59199474-a33e4d00-8bc8-11e9-8730-0c3a20274df5.png)

**编译环境信息**
 - chameleon-tool 版本：0.3.2
 - nodejs版本、npm版本：v11.4.0
 - 电脑操作系统： macOS High Sierra 10.14.5 (18F132)

**运行环境信息**
 - IDE：WebStorm

**Comment by beatles-chameleon** [comment]
这个不算异常，文件夹名称不能有/ 符号，/符号就代表要创建一级目录了

**Comment by redwolf0302** [comment]
可以支持子目录创建吗？

**Comment by beatles-chameleon** [comment]
> 可以支持子目录创建吗？
目录创建是正确的，但是组件里面的class名称中也会有/，是错的，下个版本限制一下 名称中不能有 斜杠和反斜杠
