### ISSUE TITLE
小程序支付功能支持吗

### ISSUE THREAD

**Issue by note520** [didi/chameleon#22]
**首先感谢你们的开源付出**
大概看了一遍api，没发现支付功能的api，是要自己去chameleon-api扩展吗
谢谢！

**Comment by beatles-chameleon** [comment]
首先感谢你对chameleon的支持。
目前web端在不同的webview中能使用的支付方式（支付宝webview用支付宝、微信里面只能调微信支付等）不一样。另外业务实际接入支付能力的场景也会出现不同，目前没法统一。基于此，我们并没有统一封装进跨多端接口的chameleon-api里。
我们建议你使用多态协议，根据实际业务场景进行扩展。也欢迎你有好的跨端实现方案，和我们一起交流。


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
