### ISSUE TITLE
scroller很卡

### ISSUE THREAD

**Issue by ACChe** [didi/chameleon#221]
使用了scroller在列表展示，在微信端非常的卡，客户都受不了。
机型 : [iphone 6P, iphone 7, iphone X]

**Comment by startheart** [comment]
参考 https://github.com/chameleon-team/cml-flexbox/tree/master/src/components/polyScroller 例子，小程序端代码使用的就是native 页面级滚动，很流畅，如果觉得scroller卡 又想使用scroller 定位/上拉刷新能力，可以使用多态自行扩展小程序端的<scroll-view/>组件

**Comment by ACChe** [comment]
那个例子是整个page 的view的滑动吧，这边是page里其中一部分的view需要scroller。
尝试了多态扩展了小程序端，不是c-pop不正常（没有隐藏，出现在容器的层级下），就是滑动不生效。希望能写一个出来，实在没法继续！

**Comment by startheart** [comment]
如果需要使用部分区域滚动，请扩展小程序[<scroll-view />](https://developers.weixin.qq.com/miniprogram/dev/component/scroll-view.html)组件，目前线上项目也很多这样场景

**Comment by ACChe** [comment]
https://github.com/chameleon-team/chameleon-ui-builtin/blob/master/src/components/scroller/scroller.wx.cml

cml的scroller是包的原生origin-scroll-view也卡，自行扩展会有用吗？

**Comment by ACChe** [comment]
在微信上的 “chameleon跨端“ 的官方demo也是一滑动就抖，官方不觉得需要改进一下吗？

**Comment by startheart** [comment]
小程序scroll-view 卡顿的原因很多种，需要看你的使用场景，可以到小程序社区搜索：
https://developers.weixin.qq.com/community/develop/doc/000c80048646684b04989daaa5bc00?highLine=scroll-view、
https://developers.weixin.qq.com/community/develop/doc/000ea871cc4c48990538ffbd35e400?highLine=scroll-view

**Comment by DarcyXf** [comment]
使用`<list></list>`的时候在同样遇到了卡顿的问题。发现chameleon-ui-builtin下的`<list></list>`和`<scroller>`使用有如下代码

> methods = {
      onScroll(e) {
        let detail = e.detail;
        detail.deltaX = detail.deltaX || 0;
        detail.deltaY = detail.deltaY || 0;
        **_Object.keys(detail).forEach((key) => {
          detail[key] = cml.px2cpx(detail[key]);
        })_**
        this.$cmlEmit('onscroll', detail)
        this.$cmlEmit('customscroll', detail)
      },
加粗斜体的代码注释掉，真机（iPhone6, os version:12.3 微信 version: 7.0.4)上的体验效果**会从明显的卡顿变得非常流畅**
@startheart

**Comment by DarcyXf** [comment]
`cpx2px`这个方法每次都会调用 wx.getSystemInfoSync();
这样显然是不合适的

<script cml-type="wx">
class Method implements getWidthInterface {
  getWidth() {
    const { windowWidth } = wx.getSystemInfoSync();
    return windowWidth;
  }
}

**Comment by ACChe** [comment]
@DarcyXf 用了你的方法，果然丝般顺滑！

**Comment by foreverpw** [comment]
这bug有点明显，修复了么

**Comment by beatles-chameleon** [comment]
chameleon scroller 需要对返回的滚动距离的单位进行统一转换（px2cpx），需要获取手机视窗宽度，而这一步在微信小程序是会有延迟，不可避免，如果需要更好滚动效果，请使用原生组件

**Comment by foreverpw** [comment]
> 而这一步在微信小程序是会有延迟

不能只拿一次么 @beatles-chameleon 
```
<script cml-type="wx">
class Method implements getWidthInterface {
  system = wx.getSystemInfoSync()
  getWidth() {
    const { windowWidth } = this.system;
    return windowWidth;
  }
}

export default new Method();
</script>
```

**Comment by beatles-chameleon** [comment]
👍谢谢指正，新版本已经修复，可以更新 `chameleon-api@0.5.1` 试试

**Comment by beatles-chameleon** [comment]
这个问题是我们工程师不注意用户反馈才导致犯了这么低级的错误，会做一下改进：
1、检查所有相关chameleon-api的方法，类似`getSystemInfoSync `的静态结果做缓存，更新不频繁的结果做定时缓存。
2、重视用户反馈，特别是 issue 反馈，保障 1 个工作日内做跟进。
@ACChe @foreverpw
