### ISSUE TITLE
didi的开源项目下还有一款跨小程序的开源项目mpx(https://github.com/didi/mpx),chameleon如何看待？

### ISSUE THREAD

**Issue by DarcyXf** [didi/chameleon#224]

**Comment by beatles-chameleon** [comment]
这很早就已经开源了，一开始是微信小程序增强框架。2.0继续使用微信DSL语法转成其他小程序语法，”转译原则在于，能转则转，转不了则报错提示“；api等也做了能抹平则抹平不能抹平则报错；这也是一种架构模式。目前mpx不支持web H5和native，希望继续努力。
对 Chameleon 来说无论内部和外部的有重合点的开源产品体现了这个方向的勃勃生机，同行各自努力。
