### ISSUE TITLE
在开发支付宝小程序时，IOS支持http请求，安卓不支持http，只支持https请求

### ISSUE THREAD

**Issue by penghaochen** [didi/chameleon#227]
**bug描述**
描述出现的问题
在开发支付宝小程序时，IOS支持http请求，安卓不支持http，只支持https请求，希望安卓也能支持http的请求
**复现bug的步骤**

**问题截图**

[WORKER] onerror (5) ["Uncaught [object Object]", "http://127.0.0.1:62223/index.worker.js", 1, 41411, {…}]
rl.onerror @ appx.worker.min.js:24
WebFrame.(anonymous function) @ C:\Program Files\小程序开发者工具\resources\electron.asar\renderer\api\web-frame.js:56
electron.ipcRenderer.on @ C:\Program Files\小程序开发者工具\resources\electron.asar\renderer\web-frame-init.js:36
emit @ events.js:182
error (async)
(anonymous) @ appx.worker.min.js:24
n @ appx.worker.min.js:7
(anonymous) @ appx.worker.min.js:7
(anonymous) @ appx.worker.min.js:7
common.js:3114 Uncaught {error: 20, errorMessage: "请求url不支持http,请使用https"}
fail @ common.js:3114
h @ appx.worker.min.js:24
r @ appx.worker.min.js:24
asyncAPICallbackHandler @ C:\Program Files\小程序开发者工具\resources\app\extensions\volans-ide-tiny-project.asar\static\remote-preload\bridge.js:64
(anonymous) @ VM178:1
WebFrame.(anonymous function) @ C:\Program Files\小程序开发者工具\resources\electron.asar\renderer\api\web-frame.js:56
electron.ipcRenderer.on @ C:\Program Files\小程序开发者工具\resources\electron.asar\renderer\web-frame-init.js:36
emit @ events.js:182
appx.worker.min.js:24 Uncaught (in promise) {error: 20, errorMessage: "请求url不支持http,请使用https"}

**编译环境信息**
 - chameleon-tool 版本：[e.g.0.1.0]
 - nodemeizunode v10.15.3、npm 6.4.1]
 - 电脑操作系统： [e.g. win10]

**运行环境信息**
 - 端版本： [e.iPhone6 12.0宝小程序]
 - 手机机型: [e.g. 小米8]

**Comment by beatles-chameleon** [comment]
你好，微信支付宝等小程序真机测试均需要请求https接口且这个是小程序的限制，你可以配置成https的进行真机测试。如果是开发工具，可以在详情里去掉https的限制。
