### ISSUE TITLE
全局安装不了

### ISSUE THREAD

**Issue by coding-rk** [didi/chameleon#23]
**bug描述**
npm i -g chameleon-tool 安装不了，用了各种npm 源都没用

**复现bug的步骤**
npm i -g chameleon-tool

**问题截图**
![image](https://user-images.githubusercontent.com/18101484/52026352-7905c000-2542-11e9-8068-17275f71b72c.png)

**编译环境信息**
 - nodejs版本、npm版本：[node v10.9.0、npm 6.4.0]
 - 电脑操作系统： [win10]

**Comment by beatles-chameleon** [comment]
看错误是权限的问题，看截图中的路径，尝试删除C:\User\Administrator/AppData\Roaming\npm\node_modules  目录后再进行安装
