### ISSUE TITLE
【建议】单个项目中 weex 端支持导出多个包

### ISSUE THREAD

**Issue by foreverpw** [didi/chameleon#233]
weex这边好像是通过vue-router来实现单页面路由的，是否支持多页面打包，用navigator来路由

**Comment by startheart** [comment]
可以，打开新应用参考：https://cmljs.org/doc/api/open.html#open

**Comment by foreverpw** [comment]
@startheart   希望weex打包出来就是多文件的，并且cml.navigateTo在weex端用的是weex的navigator模块，能做到吗现在。就是写完cml项目，打包weex出来就是多页面的，不是单页面应用。

**Comment by startheart** [comment]
你可以构建多个cml项目，打包生成对应weex bundle

**Comment by foreverpw** [comment]
那小程序,h5呢，如何一套代码编译多端

**Comment by beatles-chameleon** [comment]
> 那小程序,h5呢，如何一套代码编译多端


都支持

**Comment by foreverpw** [comment]
答非所问啊，构建多个cml项目，小程序怎么办，给个例子？

**Comment by foreverpw** [comment]
#242

**Comment by beatles-chameleon** [comment]
> 答非所问啊，构建多个cml项目，小程序怎么办，给个例子？

1、多个页面形成一个小应用（单个小程序、单个 weex 包含多单页、单个js 含多个单页），一个小应用对应一个 cml 项目
2、将关联性较强的几个页面形成一个闭环小应用
3、使用[cml.open](https://cmljs.org/doc/api/open.html#open) 进行多个小应用间跳转，使用[cml.navigateto](https://cml.js.org/doc/api/navigate.html#navigateto)进行小应用内部跳转

**Comment by July7788** [comment]
@beatles-chameleon 理想状态是路由、但是当前我线上APP（电商类型项目）并非都是weex。比如APP首页有4个TAB、其中2个是用的Native、两个是WEEX的。不管是weex还是native。涉及到很多weex和native
之间的跳转。所以起初采用的 [eros](https://bmfe.github.io/eros-docs/#/) 。Native和Weex打开weex 都是开新的View。

**Comment by oopyoung** [comment]
> @beatles-chameleon 理想状态是路由、但是当前我线上APP（电商类型项目）并非都是weex。比如APP首页有4个TAB、其中2个是用的Native、两个是WEEX的。不管是weex还是native。涉及到很多weex和native
> 之间的跳转。所以起初采用的 [eros](https://bmfe.github.io/eros-docs/#/) 。Native和Weex打开weex 都是开新的View。



> > 答非所问啊，构建多个cml项目，小程序怎么办，给个例子？
> 
> 在 weex 端为什么需要打出多个 JS 包？假设一个 cml 项目产出 weex 的包是 all.js ，其中包含页面逻辑x.js、y.js、z.js，分别负责 x 页面、y 页面、和公用 库的 z.js，如果分开打则重复构建出 x+z.js和y+z.js，用户打开 x、y 这2 个 页面 时，则 z.js的下载是重复浪费的。
> 而 all.js的只需下载一次，2个页面公用 all.js，当然也有一种说法是，用户只打开了 x页面不会打开y页面，那么下载all.js就是多余下载了y.js， 这是一个取舍问题，这里的逻辑设计是和微信小程序逻辑保持一致的，微信客户端能接受这种逻辑，那么我们自己的 app 最好也保持一致，既利于流程一致，有利于真正统一。
> 
> 如果你确实有这种洁癖，请考虑[combo js](https://www.google.com.hk/search?q=combo.js&oq=combo.js&aqs=chrome..69i57.3861j0j7&sourceid=chrome&%7Bgoogle:instantExtendedEnabledParameter%7Die=UTF-8)，按需加载模块，再按模块缓存和增量更新模块设计。这种事完美解决方案，可是对工程师的要求较高。
> 
> 1、多个页面形成一个小应用（单个小程序、单个 weex bundle包含多单页、单个页面（SPA)含多个单页），一个小应用对应一个 cml 项目
> 2、将业务性关联性较强的几个页面形成一个闭环小应用
> 3、使用[cml.open](https://cmljs.org/doc/api/open.html#open) 进行多个小应用间跳转，使用[cml.navigateto](https://cml.js.org/doc/api/navigate.html#navigateto)进行小应用内部跳转

这两种情况都很常见，建议chameleon针对weex端开放多页面打包的方式，以在<script cml-type="json">中进行配置实现；

**Comment by startheart** [comment]
> @startheart 希望weex打包出来就是多文件的，并且cml.navigateTo在weex端用的是weex的navigator模块，能做到吗现在。就是写完cml项目，打包weex出来就是多页面的，不是单页面应用。

可以一个仓库维护多个cml项目，打包weex出来多bundle，相对应多个web页面模板，多个小程序应用，我们很多业务场景就是采用这种方式维护，多cml项目打出的bundle相互独立，而cml.open在weex端实现应用级别跳转，底层实现就是navigator模块的原理

**Comment by snice** [comment]
谈一下在 weex 端需要打出多个 JS 包的原因，个人理解，欢迎讨论。

1. 小程序中从A页面跳转到B页面，可以通过系统Back（iOS系统侧滑返回，android返回键）到A，那么weex如果需要这种体验，目前就没法做到。

2. 在weex实际使用中，多页面需求挺多的。尤其是android系统，如果要追求页面打开速度，那么js越小越好。

3.  至于多页面（多js文件）下载浪费问题，个人觉得很正常，就像weex支持rax dsl，打包出来js就是要大很多。

4. 逻辑保持一致问题，从软件设计上讲，我是支持的。但是从用户体验上讲，这一点是不对的，用户体验给我们的感觉逻辑不一致。

如果可以通过路由配置weex打包方式：all（vue-router方式）或single（非vue-router方式，也就是单页js），这样会更好。

**Comment by beatles-chameleon** [comment]
感谢反馈 @foreverpw @July7788 @oopyoung @snice 我们尽快在[分包加载设置](https://cmljs.org/doc/example/subpage.html?h=%E5%88%86%E5%8C%85)让weex 和 web 端等统一生效。

**Comment by PerseveranceZ** [comment]
一个 JS bundle 的话，
最大的问题是性能问题，所有页面的逻辑 + store 状态常驻内存，开销是非常大的，支撑起一定规模的应用是很难的。
其次就是不同细节的体验问题。

个人觉得对于 router 和 store 这块可以在多衡量一下利弊，最好也能告知到开发者。

**Comment by startheart** [comment]
npm i chameleon-tool@1.0.6-alpha.5 -g 支持
增加name字段即可
[cml-weex-bundle](https://github.com/chameleon-team/cml-weex-multibundle)
`"mpa":{
    "weexMpa":[
      {
        "name":"addRoutes",
        "paths":["/pages/index/index","/pages/index/index3"]
      },
      {
        "paths":["/pages/index/index2"]
      }
    ]
  }`
