### ISSUE TITLE
npm i -g chameleon-tool 安装错误

### ISSUE THREAD

**Issue by 2017NewBorn** [didi/chameleon#235]
**复现bug的步骤**
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting jison-gho@0.6.1-215:
npm ERR! Verification failed while extracting jison-gho@0.6.1-215:
npm ERR! sha512-cGFo7c0it0PDSbcRYReA4XdoPCtbz3/tVhZ++qfxAkhBNDnLj/S+5A85gdbWiK0HCfqlZ81wbgiyWhaqrk4ViQ== integrity checksum failed when using sha512: wanted sha512-cGFo7c0it0PDSbcRYReA4XdoPCtbz3/tVhZ++qfxAkhBNDnLj/S+5A85gdbWiK0HCfqlZ81wbgiyWhaqrk4ViQ== but got sha512-U5qJSK2SL68AU6r8Sf8mXqvOZz9ut3MSgLLOSkrg6gQ0fwlO2OJLu0KLRZdj6SGUNe805NH/upjYwiZPh4nFRA==. (2230336 bytes)

**问题截图**
![image](https://user-images.githubusercontent.com/17246533/59760032-e92f9b00-92c3-11e9-9c3c-429454727fa2.png)

**编译环境信息**
编译环境信息
npm@6.7.0
node@v11.10.0
电脑操作系统：macOS Mojave 10.14.5

**Comment by luobinbinchina** [comment]
你这个是安装环境问题吧，npm源是不是有问题？可以指定一下源再试试

**Comment by 2017NewBorn** [comment]
替换node v10.15.0 (npm v6.4.1)后, 执行就可以了.
