### ISSUE TITLE
列表循环尾部再加一个cell标签，会穿插到循环列表中

### ISSUE THREAD

**Issue by xinglai-orange** [didi/chameleon#239]
## 问题描述
做上拉加载更多功能，在循环列表尾部添加一个终止提示，结果展示到循环列表中间了

## 问题代码
```
<list
      bottom-offset="100cpx"
      c-bind:scrolltobottom="onBottom"
      height="{{scrollHeight}}"
      class="productList"
    >
        <cell
          c-for="{{productLists}}"
          data-idx="{{index}}"
          class="productLi"
        >
            <text class="product-title">{{item.insuranceTitle}}</text>
            <text class="product-desc">{{item.designIdea}}</text>
            <view class='justify-between'>
              <text class='price'>{{item.productPrice}}元</text>
              <text class='product-button'>查看详情</text>
            </view>
        </cell>
        <cell c-if="{{!canScroll}}">
          <text class='not-more'>没有更多数据了...</text>
        </cell>
    </list>
```

## 问题截图
![image](https://user-images.githubusercontent.com/24563216/60155973-03b2c880-981e-11e9-86ac-16e4f553e4b2.png)

**编译环境信息**
 - chameleon-tool 版本：[e.g.0.1.0]
 - nodejs版本、npm版本：[node v8.11.4、npm 5.6.0]
 - 电脑操作系统： [window 10]

**运行环境信息**
 - 端版本： [e.g. 微信小程序 ]

**Comment by luobinbinchina** [comment]
![image](https://user-images.githubusercontent.com/34769734/60425497-38ab8a80-9c25-11e9-8e6b-532cc29786c9.png)
你试试把ProductList全量赋值，数组这块是没办法监听到单个的变化从而触发渲染
