### ISSUE TITLE
开发模式启动项目 weex 一直报 版本不匹配

### ISSUE THREAD

**Issue by nannan527** [didi/chameleon#24]
**bug描述**
开发模式启动项目 weex 一直报 版本不匹配

**复现bug的步骤**
cml dev

**问题截图**
<img width="969" alt="wx20190131-104907 2x" src="https://user-images.githubusercontent.com/4023533/52027529-bb310080-2546-11e9-8bcf-f28dd2706901.png">

**编译环境信息**
 - chameleon-tool 版本：[e.g.0.1.0]
 - nodejs版本、npm版本：[node v11.9.0、npm 6.5.0]
 - 电脑操作系统： [e.g. macOS High Sierra 10.13.6]

**Comment by beatles-chameleon** [comment]
> **bug描述**
> 开发模式启动项目 weex 一直报 版本不匹配
> 
> **复现bug的步骤**
> cml dev
> 
> **问题截图**
> <img alt="wx20190131-104907 2x" width="969" src="https://user-images.githubusercontent.com/4023533/52027529-bb310080-2546-11e9-8bcf-f28dd2706901.png">
> 
> **编译环境信息**
> 
> * chameleon-tool 版本：[e.g.0.1.0]
> * nodejs版本、npm版本：[node v11.9.0、npm 6.5.0]
> * 电脑操作系统： [e.g. macOS High Sierra 10.13.6]

你不是用的npm安装的吧

**Comment by nannan527** [comment]
@beatles-chameleon 用的是 cnpm ， npm 安装一直报错 装不上

**Comment by nannan527** [comment]
@beatles-chameleon  我修复了我的npm ，用npm 安装 weex 还是报这个错误，请问怎么样能解决呢？

**Comment by nannan527** [comment]
@beatles-chameleon 谢谢， 解决了， 删除/usr/local/lib/node_modules/chameleon-tool  下的全部文件重新用 npm 安装，就能跑起来了，cnpm 安装貌似vue 和vue-template-compiler的版本会不一致
