### ISSUE TITLE
建议脚手架工具提供接口修改内部webpack配置

### ISSUE THREAD

**Issue by iamonox** [didi/chameleon#247]
常见的需求，如样式自动引入全局变量、mixins，自动生成iconfont；都需要修改webpack配置。
后期规划中似乎没有看到脚手架相关的规划，建议官方脚手架工具提供接口修改内部webpack配置，让开发者能充分利用webpack插件资源提高开发效率。

**Comment by GongLLei** [comment]
目前已经支持修改webpack配置，具体见[修改webpack配置](https://cmljs.org/doc/framework/config.html#%E4%BF%AE%E6%94%B9webpack%E9%85%8D%E7%BD%AE)
