### ISSUE TITLE
【功能请求】配置微信小程序端组件样式隔离选项

### ISSUE THREAD

**Issue by iamonox** [didi/chameleon#249]
微信小程序组件允许设置addGlobalClass: true增加全局样式，chameleon目前无法配置这个选项，runtime代码也表示直接覆盖了options选项。
![20190724172039](https://user-images.githubusercontent.com/7895047/61781741-79b74900-ae37-11e9-886c-f90d768c35e6.png)

目前在微信小程序端实现全局样式，如图标字体样式，只有这个选项能做到。使用import的话，构建后每个组件的wxss都会有相同的代码。

希望不仅仅在多态组件上开放这个配置，因为很多时候只是需要添加个addGlobalClass: true而已

**Comment by beatles-chameleon** [comment]
我们调研下，如果适用跨多端，后续添加上去，请关注此issue

**Comment by jimwmg** [comment]
1.全局样式可以参考：https://cmljs.org/docs/config.html?#%E5%85%A8%E5%B1%80%E6%A0%B7%E5%BC%8F
2.chameleon-runtime@1.0.1 支持了options 自定义配置
