### ISSUE TITLE
项目启动之后页面显示，“未启动web端构建”、“未启动weex端构建”、“未启动微信小程序构建”等问题

### ISSUE THREAD

**Issue by xingzhenhe** [didi/chameleon#25]
![image](https://user-images.githubusercontent.com/38931279/52028679-d271ed00-254a-11e9-9d8d-c7e07b1fabd0.png)

**Comment by beatles-chameleon** [comment]
辛苦提供以下信息，方便定位问题：
 系统版本
 chameleon-tool版本
执行的什么命令
命令行有报错信息吗

**Comment by xingzhenhe** [comment]
**编译环境信息**
 - chameleon-tool 版本：0.0.13
 - nodejs版本、npm版本：[node v8.11.1、npm 5.6.0]
 - 电脑操作系统： win10 64bit

执行命令行无报错
![image](https://user-images.githubusercontent.com/38931279/52035899-8e8ce100-2566-11e9-8d7c-64f2c35d15ba.png)

**Comment by xingzhenhe** [comment]
![image](https://user-images.githubusercontent.com/38931279/52035920-b2502700-2566-11e9-8304-feb4a6765665.png)

**Comment by beatles-chameleon** [comment]
看一下浏览器的调试窗口，有没有报错，可能是浏览器不支持websocket

**Comment by xingzhenhe** [comment]
看了一下，谷歌、火狐正常，360、ie、QQ浏览器就不行

**Comment by GloriaCHL** [comment]
请问这问题有解决吗？我今天也遇到了。项目是别人建的，我本地运行就碰到这问题。但我本地初始化出来的项目就可以正常运行。
环境：
chameleon-tool@1.0.6
node@14.15.0
npm@6.14.8
OS: macos
