### ISSUE TITLE
vscode插件v0.2.8版本无法下载安装

### ISSUE THREAD

**Issue by JTT5327** [didi/chameleon#250]
**bug描述**
vscode插件v0.2.8版本无法下载安装

**复现bug的步骤**
1、从vscode商店内无法自动下载安装；
2、手动下载，也无法正常安装，一直显示重新加载；

**问题截图**
![image](https://user-images.githubusercontent.com/13061925/61990912-c2f7da80-b07b-11e9-994c-5f11a511076e.png

![image](https://user-images.githubusercontent.com/13061925/61990918-d99e3180-b07b-11e9-85ac-5c0091c02cec.png)

**Comment by JTT5327** [comment]
vscode 版本1.22.2

**Comment by cheer555** [comment]
建议升级到vscode最新版本 1.36.1 试试
