### ISSUE TITLE
input标签自定义样式后输入会闪烁

### ISSUE THREAD

**Issue by oopyoung** [didi/chameleon#251]
平台：weex
input标签在cstyle里增加自定义样式后，输入会闪烁，copy的官方示例的代码也是一样，主要是color属性设置过后这种现象尤为明显；另外：chameleon app的组件示例现在打不开了 ~

**Comment by beatles-chameleon** [comment]
chameleon app的组件示例现在可以正常打开，input的问题我们会继续跟进。

**Comment by zyt0103** [comment]
input的问题，建议升级chameleon-ui-builtin到最新版4.0.1-alpha.1
