### ISSUE TITLE
微信小程序端会删除mixins中的生命周期钩子

### ISSUE THREAD

**Issue by iamonox** [didi/chameleon#252]
**bug描述**
多个页面使用同一个对象作为mixins项，在微信小程序端注册页面时会删除这个对象里的cml生命周期钩子，导致之后注册其他用了相同mixins页面时，cml生命周期钩子丢失

**复现bug的步骤**
两个页面使用同一个对象作为mixins项
两个页面export前console输出这个对象
微信小程序开发者工具查看输出

**问题截图**
![微信小程序端](https://user-images.githubusercontent.com/7895047/62194886-55b2b500-b3ad-11e9-9f3b-f4f42b4c55b1.png)
![Web端](https://user-images.githubusercontent.com/7895047/62194887-55b2b500-b3ad-11e9-9cab-58efbbbf6571.png)

**编译环境信息**
 - chameleon-tool 版本：0.3.3

**运行环境信息**
 - 端版本：微信小程序开发者工具

**Comment by iamonox** [comment]
我把chameleon-runtime/src/platform/common/proto/MiniVmAdapter.js
第27行this.initHooks(this.options)注释掉就正常了。

这个initHooks把mixins中的生命周期钩子取出来放在options上，还删除原mixin上的钩子。。
初略看了下源码，后面的initMixins和resolveOptions似乎就是做这个操作，initHooks当中的操作似乎是多余的。

**Comment by beatles-chameleon** [comment]
安装 chameleon-runtime@0.3.2-alpha.0 试试

**Comment by iamonox** [comment]
> 安装 chameleon-runtime@0.3.2-alpha.0 试试

这个版本没问题了
