### ISSUE TITLE
windows系统下 chameleon-tool最新0.4.0版本init project，执行cml dev启动报错 

### ISSUE THREAD

**Issue by MT119333994** [didi/chameleon#260]
**bug描述**
chameleon-tool最新0.4.0版本init project，执行cml dev启动报错 

**复现bug的步骤**
1. 执行npm remove -g chameleon-tool，卸载老版本
2. 安装最新版本 npm i -g chameleon-tool
3. 创建新项目 cml init project
4. 切换到项目根目录执行cml dev
5. 看到报错 ，虽然提示启动成功，但是对应的编译结果，比如说h5就没有正常显示

**问题截图**
 ERROR  Failed to compile with 22 errors                                                                    

These relative modules were not found:

* ./Users/11933/AppData/Roaming/npm/node_modules/chameleon-tool/node_modules/interface-loader/node_modules/mvvm-interface-parser/runtime/checkWrapper.js in ./node_modules/chameleon-api/src/interfaces/px2cpx/getWidth.interface, ./node_modules/chameleon-api/src/interfaces/setTitle/index.interface and 9 others
* ./Users/11933/AppData/Roaming/npm/node_modules/chameleon-tool/node_modules/interface-loader/node_modules/mvvm-interface-parser/runtime/copyProto.js in ./node_modules/chameleon-api/src/interfaces/px2cpx/getWidth.interface, ./node_modules/chameleon-api/src/interfaces/setTitle/index.interface and 9 others

[INFO] Listening at http://192.168.31.135:8000/preview.html
[INFO] Syntax check results:
Congratulations! Everything is OK!

**编译环境信息**
 - chameleon-tool 版本：[0.4.0]
 - nodejs版本、npm版本：[node v10.16.1、npm 6.9.0]
 - 电脑操作系统： [windows 10 1809]
  "dependencies": {
    "chameleon-api": "0.5.4",
    "chameleon-runtime": "0.3.2",
    "chameleon-store": "0.1.0",
    "chameleon-ui-builtin": "0.4.1",
    "cml-ui": "0.3.1"
  }

**运行环境信息**
无

**Comment by beatles-chameleon** [comment]
看下你这两个路径下有没有安装上这个包
./Users/11933/AppData/Roaming/npm/node_modules/chameleon-tool/node_modules/interface-loader/node_modules/mvvm-interface-parser/runtime/checkWrapper.js


./Users/11933/AppData/Roaming/npm/node_modules/chameleon-tool/node_modules/interface-loader/node_modules/mvvm-interface-parser/runtime/copyProto.js

**Comment by MT119333994** [comment]
没有
![image](https://user-images.githubusercontent.com/8630511/62874397-bd74e280-bd53-11e9-950f-4d0258eea82c.png)

**Comment by jimwmg** [comment]
用npm源重新安装下试试

**Comment by L-cw** [comment]
我也遇到了这个问题，路径下是有这两个文件的，
![image](https://user-images.githubusercontent.com/23190216/62930871-daf78a00-bdef-11e9-88e0-c7b90f5e37a2.png)

**Comment by 132liyh** [comment]
chameleon-api
这个文件夹都没有，

**Comment by 132liyh** [comment]
更新之前0.3.2都是好的

**Comment by beatles-chameleon** [comment]
正在看这个问题，大家先安装 0.3.2 版本`npm i -g chameleon-tool@0.3.2`

**Comment by startheart** [comment]
![image](https://user-images.githubusercontent.com/10693888/63097646-96aceb00-bfa3-11e9-8388-717674d916ad.png)
![image](https://user-images.githubusercontent.com/10693888/63097653-9ca2cc00-bfa3-11e9-9cbd-48d2e561259b.png)
按照你的windows10系统，node版本10.16测试后，依然没有复现error，可能需要在其他电脑再试试

**Comment by MT119333994** [comment]
已解决，是因为windows的文件权限问题，有部分文件权限不足导致读取不到，虽然具体原因还没找到，0.3.3就没这个问题

各位如果使用碰到一样的问题，可以将模块与缓存目录设置到非系统盘即可。

可以参考如下步骤：
1. 首先执行如下命令，目录可以自行修改
npm config set prefix "D:\node\npm_modules" //全局模块存放路径 
npm config set cache "D:\node\npm_cache" //cache路径
2. 设置环境变量
a. 创建 NODE_PATH=D:\node\npm_modules\node_modules
b. Path中的原npm路径修改为 D:\node\npm_modules

然后就可以了

**Comment by iamonox** [comment]
https://github.com/didi/chameleon/blob/9f69afbeda98fc3fd0d45d217aa5fb839256e19b/packages/chameleon-tool-utils/src/index.js#L1001-L1016

好像是chameleon-tool和项目不在一个盘导致的，1008行删除了盘符，可是注释掉这一句其他地方会报错，我在chameleon-tool所在盘新建的项目就没问题。

@MT119333994 的解决方法对我无效，有效也可能是他们刚好把全局模块路径移动到项目所在盘了。。

**Comment by BenjaminFF** [comment]
@iamonox 我在chameleon-tool所在盘新建的项目也没问题。

**Comment by bestprize999** [comment]
这个问题解决了没？我的1.0.2有问题，0.3.2没问题。

**Comment by jimwmg** [comment]
npm i chameleon-tool@1.0.3-alpha.0 -g
