### ISSUE TITLE
web端自定义组件上的tap被转为click.native导致的问题

### ISSUE THREAD

**Issue by iamonox** [didi/chameleon#270]
https://github.com/didi/chameleon/blob/39d14aec7ebe5b25866364714649618884da2ec9/packages/chameleon-template-parse/src/parser/parse-event.js#L31-L45

web端，自定义组件上的tap会被转换为click.native，**导致在自定义组件上阻止tap事件冒泡无效（变成阻止click冒泡了，可是父元素绑定的是tap事件）**。
我尝试删除转换逻辑，然后直接将tap加入originEvents，可正常工作。

chameleon-runtime中web端已实现可通过v-on native捕获的cml$tap事件。
https://github.com/chameleon-team/chameleon-runtime/blob/5e4c66e31cd4b6d65b2f8a7d5abe03594e507bcb/src/platform/web/render/lib/gesture.js#L364-L367

chameleon-vue-precompiler中也已将tap改为cml$tap。
https://github.com/didi/chameleon/blob/39d14aec7ebe5b25866364714649618884da2ec9/packages/chameleon-vue-precompiler/lib/precompiler/hooks/events.js#L126-L139

是否不再需要将tap转为click.native？

**Comment by iamonox** [comment]
修改源码后，tap不转成click.native ，而是转成tap.native，是正常工作的。

```js
   let originEvents = ['tap', 'click', 'touchstart', 'touchmove', 'touchend', 'touchcancel'];

    if (type === 'web') { // cml标签或者cml组件
      // web端非第三方UI库的上的tap和click都处理成tap;
      if (isNotNativeComp || tagName === 'component') { // cml组件上的tap和click都处理成 click.native
        originEvents.includes(node.name.name) && (node.name.name = `${node.name.name}__CML_NATIVE_EVENTS__`);
      } else if (isNativeComp) {
        // native组件不处理名字
      } else { // 普通标签都处理成tap
        let isOriginTag = tagName.indexOf('origin-') === 0;
        if (!isOriginTag) { // 如果是原生 origin- 开头的标签，那么click不要处理成tap
          node.name.name === 'click' && (node.name.name = 'tap');
        }
      }
    }
```

**Comment by jimwmg** [comment]
npm i chameleon-tool@1.0.3-alpha.0 -g
