### ISSUE TITLE
api为28，Canval clipRect不兼容

### ISSUE THREAD

**Issue by fujianlian** [didi/chameleon#277]
**bug描述**
targetSdkVersion改为28，运行报错

**复现bug的步骤**
下载Android示例demo，修改targetSdkVersion为28，扫码进入页面报错

**问题截图**
![image](https://user-images.githubusercontent.com/12555302/64150864-b5dcc100-ce5b-11e9-95c8-3507842cbe25.png)
![image](https://user-images.githubusercontent.com/12555302/64150876-baa17500-ce5b-11e9-9e2b-0f8aaa6edb5e.png)

编译环境信息

chameleon-tool 版本：[1.0.2]
nodejs版本、npm版本：[node v8.10.0、npm 6.9.2]
电脑操作系统： [macOS High Sierra 10.14.6]
运行环境信息

手机机型: [荣耀10 9.0]

**Comment by beiyehou** [comment]
@fujianlian  你好，请问这个扫描用的是 我们官方的 cml-playground 还是 weex-playground ？

**Comment by fujianlian** [comment]
@beiyehou 官方[Android sdk](https://github.com/chameleon-team/chameleon-sdk-android)克隆值本地，扫码是自己app实现的。问题是引入com.taobao.android:weex_sdk包使用的Canval的clipRect方法，在Android P中会报 java.lang.IllegalArgumentException: Invalid Region.Op错误，当把主项目中targetSdkVersion设置改为28就会报错，targetSdkVersion低于28没有报错
