### ISSUE TITLE
cml-language-support的ide插件显示异常

### ISSUE THREAD

**Issue by nadirvishun** [didi/chameleon#282]
**bug描述**
文档中描述cml-language-support支持Idea、Webstorm 插件，但是测试Idea、phpStorm（与webstorm基本没区别）下都提示异常，由于没有Webstorm所以未测试

**复现bug的步骤**
正常安装插件重启后就显示异常

**问题截图**
![图片](https://user-images.githubusercontent.com/5761981/64509898-54ad6580-d313-11e9-9189-9c06a16efaa2.png)

**编译环境信息**
 - chameleon-tool 版本：[1.0.3-alpha.0]
 - nodejs版本、npm版本：[node v10.15.3、npm 6.10.3]
 - 电脑操作系统： win10
- idea版本：2019.1.2
- phpStorm版本：2019.1.2

**Comment by beatles-chameleon** [comment]
目前vscode编辑插件 "cml" 支持的功能比较完善，而其他编辑器只支持了语法高亮功能，建议使用vscode，提升开发体验，后期我们会尽力为其他编辑器也提供更完善的插件功能
