### ISSUE TITLE
单页面修改导航栏标题

### ISSUE THREAD

**Issue by mlyz-wdy** [didi/chameleon#287]
单页面修改标题内容，标题未更改，配置不生效

![image](https://user-images.githubusercontent.com/29471051/64748588-34fd8380-d545-11e9-8075-9cf8429a4fe3.png)

![image](https://user-images.githubusercontent.com/29471051/64748603-3dee5500-d545-11e9-9efd-0738aac209bb.png)

**Comment by itwdy** [comment]
![image](https://user-images.githubusercontent.com/29471051/64748697-9aea0b00-d545-11e9-9ac4-ea93d044b514.png)

**Comment by startheart** [comment]
是不是使用了[page组件](url),title属性会修改页面title
