### ISSUE TITLE
内置组件使用报错（refresh-view）

### ISSUE THREAD

**Issue by wuanyang** [didi/chameleon#289]
按照文档的示例，编译报错，页面可以正常显示。
编译报错：
`template errors:
[2 (line), 1 (column)] tag: "refresh-view" is either not allowed in this template or not referenced as a component`

逻辑bug:
如果refresh-view配合tabbar来使用，如果tabbar对应的页面都含有refresh-view组件，第一个tab对应的refresh-view组件，会在其他的tab中被触发，而且会被重复触发。

**Comment by beatles-chameleon** [comment]
请帖下示例代码

**Comment by wuanyang** [comment]
http://note.youdao.com/noteshare?id=162eee85cacbbf279ca082db4fce9610
我放在有道云上，您可以看下，这个触发机制貌似有点问题。

**Comment by zyt0103** [comment]
refresh-view在小程序中的触发机制，就是页面级的，不支持组件的刷新

**Comment by asd123freedom** [comment]
编译的报错是可以忽略的么？

**Comment by xztl** [comment]
同样出现改问题，求解
