### ISSUE TITLE
子组件emit事件h5接收不到微信却可以

### ISSUE THREAD

**Issue by xxvv** [didi/chameleon#29]
**bug描述**
子组件emit事件h5接收不到微信却可以

**复现bug的步骤**
1.子组件emit click事件  
```
this.$cmlEmit('click', e)
```
2. 父组件接收
```
<v-item :disabled="disabled" extra="" @click="disabledHandler">Click to disable</v-item>
```

**问题截图**

**编译环境信息**
- chameleon-tool 版本：[0.0.13]
- nodejs版本、npm版本：[node v9.9.0、npm 6.5.0]
- 电脑操作系统： [window 10]

**运行环境信息**
 - 端版本： [微信小程序 1.02.1901230]

**Comment by beatles-chameleon** [comment]
自定义事件名 暂时不支持和 原生事件名“click”重名哈～
