### ISSUE TITLE
tabbar找不到组件

### ISSUE THREAD

**Issue by TomVista** [didi/chameleon#291]
**bug描述**
描述出现的问题
`[CML warn]: RuntimeCore start reaction error!`
`未在tabbar 中配置的list中compName中找到对应的组件名; [Component] Lifetime Method Error @ npm/cml-ui/components/c-tabbar/c-tabbar#(anonymous)
Error: 未在tabbar 中配置的list中compName中找到对应的组件名`

**复现bug的步骤**

**问题截图**
![image](https://user-images.githubusercontent.com/42435611/65007088-9e133b80-d937-11e9-96b2-5eccb395ed03.png)
![image](https://user-images.githubusercontent.com/42435611/65007102-a9666700-d937-11e9-90f3-9d67f18147da.png)
![image](https://user-images.githubusercontent.com/42435611/65007120-b6835600-d937-11e9-80de-f4036da095b4.png)

**编译环境信息**
 - chameleon-tool 版本：[1.0.3]
 - nodejs版本、npm版本：[node v8.10.0、npm 5.6.0]
 - 电脑操作系统： [win10]

**运行环境信息**
 - 端版本： [e.g. 微信小程序 2.7]

**Comment by TomVista** [comment]
tabbar 功能正常使用

**Comment by TomVista** [comment]
src拿出来新建项目,,,好了,我可真日了够了

**Comment by TomVista** [comment]
还是不行,,我加个组件,任然出这个错误

**Comment by beatles-chameleon** [comment]
贴下tabbar使用的完整代码

**Comment by TomVista** [comment]
不知道出了什么错误,复制官网实例改了改可以了.果然,还是我菜
