### ISSUE TITLE
微信原生第三方组件支持props传值吗?

### ISSUE THREAD

**Issue by TomVista** [didi/chameleon#293]
![image](https://user-images.githubusercontent.com/42435611/65228976-07dd4200-dafe-11e9-91c4-148cb1d8dd61.png)

**Comment by TomVista** [comment]
另外各种校验 只会在第一次cml dev时有,,保存文件没有校验 是bug还是feature

**Comment by beatles-chameleon** [comment]
微信原生第三方组件支持props传值
