### ISSUE TITLE
点击进行图片变换时，切换有延时。一般要等0.1s～0.3s才会切换。

### ISSUE THREAD

**Issue by qiuzhaohai** [didi/chameleon#294]
**bug描述**

1. 点击进行图片变换时，切换有延时。一般要等0.1s～0.3s才会切换。肉眼可见的那种变换，就很难受

**问题截图**
没发截图看效果，不过你们自己实现的时候也会出现。

**编译环境信息**
 - chameleon-tool 版本：[e.g.0.1.0]
 - nodejs版本、npm版本：[node v8.11.4、npm 5.6.0]
 - 电脑操作系统： [e.g. macOS High Sierra 10.13.6]

**运行环境信息**
 - 端版本： [e.g. 微信小程序 7.0.3、weex 2.0、手机Safari浏览器 、PC Chrome浏览器 1.30]
 - 手机机型: [e.g. iPhone6 12.0]

**Comment by beatles-chameleon** [comment]
贴下完整代码

**Comment by jimwmg** [comment]
之所以会有图片切换的延迟，可能是因为使用的网络图片，可以参考 https://cml.js.org/doc/framework/source_location.html?h=inline
将图片改为 base64 的形式

**Comment by QuiZhaoHai** [comment]
非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JiM-W"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月12日(星期四) 中午11:35
收件人:&nbsp;"didi/chameleon"<chameleon@noreply.github.com&gt;;
抄送:&nbsp;"邱昭海"<593526370@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [didi/chameleon] 点击进行图片变换时，切换有延时。一般要等0.1s～0.3s才会切换。 (#294)




之所以会有图片切换的延迟，可能是因为使用的网络图片，可以参考 https://cml.js.org/doc/framework/source_location.html?h=inline
 将图片改为 base64 的形式
