### ISSUE TITLE
XEditor无法使用？

### ISSUE THREAD

**Issue by zerofront** [didi/chameleon#296]
**bug描述**
XEditor是一个能快速制作、发布上线多端页面的平台	xeditor接入滴滴云，进度80%	

**复现bug的步骤**
在github文档找不到XEditor的资料，在周报有提现

**问题截图**
XEditor外界是否可用？还是只是滴滴内部可用？

**Comment by beatles-chameleon** [comment]
目前只是内部可用，正在走开源审核流程，预计下个月对外开放

**Comment by ruapapanoob** [comment]
> 目前只是内部可用，正在走开源审核流程，预计下个月对外开放

XEditor还是只是滴滴内部可用吗？

**Comment by startheart** [comment]
现已对外开放入口，请体验：https://api.didiyun.com/xeditor/home/popular
