### ISSUE TITLE
chameleon-tool 0.0.11创建demo项目todo运行后无任何页面

### ISSUE THREAD

**Issue by tjhyupo505** [didi/chameleon#3]
cml版本： chameleon-tool@0.0.11
操作系统： CentOS Linux release 7.2.1511 (Core) 
nodejs： v10.15.0
浏览器： google chrome  51.0.2704.106 (64-bit)

执行命令：
cml init project --demo todo
cd todo
cml dev

只干了这么3个命令。

浏览器运行起来后预览无任何页面。

**Comment by beatles-chameleon** [comment]
> cml版本： chameleon-tool@0.0.11
> 操作系统： CentOS Linux release 7.2.1511 (Core)
> nodejs： v10.15.0
> 浏览器： google chrome 51.0.2704.106 (64-bit)
> 
> 执行命令：
> cml init project --demo todo
> cd todo
> cml dev
> 
> 只干了这么3个命令。
> 
> 浏览器运行起来后预览无任何页面。

原因是使用了object.entries方法，可以先升级浏览器版本，下个版本会修复此问题
