### ISSUE TITLE
修改示例文章的开发命令错误

### ISSUE THREAD

**Issue by Tianfer** [didi/chameleon#302]
**bug描述**
https://mp.weixin.qq.com/s/N8PpxRHHtlIHVlemQ1Gepg
这是《青桔单车 chameleon 跨平台实践分享》，该文章下的 工程化 > 常用执行命令
- cml build `编译全部`，cml wx dev `编译微信`, 构建生产环境

应该为
- cml build `编译全部`，cml wx build `编译微信`, 构建生产环境

**Comment by beatles-chameleon** [comment]
感谢
