### ISSUE TITLE
数据 mock 的问题

### ISSUE THREAD

**Issue by wuazhu** [didi/chameleon#306]
**bug描述**
根据官网文档配置 mock 数据, web 端可以正常发送请求并请求到数据, 在微信开发者工具中请求未发送, 报错:
1. VM2543:1 Cannot send network request to localhost.
2. VM2543:1 request:fail url not in domain list

**复现bug的步骤**
如官网所示, 仅仅改了 publicPath , apiPrefix 及平台,详细如下
```
publicPath = '/static/'
apiPrefix = '本地启动 web 页面的 ip 及端口'
platforms = ['web', 'wx']
```
**问题截图**

![image](https://user-images.githubusercontent.com/15375121/66694914-e41baf00-eceb-11e9-9561-6e4e312eb887.png)

**编译环境信息**
 - chameleon-tool 版本：chameleon-tool@1.0.3
 - nodejs版本、npm版本：[node v8.11.4、npm 5.6.0]
 - 电脑操作系统： [e.g. macOS High Sierra 10.13.6]

**运行环境信息**
 - 端版本： [e.g. 微信小程序最新版,1.02.1907300 、PC Chrome浏览器 版本 75.0.3770.142（正式版本） （64 位）]
 - 手机机型: [e.g. iPhonexr 13.1.2]

**Comment by beatles-chameleon** [comment]
本地开发调试请关闭微信开发者工具的不校验合法域名
![image](https://user-images.githubusercontent.com/44267840/66750229-8095ab00-eebe-11e9-973a-5b87f99fd65f.png)

**Comment by wuazhu** [comment]
> 本地开发调试请关闭微信开发者工具的不校验合法域名
> ![image](https://user-images.githubusercontent.com/44267840/66750229-8095ab00-eebe-11e9-973a-5b87f99fd65f.png)

麻烦问下是不是只有在扫码情况下才能接口调用, 在微信小程序开发者工具里面是无法调试本地 mock 的?

**Comment by beatles-chameleon** [comment]
勾选就没可以调试本地 mock 的

**Comment by wuazhu** [comment]
多谢, 第一次就是这样配置不行,. 后来在搞了一下才可以...
