### ISSUE TITLE
cell中布局的问题

### ISSUE THREAD

**Issue by chenzefeng09** [didi/chameleon#308]
**bug描述**
cell中的内容无法横向排列

**复现bug的步骤**

`<template>`
`<list height="{{-1}}">`
`  <cell style="flex-direction:row">`
`    <text c-for="{{[1,2,3]}}" c-for-index="index" c-for-item="item" class="first-com-text">{{item}}</text>`
`  </cell>`
`</list>`
`</template>`
`<script>`
`class FirstCom {}`
`export default new FirstCom();`
`</script>`
`<style scoped>`
`.first-com-text {`
`  color: #0f0;`
`}`
`</style>`
`<script cml-type="json">`
`{`
		
`}`
`</script>`

这上面段代码中，123是竖着排列的，flex-direction:row没有起作用。但在下面这段代码中，123就是横着排列的，这两种写法按文档不应该是一样的布局吗？区别就是cell里又套了一层view标签。微信小程序端发现的这个问题。

`<template>`
`<list height="{{-1}}">`
`  <cell>`
 **`   <view style="flex-direction:row">`**
`      <text c-for="{{[1,2,3]}}" c-for-index="index" c-for-item="item" class="first-com-text">{{item}}</text>`
**`    </view>`**
`  </cell>`
`</list>`
`</template>`
`<script>`
`class FirstCom {}`
`export default new FirstCom();`
`</script>`
`<style scoped>`
`.first-com-text {`
`  color: #0f0;`
`}`
`</style>`
`<script cml-type="json">`
`{`
		
`}`
`</script>`

**问题截图**
![image](https://user-images.githubusercontent.com/7556537/66807570-e84e0380-ef5b-11e9-875d-97bec1e6e105.png)
![image](https://user-images.githubusercontent.com/7556537/66807603-fb60d380-ef5b-11e9-8564-9d204b5981e8.png)

**编译环境信息**
 - chameleon-tool 版本：[1.0.3]
 - nodejs版本、npm版本：[node v11.1.0、npm 6.4.1]
 - 电脑操作系统： [e.g. macOS Mojav 10.14.6]

**运行环境信息**
 - 端版本： [ 微信小程序]
 - 手机机型: [开发工具预览]

**Comment by beatles-chameleon** [comment]
cell标签暂时没有默认的display:flex属性，这个问题可自己添加该属性解决
