### ISSUE TITLE
scroller如何用滚动到底部？

### ISSUE THREAD

**Issue by chenzefeng09** [didi/chameleon#309]
如题，翻了文档没有看到。

**Comment by beatles-chameleon** [comment]
设置scrollTop：https://cmljs.org/doc/component/base/layout/scroller.html

**Comment by chenzefeng09** [comment]
设置scrollTop=-1吗？  @beatles-chameleon

**Comment by beatles-chameleon** [comment]
设置scrollTop=极大值就可以滚到底部
