### ISSUE TITLE
官网文档错误

### ISSUE THREAD

**Issue by Tianfer** [didi/chameleon#311]
**bug描述**
文档错误

**复现bug的步骤**
1. https://cml.js.org/doc/framework/router.html#%E8%B7%AF%E7%94%B1%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6
2. 写domian的那行

**问题截图**
![image](https://user-images.githubusercontent.com/19382889/66990025-00f32080-f0f8-11e9-8958-f7ba40b7caf7.png)

**Comment by beatles-chameleon** [comment]
好的~谢谢指正

**Comment by liuwuhaoo** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api/wxml/wx.createSelectorQuery.html

**Comment by beatles-chameleon** [comment]
getRect内部多态实现抹平了各端差异
