### ISSUE TITLE
input 设置动画改变宽度

### ISSUE THREAD

**Issue by akbq2008** [didi/chameleon#312]
**bug描述**
小程序编译出来的input宽度没有变化

**复现bug的步骤**
``` js
 <input type="text" placeholder="搜索" placer-holder-color="#bebebe" 
      return-key-type="search" cstyle="outline:none;background-color:rgb(244,244,244);border:none;height:60cpx;font-size:28cpx;padding-left:40cpx;border-radius:16cpx;width:140cpx" @focus="handleFocus" ref="searchInput" @blur="handleBlur" :animation="animationData"></input>
```
```
handleFocus(){
      let anima=cml.createAnimation();
     this.animationData=anima.width(400).step().export();
      console.log(this.animationData)
    },
    handleBlur(){
      let anima=cml.createAnimation();
     this.animationData=anima.width(140).step().export();
    }
```

**问题截图**
![image](https://user-images.githubusercontent.com/20917699/67070258-27759200-f1b2-11e9-964e-6d89298c38f0.png)

**编译环境信息**
 - chameleon-api: "1.0.0",
 - chameleon-runtime: "1.0.0",
 - chameleon-store: "1.0.0",
 - chameleon-ui-builtin: "1.0.0",
 - cml-ui: "1.0.0"
 - nodejs版本、npm版本：node v10.16.3、npm 6.12.0
 - 电脑操作系统：windows10

**运行环境信息**
 - 端版本： 微信开发者工具 1.02.190730

**Comment by akbq2008** [comment]
chameleon-ui-builtin:1.0.3也不行

**Comment by akbq2008** [comment]
有支持的计划吗？

**Comment by zyt0103** [comment]
建议传入属性cStyle进行设置
