### ISSUE TITLE
c-radio-group组件bug

### ISSUE THREAD

**Issue by wuazhu** [didi/chameleon#313]
**bug描述**
代码如下, 绑定 goupchange 事件的时候打印出 ev, 里面的 detail.value. 也就是绑定的 radioGroup 变成了具有1000长度的数组, 其中第一第二项为 radioGroup 原数组内容项, 其余都为 undefined
```
<c-radio-group
   horizontal="{{true}}"
   option="{{ radioGroup }}"
   color="#00B366"
   c-bind:groupchange="valueChange">
</c-radio-group>
data = {
radioGroup: [
      {
        label: 'op1',
        key: 'opone',
        id: 1,
        checked: false
      },
      {
        label: 'op2',
        key: 'optwo',
        id: 2,
        checked: false
      }
    ]
}
```
![image](https://user-images.githubusercontent.com/15375121/67193693-4aa97700-f428-11e9-8c2b-49a089ad7eed.png)
![image](https://user-images.githubusercontent.com/15375121/67193997-da4f2580-f428-11e9-97de-00b2e90b6144.png)

**Comment by beatles-chameleon** [comment]
这是在小程序实现数组数据响应的方案，将原数组类型转变成类数组，依然具备数组的pop、push、shift、unshift、slice、splice、concat、reverse、join的原生方法，可通过arr.forEach进行遍历，不会循环undefined的元素
