### ISSUE TITLE
mac系统下 安装chameleon-tool后，执行cml -v报错cml不存在

### ISSUE THREAD

**Issue by luowen1991** [didi/chameleon#317]
**bug描述**
mac系统下 安装chameleon-tool后，执行cml -v报错cml不存在

**复现bug的步骤**
1. npm i -g chameleon-tool
2. 执行cml -v
3. 报错 zsh: command not found: cml 

**问题截图**
![image](https://user-images.githubusercontent.com/15939099/67450832-3ac0ab80-f651-11e9-9e5a-275a725c6145.png)

**编译环境信息**
 - chameleon-tool 版本：[1.0.3]
 - nodejs版本、npm版本：[node v10.17.0、npm 6.11.3]
 - 电脑操作系统： [macOS  10.14.6]

**Comment by jimwmg** [comment]
你好，你在哪个终端安装的  chameleon-tool ，在哪个终端执行的 cml 命令？

**Comment by luowen1991** [comment]
> 你好，你在哪个终端安装的 chameleon-tool ，在哪个终端执行的 cml 命令？

系统自带的终端 只不过装了item2 都是在mac上执行的

**Comment by beatles-chameleon** [comment]
请贴一下执行 npm i -g chameleon-tool 时的打印信息

**Comment by luowen1991** [comment]
> 请贴一下执行 npm i -g chameleon-tool 时的打印信息

解决了，是我node版本太高了 我用node v9.11版本就没问题了
