### ISSUE TITLE
如何在cml中使用兼容库socket.io-mp-client而不报错

### ISSUE THREAD

**Issue by fznply** [didi/chameleon#324]
```javascript
<script cml-type="web"> 
import io from 'socket.io-client'; 
class Method implements SocketIoInterface { 
  createSocketIoCtl(host) {
    let socket = io.connect(host); 
    return socket; 
  } 
} 
export default new Method(); 
</script> 
<script cml-type="wx"> 
import io from 'socket.io-mp-client'; 
class Method implements SocketIoInterface { 
   createSocketIoCtl(host) {
       let socket = io.connect(host);
       return socket; 
   } 
} 
export default new Method(); 
</script>
```

如下错误会被检查出来：
  不能在wx 项目中使用全局变量【my】
  不能在wx 项目中使用全局变量【chrome】
  等等。
实际上[socket.io-mp-client](https://github.com/cytle/socket.io-mp-client)已经做过兼容性处理了

**Comment by startheart** [comment]
如果确认socket.io-mp-client作了兼容，可以添加全局变量校验白名单：https://cml.didi.cn/doc/framework/config.html

**Comment by fznply** [comment]
如果开启了全局变量校验的白名单，是否其他自定义component或者page也同样不会有此检查了；或者说我只想要在某个引入库忽略某类变量的校验。

**Comment by startheart** [comment]
针对库不校验
![image](https://user-images.githubusercontent.com/10693888/68377608-ab091a00-0185-11ea-948f-6139262130a0.png)

**Comment by fznply** [comment]
多谢 @startheart 给出解决方案。
