### ISSUE TITLE
scroller 中的input组件无法在编辑的时候直接点击别的input切换焦点  

### ISSUE THREAD

**Issue by qinle123** [didi/chameleon#329]
**bug描述**
scroller组件中套两个input  , 点击其中一个进行输入,弹出输入法.  此时点击另一个input,没有反应,焦点不能切换.当input在scroller外面时   就正常使用

**问题截图**
![image](https://user-images.githubusercontent.com/32858228/68525277-f436a680-030a-11ea-8a62-76e8b1fe66f5.png)

**编译环境信息**
 - chameleon-tool 版本：[e.g.1.0.3]
 - nodejs版本、npm版本：[node v10.16.0、npm 6.9.0]
 - 电脑操作系统： [e.g. macOS Mojave 10.14]

**运行环境信息**
 - 端版本： [目前web端  (小程序未检查)]
 - 手机机型: [e.g. iPhone xr 13.1]

**Comment by zyt0103** [comment]
@1.0.5已发布，可试用
