### ISSUE TITLE
采用分包后微信小程序仍超出大小

### ISSUE THREAD

**Issue by Mr-FSM** [didi/chameleon#332]
**bug描述**
采用分包后大小仍是超出，查看具体文件发现外层和static里面有两个componets并且都很大

**复现bug的步骤**
1. cml dev

**问题截图**
![image](https://user-images.githubusercontent.com/25889758/69022730-39d42d00-09f7-11ea-9975-4ff4b5f95120.png)

**编译环境信息**
 - chameleon-tool 版本：[e.g.1.0.3]
 - nodejs版本、npm版本：[node v12.4.0、npm 6.10.1]
 - 电脑操作系统： [e.g. macOS High Sierra 10.13.6]

**运行环境信息**
 - 端版本： [e.g. 微信小程序 7.0.3]

**Comment by jimwmg** [comment]
参考这个优化：https://github.com/beatles-chameleon/cml-subpage
预期主包体积降低 40%！

已有开发者尝试，优化结果如下：

优化前：

![WechatIMG17](https://user-images.githubusercontent.com/21155942/69489082-5ae0c600-0eae-11ea-8488-2a7616588e87.jpeg)

优化后：

![WechatIMG18](https://user-images.githubusercontent.com/21155942/69489085-63d19780-0eae-11ea-9396-d30d98717c44.jpeg)
