### ISSUE TITLE
richtext报错

### ISSUE THREAD

**Issue by AshaLiu** [didi/chameleon#333]
**bug描述**
![image](https://user-images.githubusercontent.com/12619348/69301482-62576380-0c51-11ea-99b1-9b53f480df65.png)
![image](https://user-images.githubusercontent.com/12619348/69301491-697e7180-0c51-11ea-9a78-e11a59ba683d.png)
![image](https://user-images.githubusercontent.com/12619348/69301506-769b6080-0c51-11ea-8bb1-38c92ea4ebb5.png)

**复现bug的步骤**

**问题截图**
文档提供的参数，在built-in里面没有体现，导致报错

**编译环境信息**
 - chameleon-tool 版本：[1.0.3]

**Comment by jimwmg** [comment]
感谢您的反馈，我们尽快修复这个问题。

**Comment by zyt0103** [comment]
1.0.5已修复，支付宝和百度暂不支持click事件
