### ISSUE TITLE
有没有类似uni-app中的uni.$emit或者wx.navigateTo中events页面间通信功能

### ISSUE THREAD

**Issue by zhaixiyun** [didi/chameleon#336]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jimwmg** [comment]
1.可以通过 store 进行数据通信
https://cmljs.org/doc/logic/store.html
2 组件间可以利用 父子组件通信
https://cmljs.org/doc/view/event.html

**Comment by zhaixiyun** [comment]
嗯嗯，看到了，多谢
