### ISSUE TITLE
急，h5页面，先navigateTo到其他页面再点浏览器的返回按钮，节点会少class,以及框架自己添加的height：667px消失

### ISSUE THREAD

**Issue by AshaLiu** [didi/chameleon#338]
**bug描述**
h5页面，先navigateTo到其他页面再点浏览器的返回按钮，节点会少class,以及框架自己添加的height：667px消失

**问题截图**
![image](https://user-images.githubusercontent.com/12619348/69616773-1bfb6d80-1072-11ea-880e-c83a5b63b8da.png)

![image](https://user-images.githubusercontent.com/12619348/69616801-26b60280-1072-11ea-8171-c5af9f9cd52b.png)

**Comment by jimwmg** [comment]
描述详细信息  chameleon-tool 版本  电脑系统等
以及上传一个能复现这种场景的简单demo

**Comment by AshaLiu** [comment]
[testcml.zip](https://github.com/didi/chameleon/files/3891767/testcml.zip)
里面有一个.mov

这个工程就是简单的,cml init project，一步步出来的

然后新增index2页面，路由配置一个index2，在index页面新增点击按钮跳转

**Comment by jimwmg** [comment]
页面的高度需要自定义去撑满
```html
<template>
  <view  style="{{containerStyle}}">
      <view>fdf</view>
  </view>
</template>
```
```javascript
<script>
import cml from 'chameleon-api'
class Index  {
  data = {
    title: "chameleon",
    chameleonSrc: require('../../assets/images/chameleon.png'),
    containerStyle:'',
  }
  
  mounted(){
    cml.getSystemInfo().then(info => {
      let height = info.viewportHeight;
      this.containerStyle = `height:${height}cpx`
    })
  }
}

export default new Index();

</script>
```

**Comment by AshaLiu** [comment]
感谢帮助，页面太多了，直接在入口加这个style，app.cml

`<template>
  <view :style="heightStyle">
    <app router-config="{{routerConfig}}"></app>
  </view>
</template>`

`<script>
import routerConfig from '../router.config.json';
import cml from 'chameleon-api'

class App {
  data = {
    routerConfig,
    heightStyle: 'height:100vh'
  }
  created(res) {
  }
  mounted () {
    cml.getSystemInfo().then(({viewportHeight}) => {
      console.log(2222)
      // this.heightStyle = `height: ${viewportHeight}cpx`
    })
  }
}

export default new App();
</script>`

**Comment by AshaLiu** [comment]
感谢帮助，页面太多了，可以直接在入口加这个style，app.cml

```
<template>
  <view :style="heightStyle">
    <app router-config="{{routerConfig}}"></app>
  </view>
</template>
```

```
<script>
import routerConfig from '../router.config.json';
import cml from 'chameleon-api'

class App {
  data = {
    routerConfig,
    heightStyle: 'height:100vh'
  }
  created(res) {
    cml.setTitle('BMW二手车回家标准服务')
  }
  mounted () {
    cml.getSystemInfo().then(({viewportHeight}) => {
      this.heightStyle = `height: ${viewportHeight}cpx`
    })
  }
</script>
```
