### ISSUE TITLE
支持自定义content-type  multipart/form-data

### ISSUE THREAD

**Issue by AshaLiu** [didi/chameleon#339]
**bug描述**
cml.request的content-type只能支持application/x-www-form-urlencoded和application/json

我涉及到上传文件功能，需要‘multipart/form-data’

**复现bug的步骤**

**问题截图**

![image](https://user-images.githubusercontent.com/12619348/69626452-a6000200-1083-11ea-9661-a6049cd08a6f.png)

希望图中对掉下，能让用户自定义覆盖一下～

**Comment by jimwmg** [comment]
好的，明天我们发一版

**Comment by AshaLiu** [comment]
> 好的，明天我们发一版
我上面的描述有点错误，除了对掉，这边的代码，还对data做了处理，一定要字符串，我这边的需求是上传图片，传的是formData()

**Comment by AdamEleven** [comment]
上传图片有对应的方法, 参考文档
https://cmljs.org/doc/api/chooseImage.html#chooseimage

**Comment by AshaLiu** [comment]
> 上传图片有对应的方法, 参考文档
> https://cmljs.org/doc/api/chooseImage.html#chooseimage

这个只是选择照片，h5拿到的也是base64，阿里云上传图片不支持。不是接口multipart/form-data

**Comment by js5323** [comment]
微信小程序好像不支持FormData，好像也没法用cml.request来上传文件？

**Comment by AshaLiu** [comment]
> 微信小程序好像不支持FormData，好像也没法用cml.request来上传文件？

我这边是编译成h5和支付宝小程序

**Comment by jimwmg** [comment]
参考多态接口进行封装
https://cml.js.org/doc/framework/polymorphism/api.html?h=%E5%A4%9A%E6%80%81%E6%8E%A5%E5%8F%A3

**Comment by jimwmg** [comment]
chameleon-api@1.0.3-alpha.1
