### ISSUE TITLE
c-tab不知道怎么设置icon

### ISSUE THREAD

**Issue by iwz73** [didi/chameleon#34]
想练练手写个微信小程序，直接用小程序的tabBar的icon路径不知道怎么定义，用c-tab也不知道怎么写图片

**Comment by beatles-chameleon** [comment]
如果用小程序的tabBar
1 app.cml的script中require tabBar 需要的图片。
2 在微信小程序产出目录的/static/img 中找到该图片 复制加了hash值的图片名称。
3 在app.cml的json中进行微信小程序 tabbar的设置，指定该图片位置。

**Comment by beatles-chameleon** [comment]
请使用最新可跨所有端的c-tabbar： https://cml.js.org/doc/component/expand/compound/c-tabbar.html
