### ISSUE TITLE
input支付宝小程序端password类型不起作用

### ISSUE THREAD

**Issue by youlingred** [didi/chameleon#345]
**input组件password类型无效**
在小程序端使用input组件设置type=“password”不起作用

**问题截图**

**编译环境信息**
 - chameleon-tool 版本：[e.g.0.1.0]
 - nodejs版本、npm版本：[node v8.11.4、npm 5.6.0]
 - 电脑操作系统： [e.g. macOS High Sierra 10.13.6]

**运行环境信息**
 - 端版本： [e.g. 微信小程序 7.0.3、weex 2.0、手机Safari浏览器 、PC Chrome浏览器 1.30]
 - 手机机型: [e.g. iPhone6 12.0]

**Comment by jimwmg** [comment]
下个版本更新修复此问题

**Comment by zyt0103** [comment]
1.0.5已修复，可试用
