### ISSUE TITLE
http 加密后的 formData 无法设置上去，原生的没问题

### ISSUE THREAD

**Issue by huchangfa123** [didi/chameleon#347]
**bug描述**
http 加密后的 formData 会被置成空对象，原生的没问题

**复现bug的步骤**
发送一个加密后的 formData 的请求即能复现

**问题截图**
正常微信小程序的 formData
<img width="767" alt="企业微信截图_00d887f0-2afb-4815-8ea3-60107e5e3215" src="https://user-images.githubusercontent.com/20489087/69945752-2d86be80-1525-11ea-8b4f-571ad8921047.png">

用了 chameleon formData 就没了。查了下代码，
![企业微信截图_bc1b9763-93e7-4a37-b886-b39b8c547109](https://user-images.githubusercontent.com/20489087/69946121-f533b000-1525-11ea-94de-3b33966bfafd.png)
![企业微信截图_fee7e12e-670e-415f-836c-80f2d382f575](https://user-images.githubusercontent.com/20489087/69946127-f82ea080-1525-11ea-824a-1139a39cf5d4.png)
发现是这个函数导致的，它没法识别加密后的 string ..直接返回一个空对象了

**编译环境信息**
 - chameleon-tool 版本：
"chameleon-api": "^1.0.1",
    "chameleon-bridge": "^0.2.0",
    "chameleon-runtime": "1.0.0",
    "chameleon-store": "1.0.0",
    "chameleon-ui": "^2.0.0",
    "chameleon-ui-builtin": "^1.0.1",
    "cml-ui": "1.0.0",
 - nodejs版本、npm版本：
    node: 10.16.0 , npm: 6.4.1
 - 电脑操作系统：
    macOS
**运行环境信息**
 - 端版本：微信小程序 2.9.4

**Comment by jimwmg** [comment]
上传一个能复现问题的demo吧，我们调试下

**Comment by gaoxc** [comment]
> **bug描述**
> http 加密后的 formData 会被置成空对象，原生的没问题
> 
> **复现bug的步骤**
> 发送一个加密后的 formData 的请求即能复现
> 
> **问题截图**
> 正常微信小程序的 formData
> <img alt="企业微信截图_00d887f0-2afb-4815-8ea3-60107e5e3215" width="767" src="https://user-images.githubusercontent.com/20489087/69945752-2d86be80-1525-11ea-8b4f-571ad8921047.png">
> 
> 用了 chameleon formData 就没了。查了下代码，
> ![企业微信截图_bc1b9763-93e7-4a37-b886-b39b8c547109](https://user-images.githubusercontent.com/20489087/69946121-f533b000-1525-11ea-94de-3b33966bfafd.png)
> ![企业微信截图_fee7e12e-670e-415f-836c-80f2d382f575](https://user-images.githubusercontent.com/20489087/69946127-f82ea080-1525-11ea-824a-1139a39cf5d4.png)
> 发现是这个函数导致的，它没法识别加密后的 string ..直接返回一个空对象了
> 
> **编译环境信息**
> 
> * chameleon-tool 版本：
>   "chameleon-api": "^1.0.1",
>   "chameleon-bridge": "^0.2.0",
>   "chameleon-runtime": "1.0.0",
>   "chameleon-store": "1.0.0",
>   "chameleon-ui": "^2.0.0",
>   "chameleon-ui-builtin": "^1.0.1",
>   "cml-ui": "1.0.0",
> * nodejs版本、npm版本：
>   node: 10.16.0 , npm: 6.4.1
> * 电脑操作系统：
>   macOS
>   **运行环境信息**
> * 端版本：微信小程序 2.9.4

你是将整个data的值做的加密吗？

**Comment by gaoxc** [comment]
已发版解决1.0.3-alpha.2
