### ISSUE TITLE
build打包后样式文件中引入的图片地址加载错误

### ISSUE THREAD

**Issue by xiaobeiHan** [didi/chameleon#349]
**bug描述**
样式文件中背景图片是： '../images/myImages/arrow.png';
打包出来之后，图片被打到了 'dist/web/static/img'里面;
但是 打开页面，图片的引用地址是： 'dist/web/static/css/static/img/arrow.png'
publicPath为'./'  当前目录

**Comment by jimwmg** [comment]
请上传详细demo,方便我们排查问题，谢谢
