### ISSUE TITLE
滴滴内部有用在生产环境的案例吗？

### ISSUE THREAD

**Issue by Maslow** [didi/chameleon#35]
我看有人问过这个问题，并没有回答，直接关闭了。 
有就有，没有就没有。

目前只有那人严选的 Demo。 

目前建议使用在生产环境吗，希望得到官方的态度。

现在可以直接 build 为 ios &  android 安装包吗，像 cordova 那样，文档上没太找到这块。

**Comment by beatles-chameleon** [comment]
一、内部生产环境问题：
a、这里面已经有回复：https://github.com/didi/chameleon/issues/6
b、文章里面有介绍：https://zhuanlan.zhihu.com/p/56102743
二、暂时没有支持build到成安装包，用户需要自己有一定android、ios开发知识才能接入；
iOS：https://cmljs.org/doc/chameleon_client/ios_integration.html
Android：https://cmljs.org/doc/chameleon_client/android_integration.html

**Comment by Maslow** [comment]
thanks.
