### ISSUE TITLE
项目cml-demo执行cml tt dev 后报错process is not defined

### ISSUE THREAD

**Issue by BlueCat918** [didi/chameleon#351]
**bug描述**
官方cml-demo(master)执行cml tt dev后在字节开发工具中报错process is not defined(未做任何修改).请问有大佬遇到过吗

**复现bug的步骤**
1. clone
2. npm i
3. cml tt dev

**问题截图**
![捕获](https://user-images.githubusercontent.com/32082464/70959520-7c9d2980-20b7-11ea-82ac-2d011125b937.PNG)

**编译环境信息**
 - chameleon-tool 版本：1.0.3
 - nodejs版本、npm版本：[node v12.13.1、npm 6.12.1]
 - 电脑操作系统： windows 10 1903 18362.535

**运行环境信息**
 - 端版本： [头条小程序 1.45.0.0]

**Comment by jimwmg** [comment]
感谢反馈，目前定位问题是windows系统不兼容，近期修复此问题

**Comment by jimwmg** [comment]
扩展头条小程序端 package.json中依赖dependencies，其中：
chameleon-store@0.2.0   chameleon-runtime@0.4.0 及以上版本对应 cml-tt-runtime@0.2.4  cml-tt-store@0.2.4 及以上版本;
