### ISSUE TITLE
组件 refresh-view ，退出页面再进入页面后，会导致事件 onPullUpLoad 触发多次

### ISSUE THREAD

**Issue by kennyzuo** [didi/chameleon#352]
**bug描述**
【微信小程序】
  1. A 页面进入 B页面（使用 refresh-view， 监听 onPullUpLoad 事件），返回A，再次进入B， 上拉加载， 会多触发一次  onPullUpLoad 事件
  2. 重复步骤 1 ，重复一次， onPullUpLoad 事件就会累加触发次数

**复现bug的步骤**
参考bug描述

**问题截图**
以下是自己调试时候发现的问题代码
![image](https://user-images.githubusercontent.com/9876388/71048245-a880e380-2179-11ea-92e9-2c416f6a3c43.png)
作如下修改，可以修复bug
![image](https://user-images.githubusercontent.com/9876388/71048258-b0d91e80-2179-11ea-8bda-c3af447e4ca6.png)

**编译环境信息**
 - chameleon-tool 版本：[e.g.0.1.0]
 - nodejs版本、npm版本：[node v8.11.4、npm 5.6.0]
 - 电脑操作系统： [macOS]

**运行环境信息**
 - 端版本： [微信小程序、 微信开发者工具] 

**期望能有官方的解决办法，谢谢！**

**Comment by beatles-chameleon** [comment]
感谢提出问题及解决问题，已发布@1.0.5
