### ISSUE TITLE
input无法应用样式

### ISSUE THREAD

**Issue by Charley-Tang** [didi/chameleon#356]
**bug描述**
使用input组件后，web编译结果是div包裹input，但是在less中对div中的input添加样式，发现无样式

**复现bug的步骤**
```
    <view class="input-wrap">
      <view class="icon"></view>
      <input class="input-box" />
      <view class="clear"></view>
    </view>

      .input-box {
        flex-grow: 1;
        background: red;

        input {
          width: 100%;
          color: green;
        }
      }
```
**问题截图**
![image](https://user-images.githubusercontent.com/25997259/71439598-368a3a80-2735-11ea-9276-5857554c58f7.png)

![image](https://user-images.githubusercontent.com/25997259/71439577-22ded400-2735-11ea-81b2-cc190fcfb622.png)

**编译环境信息**
 - chameleon-tool 版本：1.0.3
 - nodejs版本、npm版本：v12.11.0、 6.11.3
 - 电脑操作系统： macOS High Sierra 10.14.6

**运行环境信息**
 - 端版本： PC Chrome浏览器  78

**Comment by zyt0103** [comment]
1.input 支持传入属性cstyle来控制样式，<input cstyle="width:200cpx;color:green"/>；
2.web端是否包裹可配置，chameleon.config.js文件
web: {
    dev: {
      isWrapComponent: false // 默认对组件进行一层包裹
    }
}
