### ISSUE TITLE
如何统一改变整个项目的字体

### ISSUE THREAD

**Issue by Mr-FSM** [didi/chameleon#361]
由于业务需求，公司要求改变，统一的字体

**Comment by jimwmg** [comment]
我们调研下如何支持全局样式的引入

**Comment by jimwmg** [comment]
chameleon-tool@1.0.5-alpha.1  
  - 支持全局样式，使用参考demo：https://github.com/chameleon-team/cml-global-style
  - 修复config.json缺少qq和扩展新端信息
  - 优化全局配置，支持性能优化配置项
  - 配置不引入基础样式，小程序端不生成对应样式文件
