### ISSUE TITLE
chameleon-runtime@1.0.0 初始化组件时 建议不要强制覆盖 options 选项

### ISSUE THREAD

**Issue by lonelyWalkor** [didi/chameleon#363]
chameleon-runtime@1.0.0 初始化组件时 会直接覆盖掉传入的options对象
建议保留原本的配置项

src\platform\wx\instance\component.js   51行
代码如下----saart
this.options['options'] = {
      multipleSlots: true // 在组件定义时的选项中启用多slot支持
}
runtimeCore.setOptions(this.options)

------end

![20200107150000](https://user-images.githubusercontent.com/20573782/71875166-a4375d00-315e-11ea-81ab-c383f554c13f.png)

**Comment by jimwmg** [comment]
已收到你的建议，近期我们会调研下此功能的实现方式，按期进行开发，有结果会在这里同步。

**Comment by jimwmg** [comment]
试下chameleon-runtime@1.0.1
