### ISSUE TITLE
createInnerAudio应为createInnerAudioContext

### ISSUE THREAD

**Issue by jues** [didi/chameleon#365]
**bug描述**    
文档错误    
https://cmljs.org/doc/api/audio/createInnerAudio.html    
api文档`cml.createInnerAudio()`实际应为`createInnerAudioContext`    
跟api代码里的不一样，要么文档错了要么代码错了

**Comment by jimwmg** [comment]
多谢反馈，我们核验下进行修改，谢谢。

**Comment by jimwmg** [comment]
https://cml.js.org/doc/api/audio/createInnerAudio.html
谢谢反馈，已修复，周知
