### ISSUE TITLE
1.0.4版动态组件自定义属性在编译时报错，但实际可以使用

### ISSUE THREAD

**Issue by jues** [didi/chameleon#366]
**bug描述**
https://github.com/didi/chameleon/issues/330#issuecomment-552299265    
例子见Jim之前给的，新建项目编译一下会报    
```
[INFO] Syntax check results:
[file]: src/pages/index/index.cml
template errors:
[4 (line), 48 (column)] component "component" doesn't have a defined property named "name"
[4 (line), 64 (column)] component "component" doesn't have a defined property named "age"
```    
但实际例子里的文字显示出来了

**编译环境信息**
 - chameleon-tool 版本：1.0.4

**Comment by jimwmg** [comment]
收到你的反馈，近期我们会解决这个校验问题。

**Comment by jimwmg** [comment]
chameleon-tool@1.0.5-alpha.1  
  - 支持全局样式，使用参考demo：https://github.com/chameleon-team/cml-global-style
  - 修复config.json缺少qq和扩展新端信息
  - 优化全局配置，支持性能优化配置项
  - 配置不引入基础样式，小程序端不生成对应样式文件
  - 修复模板校验中的stylus component等问题
