### ISSUE TITLE
抖音小程序关于appid的工程化配置问题

### ISSUE THREAD

**Issue by renyuzhe** [didi/chameleon#367]
发现问题：在chameleon.config.js配置中，没有找到针对抖音小程序appid等信息的配置项
建议：希望可以提供对应配置项，工程化配置appid等信息

**Comment by jimwmg** [comment]
感谢对该问题的反馈，本周会修复

**Comment by jimwmg** [comment]
cml-tt-api@0.2.5 已修复该问题
