### ISSUE TITLE
能否支持必要配置外置，比如地址，否则的话打包文件无法作为部署文件分发，需要重新编译

### ISSUE THREAD

**Issue by youlingred** [didi/chameleon#369]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by youlingred** [comment]
场景描述：
支付宝小程序和h5打包后输出`alipay`和`h5`的打包文件，但是静态资源以及接口地址必须在``配置好，然后打包输出。
![image](https://user-images.githubusercontent.com/177204/74897866-48a1f580-53d3-11ea-88ef-a2709ba11bcb.png)
提供给部署人员，如果部署人员在其他环境上部署，地址不是已经配置好的地址，那么就需要重新打包，输入`alipay`和`h5`文件，无法通过读取外置配置文件方式设置资源请求地和接口请求地址，能不能将这中依赖配置不放在编译期二放在运行期，可以支持写在逻辑代码里或者通过读取外部json文件的方式

**Comment by jimwmg** [comment]
谢谢反馈，我们近期调研下如何实现

**Comment by jimwmg** [comment]
另，附上一个如何调试chameleon工程化配置的步骤
如何调试chameleon的工程化配置

第一步：

`cml -v` 找到当前使用chameleon-tool的路径

第二步：

用编辑器打开该路径下源码，找到`chameleon.js` 文件,修改成如下

```javascript

#! /usr/bin/env node --inspect-brk
require('./lib/index.js');

```
可以在源码目录中任何想调试的地方打上断点`debugger`

第三步：

修改`chameleon.config.js`

```javascript
cml.utils.plugin('webpackConfig', function(params) {
  let { type, media, webpackConfig } = params
  /*最终断点会进到这里，在这里可以看.
  type:编译端，web,wx,weex等
  media:编译类型 dev build
  webpackConfig:chameleon内置工程化配置
  */
  debugger;
  return { type, media, webpackConfig }
})
```

第四步：

执行相关的运行命令之后，比如 `cml web dev`
打开`chrome://inspect`

进入调试终端即可
