### ISSUE TITLE
文件名不能以x开头

### ISSUE THREAD

**Issue by feng138168** [didi/chameleon#37]
**bug描述**
init项目时，文件名不能以x开头，否则会报错

**复现bug的步骤**

**问题截图**
![tim 20190212133632](https://user-images.githubusercontent.com/18364051/52614039-4c02c700-2ecb-11e9-84df-6139a4502fef.png)

**Comment by beatles-chameleon** [comment]
这个bug在 0.1.0-alpha.2中已经修复  https://github.com/didi/chameleon/commit/f1b236dfe602daf9dd476b9c6e33e980e3640dbc
通过测试期后会发布正式版本
