### ISSUE TITLE
如何将cml weex build输出的文件放到weex里打包成apk

### ISSUE THREAD

**Issue by youlingred** [didi/chameleon#371]
**cml weex build 输出了 js文件和static静态文件夹**
<img width="316" alt="image" src="https://user-images.githubusercontent.com/177204/75122627-9d4ab680-56da-11ea-98b5-f6a584e1ea70.png">
**不知道如何将文件放到weex工程下打包成apk**
**weex工程目录如下**
<img width="371" alt="image" src="https://user-images.githubusercontent.com/177204/75122664-03373e00-56db-11ea-92ec-6d7737401e9c.png">
**weex-cli版本2.0.0-beta.31**
<img width="328" alt="image" src="https://user-images.githubusercontent.com/177204/75122711-63c67b00-56db-11ea-849b-3cc3af3b2ad9.png">

**Comment by sxychenjing** [comment]
测试的话可以把jsbundle放到android工程app模块的assets目录下，clone并参考：
https://github.com/chameleon-team/chameleon-sdk-android
这里有demo工程示例的jsbundle，直接读取assets目录下并渲染
https://github.com/chameleon-team/chameleon-sdk-android/tree/master/app/src/main/assets

另，这里的android相关文章建议先读一遍。
https://cmljs.org/doc/chameleon_client/android/introduction.html
