### ISSUE TITLE
scroller 可以增加一个属性控制取消scrollTop的动画吗

### ISSUE THREAD

**Issue by jues** [didi/chameleon#374]
日历、聊天等scroller都是从上到下依次从旧到新，需要频繁进入时，动画显得不简洁

**Comment by jimwmg** [comment]
好的，我们看下

**Comment by zyt0103** [comment]
scroller scrollTop 动画使用 easing 缓动函数，暂时不支持属性控制修改，一般不建议修改，如果想修改，参考源码https://github.com/chameleon-team/chameleon-scroll/blob/master/src/util/ease.js
