### ISSUE TITLE
input 双向数据绑定失效

### ISSUE THREAD

**Issue by FrancisLL** [didi/chameleon#38]
**bug描述**
描述出现的问题
`c-model="{{ appkey }}" ` appkey两边加上空格，双向绑定数据失效
**复现bug的步骤**
```
       <input type="text" c-model="{{ appkey }}" ></input>
       <text>{{ appkey }}</text>
```

**问题截图**

**编译环境信息**
 - chameleon-tool 版本：chameleon-tool@0.0.13
 - nodejs版本、npm版本：node v10.15.0、npm 6.4.1
 - 电脑操作系统：macOS Mojave 版本：10.14.2(18C54)
**运行环境信息**
 - 端版本： Chrome浏览器 版本 71.0.3578.98（正式版本） （64 位）
 - 手机机型: iPhone6

**Comment by beatles-chameleon** [comment]
https://github.com/didi/chameleon/commit/ec807a0082905dda91dd1c91a9abf5635e249734
已修复，请下载最新 0.0.15 版本
