### ISSUE TITLE
用chameleon如何自定义导航栏

### ISSUE THREAD

**Issue by hyf760451025** [didi/chameleon#382]
为什么app.cml wx   window配置这个就报错    "navigationStyle": 'custom'

**Comment by beatles-chameleon** [comment]
可以麻烦你贴上
- chameleon-tool版本
-代码
-报错信息
详细点的内容吗

**Comment by SuperTaric** [comment]
> 为什么app.cml wx window配置这个就报错 "navigationStyle": 'custom'

你把custom的单引号改成双引号试试
