### ISSUE TITLE
createInnerAudioContext在web环境播放报错

### ISSUE THREAD

**Issue by jues** [didi/chameleon#383]
**bug描述**
点播放报`Uncaught (in promise) TypeError: Cannot read property 'pause' of undefined`
查看代码发现createInnerAudioContext/index.interface 第44行
```
    audioContext.stop = function(){
      this.audioContext.pause();
      this.seek(0);
      events.emit('onStop');
    }
```
这个this.audioContext应为undefined，应该改成`this.pause();`

chameleon-api 1.0.3-alpha.1

**Comment by beatles-chameleon** [comment]
谢谢反馈，很不错，不仅能发现问题，还能排查到问题并给出解决方案，给你点赞

**Comment by gaoxc** [comment]
已发版解决1.0.3-alpha.2

**Comment by gaoxc** [comment]
Fixed
