### ISSUE TITLE
mac执行sudo npm i -g chameleon-tool失败

### ISSUE THREAD

**Issue by ttoling** [didi/chameleon#384]
mac执行sudo npm i -g chameleon-tool失败；
报错信息：
n-tool/node_modules/uglifyjs-webpack-plugin > node lib/post_install.js  
sh: node: command not found 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/chameleon-tool/node_modules/fsevents): 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install` 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT  
npm ERR! code ELIFECYCLE npm ERR! syscall spawn 
npm ERR! file sh npm ERR! errno ENOENT 
npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js` 
npm ERR! spawn ENOENT 
npm ERR!  
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script. 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.  
npm ERR! A complete log of this run can be found in: 
npm ERR!     /Users/admin/.npm/_logs/2020-03-13T02_00_27_777Z-debug.log

![image](https://user-images.githubusercontent.com/51197295/76583120-500c7880-6513-11ea-8028-6acd4927aec1.png)

**编译环境信息**
node版本：12.16.1
npm版本： 6.13.4
Mac版本：macOs catalina 10.15.1

**Comment by beatles-chameleon** [comment]
npm i chameleon-tool -g   试一下，没复现你的问题

<img width="576" alt="屏幕快照 2020-03-14 下午3 09 07" src="https://user-images.githubusercontent.com/44267840/76677147-f3d65100-6605-11ea-84a3-a25b3f4352ab.png">
