### ISSUE TITLE
导航API navigateTo  中文传递乱码

### ISSUE THREAD

**Issue by dL-hx** [didi/chameleon#387]
**bug描述**
描述出现的问题
使用导航API `navigateTo` 传递页面参数, 中文乱码
**复现bug的步骤**
1. 定义navigateTo 方法
``` js
        cml.navigateTo({
          path,
          query:{ title: '张三' }
        })
```

2. beforeCreate 接收参数
 ``` js
  beforeCreate(query) {
    console.log(' query.title ',  query.title )
    this.title = query.title || ''
  }
```

**问题截图**

![111](https://user-images.githubusercontent.com/39437437/77028480-d7566200-69d3-11ea-9d69-bfdf9a13f38c.png)

**编译环境信息**
 - chameleon-tool 版本：1.0.0
 - nodejs版本、npm版本：[node v8.11.4]
 - 电脑操作系统： Win10

**运行环境信息**
 - 端版本： [微信小程序 7.0.3]

**Comment by gaoxc** [comment]
好的   预计下版本1.0.5修复    目前可以先decode下

**Comment by gaoxc** [comment]
预计下周发布

**Comment by dL-hx** [comment]
发布了吗,  1.0.5修复

**Comment by gaoxc** [comment]
本周发布，发布后同步给你




| |
高星晨
|
|
邮箱：gxczkx@163.com
|

签名由 网易邮箱大师 定制

在2020年04月22日 15:33，dL-hx 写道：

发布了吗, 1.0.5修复

**Comment by gaoxc** [comment]
已发布

**Comment by gaoxc** [comment]
1.0.5  已发布  修复navigateTo和redirectTo在小程序端中文参数乱码问题
