### ISSUE TITLE
CLI Language Options

### ISSUE THREAD

**Issue by idkjs** [didi/chameleon#39]
cli是英语，法语还是西班牙语？ 任何人都会这样做 谢谢。

Is the cli English, Spanish or French? Any would do. Thank you.

**Comment by beatles-chameleon** [comment]
Please describe your problem in detail.

**Comment by idkjs** [comment]
When I run commands in the cli, they are in a language I do not understand. The seem to be chinese characters. Is there a way to configure that language?

**Comment by beatles-chameleon** [comment]
Thanks for your advice, that we will support in the next version.
