### ISSUE TITLE
如何通过多态组件协议 , 使用各端的自带的组件

### ISSUE THREAD

**Issue by dL-hx** [didi/chameleon#395]
例如:  使用wx 小程序原生的 rich-text 组件, 而不是cml 框架的 rich-text

因为cml 官方组件不满足具体业务

**Comment by kingsleydon** [comment]
![image](https://user-images.githubusercontent.com/10992364/78237588-1aedb780-750e-11ea-83f5-a8e57490bd0e.png)

https://cml.js.org/docs/build.html#%E6%A8%A1%E6%9D%BF%E5%86%85-tags-%E6%A0%A1%E9%AA%8C

**Comment by dL-hx** [comment]
想问下有实例代码吗? 关于原生wx 小程序组件使用的, 感谢

**Comment by dL-hx** [comment]
`    <origin-rich-text nodes="{{ nodes }}"></origin-rich-text>`

使用多态组件包裹原生标签,  即可使用原生组件 , 通过**父子组件**方式传值,  

参考文章:
https://cml.js.org/doc/example/poly.html
