### ISSUE TITLE
cml版本升级后，出现Cannot read property '__methodCaller' of undefined异常

### ISSUE THREAD

**Issue by htgy12** [didi/chameleon#399]
**bug描述**
升级cml版本之后，同样的代码在新版本报错，错误内容是 `Cannot read property '__methodCaller' of undefined`
cml跨大版本升级，原先版本为0.4升级为1.0
由
```
    "chameleon-api": "0.4.10",
    "chameleon-bridge": "0.1.5",
    "chameleon-runtime": "0.1.5",
    "chameleon-store": "0.0.3",
    "chameleon-ui-builtin": "0.2.9",
    "cml-ui": "0.1.8"
```
升级为
```
    "chameleon-api": "1.0.3",
    "chameleon-runtime": "1.0.1",
    "chameleon-store": "1.0.1",
    "chameleon-ui-builtin": "1.0.6",
    "cml-ui": "1.0.3"
```

**另外，我使用[picker示例文档](https://cml.js.org/components/c-picker.html)，在小程序sdkversion1.9.91下也同样报错**

**复现bug的步骤**
1. 使用官方picker示例，https://cml.js.org/components/c-picker.html
2. 任意选择一个省份
3. 点击确定按钮
4. 控制台出错

**问题截图**
![image](https://user-images.githubusercontent.com/24886532/78500245-e4bb6c80-7787-11ea-8daf-f027a212a209.png)

**编译环境信息**
 - chameleon-tool 版本：[1.0.5]
 - nodejs版本、npm版本：[node v10.15.3、npm 6.4.1]
 - 电脑操作系统： [win10]

**运行环境信息**
 - 端版本： [微信小程序开发者工具 SDKVersion 1.9.91]

**Comment by htgy12** [comment]
发现使用`Promise.resolve().then(() => this.pickerShow= false)`可以临时避免

**Comment by jimwmg** [comment]
将chameleon-api 的版本回退，npm i chameleon-api@1.0.3-alpha.1 -S

如果还有问题麻烦你提供一个最简单能复现此问题的demo，我们定位下问题

**Comment by htgy12** [comment]
https://github.com/htgy12/cml-demo

**Comment by jimwmg** [comment]
<img width="220" alt="屏幕快照 2020-04-21 下午7 18 59" src="https://user-images.githubusercontent.com/21155942/79860307-00b84280-8405-11ea-9241-4a2378ad3dca.png">
升级下微信开发者工具里的sdk版本
微信开发者工具==> 详情 ==> 本地设置 ==> 调试基础库

**Comment by htgy12** [comment]
等了这么多天就这回复？
我也知道升级就行，但是线上小程序的最低版本是1.9.91。
那就是指不兼容老的基础库了？

**Comment by htgy12** [comment]
总该给个支持的微信基础库最低版本吧？

**Comment by jimwmg** [comment]
chameleon-tool生效和不生效的版本号发下

**Comment by jimwmg** [comment]
> 总该给个支持的微信基础库最低版本吧？
升级的时候这两个仓库对应版本如下
"chameleon-runtime": "^0.1.5",
"chameleon-store": "^0.1.0",

**Comment by htgy12** [comment]
关了吧，已经打算换框架了。
用了一年多cml，不再打算继续使用了
