### ISSUE TITLE
chameleon-api 1.0.3 版本web端编译错误，不存在@didi/chameleon-bridge包

### ISSUE THREAD

**Issue by htgy12** [didi/chameleon#402]
**bug描述**
chameleon-api 1.0.3 版本web端编译错误，不存在`@didi/chameleon-bridge`包

**复现bug的步骤**

**问题截图**
1.0.1版本如下
![image](https://user-images.githubusercontent.com/24886532/78789430-b8019200-79df-11ea-8464-f8aa721c3df8.png)
1.0.3版本如下
![image](https://user-images.githubusercontent.com/24886532/78789485-c5b71780-79df-11ea-8149-bad6a739ed3b.png)

**编译环境信息**
 - chameleon-api 版本：[1.0.3]

**运行环境信息**
 - chameleon-api 版本：[1.0.3]

**Comment by gaoxc** [comment]
感谢反馈，您的问题已修复，请更新到1.0.4版本，thx
