### ISSUE TITLE
多态api如何设置object参数

### ISSUE THREAD

**Issue by wanzijinx** [didi/chameleon#405]
错误信息: 不能直接定义类型Object，需要使用符合类型定义，请确认是否开启了可以直接定义 Object 类型参数；

**Comment by dL-hx** [comment]
![image](https://user-images.githubusercontent.com/39437437/79175512-813cd900-7e30-11ea-8cfc-920bcd294dc0.png)

怎么在接口多态中定义一个含可选属性的对象?
https://github.com/didi/chameleon/issues/327

**Comment by jimwmg** [comment]
> ![image](https://user-images.githubusercontent.com/39437437/79175512-813cd900-7e30-11ea-8cfc-920bcd294dc0.png)
> 
> 怎么在接口多态中定义一个含可选属性的对象?
> #327

赞啊  厉害厉害
