### ISSUE TITLE
小程序@import不带wxss后缀问题

### ISSUE THREAD

**Issue by zhanzeliang** [didi/chameleon#406]
**bug描述**
小程序的样式文件wxss，可以使用@import以入其他样式文件，引入时可以省略.wxss后缀。 此时，运行cml dev运行程序时，会报not found xx.less， 即小程序不加wxss后缀时，项目默认后缀是less文件。由于@import是使用在第三方组件库上的，请问，如何在不改动原第三方组件库的情况，让样式正常文件被引用？

**复现bug的步骤**
1. 在小程序的wxss文件使用@import引用其他wxss文件，@import不加wxss后缀。

**问题截图**
小程序第三方库
![image](https://user-images.githubusercontent.com/28891034/79176583-2fe21900-7e33-11ea-8a4b-6c754cc9e90b.png)
cml  dev报错
![image](https://user-images.githubusercontent.com/28891034/79176604-42f4e900-7e33-11ea-86ba-d2b5e86279e4.png)

**编译环境信息**
 - chameleon-tool 版本：1.0.5
 - nodejs版本、npm版本：[node v12.16.1、npm 6.13.2]
 - 电脑操作系统： windows10

**运行环境信息**
 - 端版本： 微信小程序 7.0.3

**Comment by jimwmg** [comment]
方便提供一个demo吗？

**Comment by zhanzeliang** [comment]
这是例子https://github.com/zhanzeliang/chameloemDemo。 因为公司业务的关系，不便公开第三方组件。我的demo使用了iview webapp可以模拟上面的问题。

**Comment by jimwmg** [comment]
好的  我看下问题

**Comment by jimwmg** [comment]
感谢你的反馈，npm i  chameleon-tool@1.0.6-alpha.1 -g 已解决此问题

**Comment by zhanzeliang** [comment]
谢谢！ 经验证，已解决！
