### ISSUE TITLE
快应用与微信小程序如何才能配置兼容

### ISSUE THREAD

**Issue by saubcy** [didi/chameleon#416]
**bug描述**
根据官方文档集成快应用支持后，在微信中启动报错如下：
`Mon May 11 2020 09:40:42 GMT+0800 (中国标准时间)  sitemap.json 文件内容错误
VM92:1 sitemap.json
Error: 未找到入口 sitemap.json 文件，或者文件读取失败，请检查后重新编译。
console.error @ VM92:1
(anonymous) @ VM116:2
VM92:1 jsEnginScriptError
Component is not found in path "npm/cml-quickapp-ui-builtin/node_modules/chameleon-ui-builtin/components/page/page" (using by "pages/index/index");onAppRoute
Error: Component is not found in path "npm/cml-quickapp-ui-builtin/node_modules/chameleon-ui-builtin/components/page/page" (using by "pages/index/index")
    at q (http://127.0.0.1:53025/appservice/__dev__/WAService.js:2:1631416)
    at q (http://127.0.0.1:53025/appservice/__dev__/WAService.js:2:1631620)
    at http://127.0.0.1:53025/appservice/__dev__/WAService.js:2:1653569
    at Module.He (http://127.0.0.1:53025/appservice/__dev__/WAService.js:2:1654148)
    at Function.value (http://127.0.0.1:53025/appservice/__dev__/WAService.js:2:1744838)
    at xt (http://127.0.0.1:53025/appservice/__dev__/WAService.js:2:1761097)
    at http://127.0.0.1:53025/appservice/__dev__/WAService.js:2:1765354
    at Mt (http://127.0.0.1:53025/appservice/__dev__/WAService.js:2:1765847)
    at Function.<anonymous> (http://127.0.0.1:53025/appservice/__dev__/WAService.js:2:1773952)
    at i.<anonymous> (http://127.0.0.1:53025/appservice/__dev__/WAService.js:2:1737576)
console.error @ VM92:1
errorReport @ VM98 WAService.js:2
(anonymous) @ VM98 WAService.js:2
x @ VM98 WAService.js:2
(anonymous) @ VM98 WAService.js:2
i.emit @ VM98 WAService.js:2
emit @ VM98 WAService.js:2
(anonymous) @ VM98 WAService.js:2
(anonymous) @ VM98 WAService.js:2
n @ VM96 asdebug.js:1
(anonymous) @ VM96 asdebug.js:1
(anonymous) @ VM96 asdebug.js:1
_ws.onmessage @ VM96 asdebug.js:1`

**复现bug的步骤**
1. cml init project 新建工程
2. 根据[官方快应用集成指南](https://cmljs.org/tutorial/quickapp-cml-app.html#%E6%8E%A5%E5%85%A5%E5%BF%AB%E5%BA%94%E7%94%A8)改造工程
3. cml dev 编译启动工程
4. 微信开发者工具打开dist/wx目录

**编译环境信息**
 - chameleon-tool 版本：chameleon-tool@1.0.5
 - nodejs版本、npm版本：node v12.5.0、npm 6.9.0
 - 电脑操作系统： [e.g. macOS 10.15.4]

**运行环境信息**
 - 端版本： 微信开发者工具 1.02.2004020

**Comment by jimwmg** [comment]
https://github.com/chameleon-team/cml-flexbox/tree/master-quickapp
试下这个demo

**Comment by saubcy** [comment]
> https://github.com/chameleon-team/cml-flexbox/tree/master-quickapp
> 试下这个demo

emmm，尝试了一下子，切换到master-quickapp后
npm install
cml wx dev
然后微信开发者工具导入也是报了一样的错这样

**Comment by saubcy** [comment]
其实主要是想确认下，是框架本身目前确实还不支持一套代码同时编译到微信小程序跟快应用，还是说这里的配置有什么地方不对？
因为目前项目上确实是有这样的需求，假设说是前者的话，我这边就先去想想别的办法了，多谢🙏

**Comment by beatles-chameleon** [comment]
还是这个分支，再试下：https://github.com/chameleon-team/cml-flexbox/tree/master-quickapp
由于快应用相关的包依赖没有升级，我们已经联系快应用团队进行升级

**Comment by saubcy** [comment]
> 还是这个分支，再试下：https://github.com/chameleon-team/cml-flexbox/tree/master-quickapp
> 由于快应用相关的包依赖没有升级，我们已经联系快应用团队进行升级

好的，那就等升级不自己折腾了😄

**Comment by whuhenrylee** [comment]
@saubcy 1.0.1版本已修复包依赖问题
