### ISSUE TITLE
usingComponents引入组件在小程序端报错找不到组件

### ISSUE THREAD

**Issue by wanzijinx** [didi/chameleon#426]
**bug描述**
usingComponents用相对路径引用组件，在web端可以正常使用，在小程序端报错

**问题截图**
项目文件结构：

![image](https://user-images.githubusercontent.com/28819509/82623393-a6ccb780-9c12-11ea-874d-c37c933707ed.png)
![image](https://user-images.githubusercontent.com/28819509/82623513-ed221680-9c12-11ea-93bc-403cb9f0989f.png)

**编译环境信息**
 - chameleon-tool 版本：1.0.4
 - nodejs版本、npm版本：node v12.10.0、npm 6.10.3
 - 电脑操作系统： win10

**Comment by beatles-chameleon** [comment]
../order/list/index

**Comment by wanzijinx** [comment]
> 相对路径这么写
> 
> ```json
> "order":"../order/list/index"
> ```
> 
> 如果小程序端找不到组件，有没有看编译后的 pages/index/index.json 的路径为什么找不到组件，定位下问题

这样写在小程序也是一样的报错，我已经在小程序试过各种组合了
![image](https://user-images.githubusercontent.com/28819509/82646053-76067580-9c46-11ea-9620-5c9b4b7db714.png)

**Comment by beatles-chameleon** [comment]
初始化一个项目能运行吗

**Comment by wanzijinx** [comment]
> 初始化一个项目能运行吗

问题解决了，tabbar不能引用其他文件夹的文件，要引用同一文件夹，在小程序端的这个问题我不知道算不算bug

**Comment by beatles-chameleon** [comment]
可以参考下这个demo
https://github.com/chameleon-team/miniapp-enhance-demo/tree/master/miniapp-config-demo/%E5%85%A8%E5%B1%80%E9%85%8D%E7%BD%AEdemo-tabbar

**Comment by wanzijinx** [comment]
> 可以参考下这个demo
> https://github.com/chameleon-team/miniapp-enhance-demo/tree/master/miniapp-config-demo/%E5%85%A8%E5%B1%80%E9%85%8D%E7%BD%AEdemo-tabbar

这个demo也没有tabbar跨文件夹引用组件啊
