### ISSUE TITLE
refresh-view在小程序端无效

### ISSUE THREAD

**Issue by wanzijinx** [didi/chameleon#433]
**bug描述**
上拉加载更多和下拉刷新无法在小程序端触发

**问题截图**
![image](https://user-images.githubusercontent.com/28819509/83220055-92edfc00-a1a4-11ea-85d1-669baea93dae.png)
![image](https://user-images.githubusercontent.com/28819509/83220082-9f725480-a1a4-11ea-9fcb-7d7fde2a8a65.png)
![image](https://user-images.githubusercontent.com/28819509/83220094-a7ca8f80-a1a4-11ea-9ee2-dcf63f298429.png)

**Comment by beatles-chameleon** [comment]
提供下详细的chameleon-tool版本信息，相关依赖信息

**Comment by wanzijinx** [comment]
> 提供下详细的chameleon-tool版本信息，相关依赖信息

编译环境信息

chameleon-tool 版本：1.0.4
nodejs版本、npm版本：node v12.10.0、npm 6.10.3
电脑操作系统： win10

**Comment by wanzijinx** [comment]
已解决，该组件不支持自定义高度，必须作为全屏组件高度占满才能支持加载更多
