### ISSUE TITLE
c-if在小程序端不支持indexOf

### ISSUE THREAD

**Issue by wanzijinx** [didi/chameleon#434]
**bug描述**
c-if="{{[30, 40, 50, 60].indexOf(item.status) !== -1}}"无效，要用c-if="{{item.status === 30 || item.status === 40 || item.status === 50|| item.status === 60}}"

**Comment by beatles-chameleon** [comment]
两点建议：
一：提issue要按照规定的格式来，比如注明chameleon-tool版本号，电脑信息，并且贴上详细代码等
二：遇到问题可以尝试下定位下，排查下具体的根源，比如这个问题，如果用微信原生的代码这么写能否生效

刚试了下微信原生的是不支持的
```wxml
<view>
<view wx:for="{{array}}">
          <view wx:if="{{[30,40,50].indexOf(item.status) !== -1}}">ss{{item.status}}</view>
        </view>
<view wx:if="{{[40,50].indexOf(code) !== -1}} ">{{code}}</view>
</view>
```
page里面的数据如下：

```javascript
array: [{ status: 20 },{ status: 30 }, { status: 40 }],
code:30,
```
