### ISSUE TITLE
能否增加setStorage和getStorage的同步版本的API？

### ISSUE THREAD

**Issue by wuyansongs** [didi/chameleon#438]
比如像Taro的
Taro.setStorageSync
Taro.getStorageSync
Taro.removeStorageSync

**Comment by beatles-chameleon** [comment]
是个不错的建议，我们看下各端的适配情况如何，也欢迎你可以为chameleon贡献代码
https://github.com/chameleon-team/chameleon-api  新增一个这样的API接口
本地开发调试node_modules里面的包的话，可以参考，optimize配置
optimize: {
  watchNodeModules: true //设置为true
}
http://cml.didi.cn/docs/config.html#%E9%A1%B9%E7%9B%AE%E4%BC%98%E5%8C%96

**Comment by limingwei** [comment]
找到參考 
https://github.com/chameleon-team/chameleon-api/tree/master/src/interfaces/setStorage
https://github.com/chameleon-team/chameleon-api/tree/master/src/interfaces/getLaunchOptionsSync

不敢下手呢
似乎还得 weex 里面的本地代码

看了各端相关接口
好像 weex 和 快应用没有现成的
但 weex 应该可以由cml 的本地代码做
快应用不知道咋做

https://developers.weixin.qq.com/miniprogram/dev/api/storage/wx.getStorageSync.html
https://opendocs.alipay.com/mini/api/ox0wna
https://smartprogram.baidu.com/docs/develop/api/storage/save_swan-setStorageSync/
https://q.qq.com/wiki/develop/miniprogram/API/data-cache/qq.getStorageSync.html
https://microapp.bytedance.com/dev/cn/mini-app/develop/api/data-caching/tt.getstoragesync
https://doc.quickapp.cn/features/system/storage.html
https://weex.apache.org/zh/docs/modules/storage.html#setitem

**Comment by gaoxc** [comment]
chameleon-api@1.0.8-alpha.2  以支持

**Comment by limingwei** [comment]
赞
