### ISSUE TITLE
文档更新

### ISSUE THREAD

**Issue by L-Jovi** [didi/chameleon#439]
从 github 过去的文档
http://cml.didi.cn/docs/setup.html

看描述是不支持 yarn

![image](https://user-images.githubusercontent.com/7262199/83622866-210e1c00-a5c3-11ea-93bc-b0b26cec5d72.png)

但是这边尝试了下也能安装成功，所以是能用还是不能用呢。。

![image](https://user-images.githubusercontent.com/7262199/83622831-15225a00-a5c3-11ea-8fb4-6285216ca687.png)

**Comment by beatles-chameleon** [comment]
推荐使用 npm ，能安装成功的情况下可以启动下项目看是否可以
