### ISSUE TITLE
滴滴开始裁员，这个项目会停止吗？

### ISSUE THREAD

**Issue by zc806zc** [didi/chameleon#44]
滴滴全员会宣布过冬：将裁员15%涉及员工超2000人

这个项目还会继续吗

**Comment by bby422** [comment]
同问

**Comment by beatles-chameleon** [comment]
公司只是在发布时支持开源审核等，从来不是KPI驱动开源项目。
我从17年初规划出这个项目，在内网技术论坛发起倡议，从第一版本mini program view到现在chameleon，很多同学都是利用闲暇时间参与贡献进来的。
我的kpi不会定cml，我团队kpi也不会定cml。
—— Conan （Chameleon 负责人）

**Comment by zc806zc** [comment]
希望尽量1.0出来

**Comment by beatles-chameleon** [comment]
> 希望尽量1.0出来

@zc806zc 1.0版本不会做重大改变，仅仅是按计划完善周边功能，请放心使用。
