### ISSUE TITLE
支持打包输出 ios 和 android sdk 么

### ISSUE THREAD

**Issue by L-Jovi** [didi/chameleon#440]
这边的需求是希望能够打包出带有 ui 界面的 ios 和 android 移动端可供 app 接入的 sdk，不知 chameleon 是否支持呢

**Comment by beatles-chameleon** [comment]
http://cml.didi.cn/tutorial
这里里有接入android和ios教程，有没有先看过？

**Comment by L-Jovi** [comment]
收到，这边瞅瞅哈
