### ISSUE TITLE
c-tabbar 支持定制小程序端内的已有特性么

### ISSUE THREAD

**Issue by L-Jovi** [didi/chameleon#443]
小程序端内的 tabbar 支持定制 `dot` 和 `badge` 的定制，cml 统一了各个端的 tabbar，但是如何针对小程序端使用已有的 tabbar 能力呢

![image](https://user-images.githubusercontent.com/7262199/84341782-90dd6180-abd6-11ea-96fb-4cef42921a8e.png)

**Comment by jimwmg** [comment]
## 如何使用原生tabbar?

如果要使用小程序端原生的tabbar,我们也提供了支持

具体demo [参考](https://github.com/chameleon-team/miniapp-enhance-demo/tree/master/miniapp-config-demo)

但是需要注意一点，原生小程序的支持情况，web/weex端是没有对应支持的能力的。

**Comment by L-Jovi** [comment]
可以的，很看好 chameleon，目前生态稍微薄弱了些，加油哈

**Comment by jimwmg** [comment]
> 可以的，很看好 chameleon，目前生态稍微薄弱了些，加油哈

谢谢关注，我们努力
