### ISSUE TITLE
内联 style 中无法使用 cpx 单位

### ISSUE THREAD

**Issue by baylin87** [didi/chameleon#458]
**bug描述**
见关于 [CMSS介绍 #内联写法](http://cml.didi.cn/docs/cmss.html#%E5%86%85%E8%81%94%E5%86%99%E6%B3%95) 中，可使用如：

```html
<template>
  <view style="margin-top: 10cpx;"> </view>
</template>
```

但在实际使用中，发现 style 中的 cpx 在微信小程序中不会编译成 rpx ( class 中的 cpx 好像是转 rpx ？)，而是直接使用 cpx，导致小程序无法识别单位：
![image](https://user-images.githubusercontent.com/14541329/86870231-9319d980-c10a-11ea-8502-7e03d8846003.png)

**复现bug的步骤**
如上

**问题截图**
见描述

**编译环境信息**
 - chameleon-tool 版本：1.0.6
 - nodejs版本、npm版本：node v12.16.2、npm 6.14.4
 - 电脑操作系统： macOS Catalina 10.15.2

**运行环境信息**
 - 端版本： 微信小程序，其他端未测试

**Comment by jimwmg** [comment]
chameleon-tool@.1.0.6
编译之前：
<template>
  <view style="margin-top: 10cpx;"> </view>
</template>
编译之后  查看 dist/wx  中对应的组件
<view style="margin-top:10rpx" class=" cml-base cml-view"> </view>

没发现问题，麻烦自己在确认下哈

**Comment by baylin87** [comment]
> 我刚试了下
> chameleon-tool@.1.0.6
> 编译之前：
> `<template> <view style="margin-top: 10cpx;"> </view> </template>`
> 编译之后 查看 dist/wx 中对应的组件
> `<view style="margin-top:10rpx" class=" cml-base cml-view"> </view>`
> 
> 没发现问题，麻烦自己在确认下哈
> 
> 如果还有问题，node版本试下 别用太高的，试下 8.10.0

@jimwmg 感谢解答，已解决，是我这边问题
