### ISSUE TITLE
设置不支持的属性时导致无限启动CmlWeexViewActivity

### ISSUE THREAD

**Issue by xirys** [didi/chameleon#464]
**bug描述**
设置不支持的属性时导致无限启动CmlWeexViewActivity

**复现bug的步骤**
1. 在小程序cml文件中的view添加width or height百分比属性(知道不支持)
2. 小程序构建打包后放入android demo的assets目录下，App点击canvas进行加载，然后出现无限启动的情况
3. 使用assets目录下的其它js文件，可以正常渲染

**问题截图**

**编译环境信息**
 - chameleon-tool 版本：[e.g.0.1.0]
 - nodejs版本、npm版本：[node v8.11.4、npm 5.6.0]
 - 电脑操作系统： [e.g. macOS High Sierra 10.13.6]

**运行环境信息**
 - 端版本： [e.g. 微信小程序 7.0.3、weex 2.0、手机Safari浏览器 、PC Chrome浏览器 1.30]
 - 手机机型: [e.g. iPhone6 12.0]

**Comment by jimwmg** [comment]
1.麻烦首先确认是以这种方式接入的： http://cml.didi.cn/tutorial/android-sdk.html
2.麻烦提供一个能复现的demo,方便我们定位问题，只看描述，有些理解偏差，可以将demo上传到github,然后确定是将cml weex build 之后生成在  dist/weex  中 jsbundle 的按照  http://cml.didi.cn/tutorial/android-sdk.html 中的指示加入工程中了。

**Comment by xirys** [comment]
我的Demo代码在学习时结构混乱了复现不了，抱歉
