### ISSUE TITLE
讨论：chameleon 仓库太多 导致人气不聚集的问题

### ISSUE THREAD

**Issue by limingwei** [didi/chameleon#468]
本仓库**仅包含编译时代码，全部开源代码参见**：https://github.com/chameleon-team

个人感觉，这个事儿也许有点超前了

导致人家进来看这个仓库**很久都没有更新**
**其实** chameleon-team 里的**某个仓库是有更新**的

记得以前搞论坛的朋友，都说先只弄一个版块，集中人气，等量大了再细分

或者 也许可以有一个只读的影子仓库
把这一系列的库里的**代码和变更都同步过去**

不知道有没有这种**工具 或者**可以用**脚本**搞

**Comment by beatles-chameleon** [comment]
感谢关注啊，我们需要开源的力量

**Comment by Guo-Zhang** [comment]
我查到了一些资料：https://www.zhihu.com/question/28676261

**Comment by limingwei** [comment]
或者給 cml 所有子項目都 搞個 webhook
然后自动生成个最新动态的网页？
