### ISSUE TITLE
文档无法在新标签页中打开

### ISSUE THREAD

**Issue by xiaoyucoding** [didi/chameleon#485]
**bug描述**
部分文档不可在新标签页中打开，同时也造成无法在别处直接打开以下文档。

- [组件](http://cml.didi.cn/components/)
- [教程](http://cml.didi.cn/tutorial/)

选择在新标签页中打开，均返回 403 码。

**复现bug的步骤**
Ctrl + 鼠标左键，或者右键选择“在新标签页中打开链接”

**其他**

[多态协议](http://cml.didi.cn/docs/poly.html) 中有一处的 `catch` 写成了 `cache` 单词。

**Comment by beatles-chameleon** [comment]
http://cml.didi.cn/docs/  已解决

**Comment by xiaoyucoding** [comment]
> http://cml.didi.cn/docs/ 已解决

多态协议 中有一处的 catch 写成了 cache 单词。

这个问题依旧存在哦~
