### ISSUE TITLE
内置组件没有详细的说明文档，希望补充详细说明文档

### ISSUE THREAD

**Issue by sharh** [didi/chameleon#49]
1、像`c-fresh`组件的使用，只是给个例子，就没有文档说明了，只有看源码才能知道使用方法，建议还是添加详细说明文档，文档地址：
https://cmljs.org/doc/example/c-refresh.html

2、`scroller`组件的举例说明文档里面说滚动事件是：onscroll,在c-fresh举例却是其他：
![image](https://user-images.githubusercontent.com/7692602/53058771-75d17480-34ef-11e9-937f-def256a52a2a.png)
![image](https://user-images.githubusercontent.com/7692602/53058796-82ee6380-34ef-11e9-8bf4-c5c0d1aa7904.png)

https://cmljs.org/doc/example/scroller.html

而文档说明中并没有说明清楚。

**建议还是先把文档说明都补充完整**

**Comment by beatles-chameleon** [comment]
谢谢指正，文档已修改~
