### ISSUE TITLE
c-loading微信小程序真机报错

### ISSUE THREAD

**Issue by Bowen7** [didi/chameleon#5]
node v8.9.3
npm 5.5.1
cml 0.0.11

使用c-loading组件时，微信小程序真机调试时报错，尝试使用示例代码，仍然会报错

错误log：Cannot read property 'mask' of undefined;at setTimeout callback function
TypeError: Cannot read property 'mask' of undefined 
at Function.<anonymous> (weapp:///static/js/npm/cml-ui/components/c-loading/c-loading.js:137:47)

**Comment by beatles-chameleon** [comment]
感谢反馈，请更新以下包，可以解决问题：
chameleon-api@0.1.1
chameleon-ui-builtin@0.0.7
cml-ui@0.0.7
