### ISSUE TITLE
代码安全问题-存在钓鱼风险

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [didi/chameleon#501]
你好，我是来自**奇安信-代码安全事业部**团队的成员。在审计该项目时发现了如下的安全问题，可能存在钓鱼风险，请修复。
例如：
https://github.com/didi/chameleon/blob/ffa8976c72f57e2a3878bff1e1bfc65d771f997e/packages/chameleon-tool/configs/preview.html#L495
该问题还存在于此文件的**529，530，547,548，566**行。
修复建议：如果使用`target="_blank"`时请配合使用`rel="noopenner noreferrer"`。

**Comment by jimwmg** [comment]
感谢
