### ISSUE TITLE
在weex端，如何接入chameleon客户端sdk？

### ISSUE THREAD

**Issue by dick3741** [didi/chameleon#51]
[手把手教你系列- 变色龙SDK使用范例](https://github.com/chameleon-team/chameleon-sdk-android/blob/master/assets/android_example.md)，这个文档，看到`4.4.2 js 侧的实现`就不懂了，是在实现业务的那个页面调用在native 侧注册的模块吗？
`cml init project`生成的是一个前端文件夹，`chameleon-sdk-android`下载又是另一个文件夹，怎么结合起来呢？
比如我现在调用`cml.chooseImage`这个方法，那在这个业务页面应该怎么来引入SDK？
纯前端看到这个很吃力，希望文档描述能更详细一点！

**Comment by wowtrxqn** [comment]
表示也木有看懂
