### ISSUE TITLE
easy-chameleon支持切换npm-client

### ISSUE THREAD

**Issue by broven** [didi/chameleon#53]
在安装时支持通过参数切换npm-client

**Comment by beatles-chameleon** [comment]
easy-chameleon在项目中安装的依赖，不建议用yarn或者cnpm等npm client安装，可能会出现问题，例如 https://github.com/didi/chameleon/issues/1
可以提供registry参数改变源安装

**Comment by broven** [comment]
PR中注意到了#1, yarn会报错, 已经禁掉了yarn
公司内部有自建的npm client, 还是觉得应该流出一个option来进行使用
