### ISSUE TITLE
不兼容webpack4

### ISSUE THREAD

**Issue by broven** [didi/chameleon#55]
**bug描述**
![image](https://user-images.githubusercontent.com/12854613/53166694-02278880-3611-11e9-8667-a9fe38a543e0.png)
In webpack4 * `CommonsChunkPlugin` was removed -> `optimization.splitChunks`
**复现bug的步骤**
1. 按照webpack集成文档接入chameleon: https://cmljs.org/doc/example/webpack_plugin.html
2. 
```javascript
module.exports.chameleon = function(type, mode, config) {
  const modePreset = {
    'dev': {
      cmlType: type,
      media: `dev`,
      hot: true,
      disableExtract: false,
      context: path.join(__dirname,'../'),
      wxConfig: config
    },
    'build': {
      cmlType: type,
      media: `build`,
      hot: false,
      disableExtract: false,
      wxConfig: config
    }
  }

  return getConfig({
    ... modePreset[mode]
  })
}
--------
merge(originWebpackConfig, chameleon('baidu', 'dev', {entry: [...]}) )
```
3. errorLog: https://gist.github.com/broven/a627bff2891eda099badbdc886075adf

**编译环境信息**
 webpack: 4.23.0

**Comment by broven** [comment]
文档注明下兼容的webpack版本吧

**Comment by beatles-chameleon** [comment]
已注明
