### ISSUE TITLE
http请求支付宝环境下报错

### ISSUE THREAD

**Issue by Michael-5h** [didi/chameleon#57]
**bug描述**
使用cml.request发起请求 在支付宝环境会报错

**问题截图**
![image](https://user-images.githubusercontent.com/13900877/53218930-0eefbf00-3699-11e9-8201-f1d25500e1c8.png)

**编译环境信息**
 - chameleon-tool 版本：0.1.0-alpha.3
 - nodejs版本、npm版本：[node v9.6.1、npm 6.7.0]
 - 电脑操作系统： [e.g. macOS Mojave 10.14]

**运行环境信息**
 - 端版本： 支付宝IDE Version 0.27.0-beta.1 (0.27.0-beta.1)

**Comment by beatles-chameleon** [comment]
提供一下项目中chameleon-api的版本号
调用request方法时传递的method字段是什么，支付宝小程序目前只支持 get post 如果在 request中声明了method=put 会失败

**Comment by Michael-5h** [comment]
[存储多态接口支付宝存储源码缺少errMsg定义导致脚本错误](https://qiniu-image.qtshe.com/WechatIMG2.png)

**Comment by beatles-chameleon** [comment]
你好，感谢反馈，我们这边已经修复，将会在下个alpha版本发布更新。
