### ISSUE TITLE
无法正常编译

### ISSUE THREAD

**Issue by kaykie** [didi/chameleon#58]
**bug描述**
无法正常编译 h5 weex均报错

**复现bug的步骤**
1. npm i -g chameleon-tool
2. cml init project demo
3. cml dev
4. Module parse failed: Unexpected token (157:6)
You may need an appropriate loader to handle this file type.
|   if(type === 'scroll') {
|     newEvent.detail = {
|       ...newEvent.detail,
|       scrollHeight: e.contentSize ? e.contentSize.height : 0,
|       scrollWidth: e.contentSize ? e.contentSize.width : 0,

 @ ./node_modules/chameleon-runtime/src/platform/web/render/lib/extendVue.js 8:17-58
 @ ./node_modules/chameleon-runtime/src/platform/web/render/index.js
 @ ./node_modules/chameleon-runtime/src/platform/web/index.js
 @ ./node_modules/chameleon-runtime/src/interfaces/createPage/index.interface
 @ ./node_modules/chameleon-runtime/src/interfaces/createPage/index.js
 @ ./node_modules/chameleon-runtime/index.js
 @ ./node_modules/chameleon-runtime/.temp/entry.js
 @ multi /usr/local/lib/node_modules/chameleon-tool/commanders/web/liveload-dev-client.js ./node_modules/chameleon-runtime/.temp/entry.js

**问题截图**
[
![image](https://user-images.githubusercontent.com/26200899/53296407-f8d53080-3849-11e9-8a89-0d258fb28a03.png)
]

**编译环境信息**
 - chameleon-tool 版本：0.0.16
 - nodejs版本、npm版本：v11.10.0 6.7.0
 - 电脑操作系统： mac

**运行环境信息**
 - 端版本： [e.g. 微信小程序 7.0.3、weex 2.0、手机Safari浏览器 、PC Chrome浏览器 1.30]

**Comment by kaykie** [comment]
自己的临时解决方案: 到  /chameleonDemo/node_modules/chameleon-runtime/src/platform/web/render/lib/extendVue.js 点开第三行 import webMixins from 'chameleon-mixins/web-mixins.js'  的web-mixins.js 进去,157行 
if(type === 'scroll') {
    newEvent.detail = {
      // ...newEvent.detail,
      scrollHeight: e.contentSize ? e.contentSize.height : 0,
      scrollWidth: e.contentSize ? e.contentSize.width : 0,
      scrollLeft: e.contentOffset ? Math.abs(e.contentOffset.x) : 0,
      scrollTop: e.contentOffset ? Math.abs(e.contentOffset.y) : 0, // 坐标轴变换
      deltaX: 0,
      deltaY: 0
    }
  }
把对象扩展注释上 即可正常编译

**Comment by beatles-chameleon** [comment]
执行你的步骤没有复现这个问题。
从截图上看编译时chameleon-mixins这个包的路径寻找的不正确，导致没有过babel。
正确chameleon-mixins路径应该是/usr/local/lib/node_modules/chameleon-tool/chameleon-mixins
但是你的是/User/nianwangxia/node_modules/chameleon-mixins
