### ISSUE TITLE
果然是个kpi项目 又死了

### ISSUE THREAD

**Issue by duxphp** [didi/chameleon#582]
果然是个kpi项目 又死了 敬告各位开发者 珍爱生命 远离大厂开源

**Comment by zhouzhiqiangzzq** [comment]
有官方人员能说下项目目前的情况吗？

**Comment by a67793581** [comment]
确实死了 都不更新了 2019年的bug都还没关闭

**Comment by soulmatecm** [comment]
滴滴的项目是我用（见）过的，开源生命周期最短的，千万别用。

**Comment by CaopanHuster** [comment]
chameleon-tool安装失败 这是把我扼杀在摇篮里面的意思吗

**Comment by geeklibin** [comment]
weex都凉了。。。不喜欢uni和apiCloud他们的开发方式。。。兄弟们有没有其他好用的跨端方案？

**Comment by 54huige** [comment]
@geeklibin weex不是凉了 是uniapp里nvue就是weex方式，uni方式和apicloud不大一样的哦。uni最多在无法兼容的地方需要你自己去交叉编译，其他能统一兼容的都统一了。

**Comment by klren0312** [comment]
远离国内大厂开源

**Comment by anzipomelo** [comment]
hi～大家好，我是滴滴开源负责人安旭。
看到这个issue下的留言，作为一名开源人确实感觉很难过，听说这组截屏近期还在各种群里传播，真是影响很糟糕。
chameleon这个项目最早起源于顺风车团队，当时运营的非常活跃，也荣获了滴滴开源年度的奖项，我们都为项目团队祝贺和欣喜。但后来多次组织变化人员调整之后，这个项目就确实长期没人维护了。
从企业开源的角度，我们也在想怎么能避免这种情况，今年，开源规划里已经明确定出，开源项目必须在企业内部深度使用，来保持项目的持续性，这样对外开源就可以保证活跃度赢取开发者的信赖。
如果大家有兴趣，可以看[MPX](https://github.com/didi/mpx)这个项目，MPX就是滴滴内部重点项目，所以大家可以开到项目一直保持着活跃和持续迭代。
所以，希望大家在开源的环境下，找到自己喜爱的项目和社区，一起共建发展。
