### ISSUE TITLE
预期什么时候，可以到 1.0 版本？

### ISSUE THREAD

**Issue by hgonlywj** [didi/chameleon#6]
（1）weex 在阿里已经大面积弃用了

如果这样，未来 chameleon 的价值又在哪里呢，大量的维护鸡肋的工作吗？

（2）官方的demo
  
编译出来的BUG ，"navigationBarTextStyle": "#fff"； 类似版本更新的问题，未来如何解决？

（3）是否可以给出一些性能测试的数据、稳定性、兼容性的数据和一些相对丰富的案例。

那些产品使用了它进行了业务开发？

（4）工具链路上和开发规范上

对 VScode、webStrom 插件的支持，代码提醒、高亮、预发检测工具。有的官方文档要推荐，没有的补上。代码规范给出一个 eslint 基础版，文件约定，给出官方的一个最佳实践，目前写在一起，不够优雅。

**Comment by beatles-chameleon** [comment]
### 1）
weex、react-native作为2大虚拟机型跨android、ios端的技术选型，Weex国内用户量还是[足够有理由让我们支持](http://weex.apache.org/cn/who-is-using-weex.html)。
另外，目前cml框架规范分层比较合理，新增一个端基本2周可以完成，关键是测试、实践工作量较多。

### 2）
- "navigationBarTextStyle": "#fff"是具体什么问题？可以单独提issue提供更明确的环境信息。
- 版本更新的问题，未来如何解决？
目前编译只做足够基础如模板语法层（if、each、块）等基础统一工作，这类工作足够抽象。见FAQ：[各端包括小程序的接口更新频繁，如何保证框架编译的抽象度和稳定性？](https://cmljs.org/doc/framework/faq.html#%E5%90%84%E7%AB%AF%E5%8C%85%E6%8B%AC%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%9A%84%E6%8E%A5%E5%8F%A3%E6%9B%B4%E6%96%B0%E9%A2%91%E7%B9%81%EF%BC%8C%E5%A6%82%E4%BD%95%E4%BF%9D%E8%AF%81%E6%A1%86%E6%9E%B6%E7%BC%96%E8%AF%91%E7%9A%84%E6%8A%BD%E8%B1%A1%E5%BA%A6%E5%92%8C%E7%A8%B3%E5%AE%9A%E6%80%A7%EF%BC%9F)

### 3）

- [关于性能的回答点此](https://cmljs.org/doc/framework/faq.html#%E6%A1%86%E6%9E%B6%E6%9C%89%E5%A4%9A%E5%A4%A7%EF%BC%8C%E6%80%A7%E8%83%BD%E6%98%AF%E5%90%A6%E6%9C%89%E5%BD%B1%E5%93%8D%EF%BC%9F)；[框架各端尺寸这里有提到](https://github.com/didi/chameleon/wiki/%E5%90%8E%E6%9C%9F%E8%A7%84%E5%88%92)uglily后当前weex 136k wx 99.3k web 143k
- 部分线上应用场景如下图
![线上场景](https://user-images.githubusercontent.com/44267840/51796510-a9dab200-222f-11e9-83ab-476fd5d4b3db.jpeg)
- 复杂场景方面DEMO，我们已经做了一个网易严选demo后续会更新到这里来：[beatles-chameleon/awesome-cml](https://github.com/beatles-chameleon/awesome-cml)，已经目前收到很多用户的实践场景也会陆续更新。
- 各端兼容性后续会更新[FAQ](https://cmljs.org/doc/framework/faq.html)里面

### 4）

- 代码规范[见文档](https://cmljs.org/doc/framework/linter.html)，已经在编译工具内置；更细节规范不做官方限制。
- 插件支持已经在[规划中](https://github.com/didi/chameleon/wiki/%E5%90%8E%E6%9C%9F%E8%A7%84%E5%88%92)，欢迎贡献。
- 目前[快速上手](https://cmljs.org/doc/quick_start/quick_start.html)会告知用户：编辑器中语法高亮，暂时使用.vue的插件，后续会推出更强大的插件。


@hgonlywj 感谢你的反馈，对我们很有帮助。

**Comment by cnsummer** [comment]
2.这个问题我觉得我可以帮助你一下，因为最近微信官方的升级 "navigationBarTextStyle": "#fff" 已经不支持使用了，应该是"navigationBarTextStyle": "white"或者 "navigationBarTextStyle": "black" 昨天我在做小程序版本更替的时候发现微信官方也报了这个错
