### ISSUE TITLE
滴滴滴，能不能支持桌面应用，滴滴滴滴滴滴滴滴滴滴滴滴，一长两短，招手即停

### ISSUE THREAD

**Issue by AibiTi** [didi/chameleon#62]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by beatles-chameleon** [comment]
感谢支持，目前主要的方向是移动端；
同时桌面应用会慎重考虑。
