### ISSUE TITLE
input组件支付宝环境下无法进行数据双向绑定，@input监听事件报脚本错误

### ISSUE THREAD

**Issue by Michael-5h** [didi/chameleon#63]
**bug描述**
官网提供的v-model的demo可在微信环境运行，支付宝环境不可以，并且出现脚本错误

**复现bug的步骤**
<input type="text" v-model="modelValueTest"/>
<text>{{modelValueTest}}</text>
结果：
微信环境：![image](https://user-images.githubusercontent.com/13900877/53472230-0dac0100-3aa2-11e9-9696-6f4d0e2a765c.png)
支付宝环境：![image](https://user-images.githubusercontent.com/13900877/53472247-1997c300-3aa2-11e9-9d2f-1ea35ca9e2a0.png)

**问题截图**
监听事件支付宝环境报错信息：
![image](https://user-images.githubusercontent.com/13900877/53472099-b3ab3b80-3aa1-11e9-801d-9848ad0f9290.png)

**编译环境信息**
 - chameleon-tool 版本：chameleon-tool@0.1.0-alpha.3
 - nodejs版本、npm版本：9.6.1, 6.8.0
 - 电脑操作系统： [e.g. macOS Mojave 110.14]

**Comment by jimwmg** [comment]
您好：
      感谢您对chameleon的关注，目前这个bug已经修复，将在下个版本发布更新。

**Comment by Michael-5h** [comment]
好的 辛苦
