### ISSUE TITLE
app端不展示image图片

### ISSUE THREAD

**Issue by ihezz777** [didi/chameleon#65]
**bug描述**
web端能正常展示图片，app端未展示图片

**复现bug的步骤**
1. 在page 文件夹下面加了个hotel/hotel.cml 文件
2. 在page标签内 写上 <image class="bg-image" src="{{imageSrc}}"></image>

**问题截图**

**编译环境信息**
 - chameleon-tool 版本：[e.g.0.1.0]
 - nodejs版本、npm版本：[node v8.11.4、npm 5.6.0]
 - 电脑操作系统： [e.g. macOS High Sierra 10.13.6]

**运行环境信息**
 - 端版本： [weex 2.0]
 - 手机机型: [ oppo R17]

**Comment by beatles-chameleon** [comment]
不展现

**Comment by beatles-chameleon** [comment]
多天没有回复，我理解已经解决了，暂时关闭issue
