### ISSUE TITLE
接入小程序组件，组件内使用相对路径报错

### ISSUE THREAD

**Issue by pigzzz123** [didi/chameleon#67]
**bug描述**
接入小程序组件，组件内使用相对路径报错

**复现bug的步骤**
1. 构建多态组件时，引入了vant-weapp
2. 使用了icon组件报错，原因是icon组件中，wxs标签引入的是相对路径

**问题截图**
![image](https://user-images.githubusercontent.com/24596908/53612580-e3775200-3c0d-11e9-947e-a10a6c1ae432.png)
![image](https://user-images.githubusercontent.com/24596908/53612591-f12cd780-3c0d-11e9-94dc-a72bfd7de761.png)

**编译环境信息**
 - chameleon-tool 版本：[0.0.16]
 - nodejs版本、npm版本：[node v8.9.1、npm 5.5.1]
 - 电脑操作系统： [Windows10]

**运行环境信息**
 - 端版本： [微信开发者工具 v1.02.1902010]
 - 手机机型: [xiaomi 8]

**Comment by beatles-chameleon** [comment]
感谢反馈，后续版本会添加对wxs文件的解析。
