### ISSUE TITLE
引用其他端组件的时候会报错，需要手动安装vue-router

### ISSUE THREAD

**Issue by gaojx97** [didi/chameleon#71]
**bug描述**
引用其他端组件的时候会报错，需要手动安装vue-router

**复现bug的步骤**
1. 引入小程序端组件到“components”文件夹下
2. 根据教程调用组件

注：安装完vue-router问题解决

**问题截图**
![image](https://user-images.githubusercontent.com/15071824/53940420-a0771c00-40f0-11e9-982b-6a0ecb0325b1.png)

**编译环境信息**
 - chameleon-tool 版本：0.0.16
 - nodejs版本、npm版本：v10.15.0   6.4.1
 - 电脑操作系统：win10

**运行环境信息**
 - 端版本： 微信小程序 7.0.3       PC Chrome浏览器 1.30

**Comment by beatles-chameleon** [comment]
https://github.com/didi/chameleon/issues/72  这个问题截图上看出你不是用npm 安装的chameleon-tool导致的问题

**Comment by gaojx97** [comment]
那有可能是我cnpm安装出的问题，，，
