### ISSUE TITLE
导入小程序组件库，H5端报错，小程序端渲染正常

### ISSUE THREAD

**Issue by gaojx97** [didi/chameleon#72]
**bug描述**
使用导入的小程序组件库，H5端报错，小程序端渲染正常

**复现bug的步骤**
1. 导入小程序组件库
2. 页面调用
3. cml dev

**问题截图**
![image](https://user-images.githubusercontent.com/15071824/53941284-aa9a1a00-40f2-11e9-8a9f-ca5fa203f2d9.png)

**编译环境信息**
 - chameleon-tool 版本：0.0.16
 - nodejs版本、npm版本：v10.15.0   6.4.1
 - 电脑操作系统：win10

**运行环境信息**
 - 端版本： 微信小程序 7.0.3       PC Chrome浏览器 1.30

**Comment by beatles-chameleon** [comment]
是否在多态组件的小程序端进行引用的，如果在各端公用的cml文件中引用小程序组件，其他端是会报错找不到组件的，多态组件使用参见：https://cmljs.org/doc/framework/polymorphism/component.html

**Comment by beatles-chameleon** [comment]
不能用yarn和cnpm安装chameleon-tool，需要把chameleon-tool删除重新安装

**Comment by gaojx97** [comment]
已解决，得用多态组件，调用的小程序组件只能在小程序平台使用
