### ISSUE TITLE
关于微信小程序分包功能

### ISSUE THREAD

**Issue by luyixin** [didi/chameleon#73]
在未来版本中，请问会考虑支持微信小程序的分包加载吗？如果后期版本支持了，我目前的前期版本升级后期支持小程序分包加载版本后，项目代码调整和修改幅度大吗？

**Comment by beatles-chameleon** [comment]
分包加载是资源打包功能功能在小程序端端实现方式，只会在[chameleon.config.js](https://cmljs.org/doc/framework/structure.html)配置增加打包功能。
目前想要使用微信分包加载功能，其实现在用户只需修改`cml build`微信产出的 dist/wx 文件夹即可，具体如下：

**Comment by luyixin** [comment]
发个配置链接可以吗？

**Comment by beatles-chameleon** [comment]
微信提供[分包加载方案](https://developers.weixin.qq.com/miniprogram/dev/framework/subpackages/basic.html?search-key=%E5%88%86%E5%8C%85),以页面为入口进行分包。

cml项目中将如何手动做微信小程序的分包？

- 1 图片资源不需要进行分包，为了减少包大小，图片都会用线上地址，有两种方案，1 开发的时候就把图片传到服务器，直接用线上地址，2 配置publicPath， 将打包出的static/img发布到服务器，小程序代码中就可以将static/img删除。

- 2 将要分包的页面放到同一个子文件夹中，进行打包，例如我要把subpage下的页面分包。
```router.config.json
  "routes":[
    {
      "url": "/cml/h5/index",
      "path": "/pages/index/index",
      "name": "首页",
      "mock": "index.php"
    },
    {
      "url": "/cml/h5/page2",
      "path": "/pages/subpage/page2/page2",
      "name": "page2",
      "mock": "index.php"
    }
  ]
```
打包出的页面结构如下：
```
├── pages
│   ├── index
│   │   ├── index.js
│   │   ├── index.json
│   │   ├── index.wxml
│   │   └── index.wxss
│   └── subpage
│       └── page2
│           ├── page2.js
│           ├── page2.json
│           ├── page2.wxml
│           └── page2.wxss
```

- 3 配置app.json中的subpackages，把分包的页面从pages中删除，放入subpackages中，注意root指向分包页面的子文件夹。
```
"pages": [
      "pages/index/index"
  ],
  "subpackages": [
      {
        "root": "pages/subpage",
        "name": "subpage",
        "pages": ["page2/page2"]
      }
  ],
```

- 4 拷贝页面js。例如`pages/subpage/page2/page2.js`的内容如下：
```
var __CML__GLOBAL = require('../../../static/js/manifest.js')
__CML__GLOBAL.Page = Page;
require('../../../static/js/common.js')
require('../../../static/js/pages/subpage/page2/page2.js')

```
则把`/static/js/pages/subpage/page2/page2.js`这个文件的内容替换掉`require('../../../static/js/pages/subpage/page2/page2.js')` 然后删除`/static/js/pages/subpage/page2/page2.js`这个文件。

```
var __CML__GLOBAL = require('../../../static/js/manifest.js')
__CML__GLOBAL.Page = Page;
require('../../../static/js/common.js')

// /static/js/pages/subpage/page2/page2.js文件内容如下
// var __CML__GLOBAL = require("../../../manifest.js"); 注意把这句话删除
__CML__GLOBAL.webpackJsonp([9],{


Object.defineProperty(exports, "__esModule", {
      value: true
});
....内容省略
```


以上是手动实现微信小程序分包加载的过程，之后会按照这个思路写成webpack插件。

**Comment by luyixin** [comment]
3q

**Comment by beatles-chameleon** [comment]
分包已支持：https://cmljs.org/doc/example/subpage.html?h=分包
