### ISSUE TITLE
h5端编译报错 Cannot find module 'webpack/lib/RuleSet'

### ISSUE THREAD

**Issue by ddiu8081** [didi/chameleon#76]
**bug描述**
初始化项目后运行`dev`命令，直接报错`Module build failed: Error: Cannot find module 'webpack/lib/RuleSet'`，同时h5效果预览为空白。

**复现bug的步骤**
cml init project
cd cmltest
cml dev

**问题截图**
![image](https://user-images.githubusercontent.com/1998168/54082139-f4ca0800-434b-11e9-824d-e4736a08884a.png)
![image](https://user-images.githubusercontent.com/1998168/54082144-fdbad980-434b-11e9-97ca-44b599921439.png)

**编译环境信息**
 - chameleon-tool 版本：0.0.16，使用npm全局安装
 - nodejs版本、npm版本：node v8.15.1、npm 6.4.1，使用nvm管理版本
 - 电脑操作系统：macOS 10.14

![image](https://user-images.githubusercontent.com/1998168/54082181-86397a00-434c-11e9-9793-37609adb39bc.png)

**运行环境信息**
 - 端版本： Chrome 72.0.3626.121
 - 手机机型:  -

**Comment by jimwmg** [comment]
您好：
       刚刚试了下是可以的，麻烦您按照cml -v   cml init project   重新生成一个页面，cml dev
我刚测试的结果如下图

<img width="570" alt="屏幕快照 2019-03-11 上午11 39 58" src="https://user-images.githubusercontent.com/21155942/54099091-89874100-43f2-11e9-962d-9d2a91d3e6ce.png">
![屏幕快照 2019-03-11 上午11 40 16](https://user-images.githubusercontent.com/21155942/54099107-95730300-43f2-11e9-8995-548be0408d5f.png)

**Comment by beatles-chameleon** [comment]
把你/Users/didi/node_modules/vue-loader 删除

**Comment by ddiu8081** [comment]
> 把你/Users/didi/node_modules/vue-loader 删除

把 vue-loader 删除之后重新 install 就可以了，感谢 @beatles-chameleon @jimwmg ！
