### ISSUE TITLE
组件实例 c-refresh报错

### ISSUE THREAD

**Issue by smwsk** [didi/chameleon#78]
**bug描述**
描述出现的问题
VM625:1 纵向滚动必须传递高度属性
**复现bug的步骤**
1. 编译输出到微信小程序
2. 使用组件 c-refresh

**问题截图**
![image](https://user-images.githubusercontent.com/12505419/54258454-a0b66200-459d-11e9-957e-9d8507866097.png)

**编译环境信息**
 - chameleon-tool 版本：[chameleon-tool@0.0.16]
 - nodejs版本、npm版本：[node v11.11.0、npm 6.7.0]
 - 电脑操作系统： [windows10]

**运行环境信息**
 - 端版本： [e.g. 微信小程序 7.0.3、weex 2.0、手机Safari浏览器 、PC Chrome浏览器 1.30]
 - 手机机型: [e.g. iPhone6 12.0]

**Comment by beatles-chameleon** [comment]
使用<scroller />组件必须传入height，请参考文档https://cmljs.org/doc/component/base/layout/scroller.html
