### ISSUE TITLE
按照文档的写法，在组件内部并没有监听到state变动

### ISSUE THREAD

**Issue by Martinzzyy** [didi/chameleon#80]
mutation中修改了state
`beginLogin(state,status){
        state.status = status;
    }`
组件内部computed中返回state
` computed = {
    status(){
      console.log(`state.status:${store.state.status}`);
      return store.state.status;
    }
  }`
但是结果并没有监听到，除非是跳转到新页面再返回过来，才能获取一次最新的值。

**Comment by beatles-chameleon** [comment]
请描述清楚web/wx/weex？粘贴完整代码~

**Comment by Martinzzyy** [comment]
> 请描述清楚web/wx/weex？粘贴完整代码~

是我的问题，在创建state子模块时没有展开子模块的state
