### ISSUE TITLE
导出组件报错

### ISSUE THREAD

**Issue by Call-Me-Uncle** [didi/chameleon#87]
**bug描述**
执行cml web export 提示unhandledRejection can't find the entry file that you want to export

**问题截图**
配置
![image](https://user-images.githubusercontent.com/8119899/54652989-ff2a9580-4af3-11e9-89f4-995095e0881f.png)
组件
![image](https://user-images.githubusercontent.com/8119899/54652887-a3f8a300-4af3-11e9-832c-943831a53330.png)
执行命令
![image](https://user-images.githubusercontent.com/8119899/54652861-83c8e400-4af3-11e9-9a0a-87ddfc4f2702.png)

**编译环境信息**
 - chameleon-tool 版本：[0.1.0-alpha.4]
 - nodejs版本、npm版本：[node/11.11.0, npm/6.7.0]
 - 电脑操作系统： [macOS High Sierra 10.13.6]

**Comment by huyuangang** [comment]
导出配置应放在对应端内部
```js
web: {
  export: {
    entry: ['src/components']
  }
}
```
