### ISSUE TITLE
全局安装npm i -g chameleon-tool到一半卡着不动

### ISSUE THREAD

**Issue by WangEn** [didi/chameleon#90]
**bug描述**
MacOS Mojave10.14.3全局安装`npm i -g chameleon-tool`到一半卡着不动，最初查看是node版本问题，然后用nvm安装node 10.15.3版本并启用后再次尝试安装，仍然是相同情况

**复现bug的步骤**
1. `nvm use 10.15.3`
2. `npm i -g chameleon-tool`

**问题截图**
![cmltool](https://user-images.githubusercontent.com/12842804/54728259-c48a3100-4bb7-11e9-8b97-023344a3a113.png)

**编译环境信息**
 - chameleon-tool 版本：[master]
 - nodejs版本、npm版本：[node v10.15.3、npm 6.4.1]
 - 电脑操作系统： [macOS Mojave10.14.3]

**Comment by yylgit** [comment]
--registry=https://registry.npm.taobao.org 用淘宝源试一下

**Comment by WangEn** [comment]
> --registry=https://registry.npm.taobao.org

谢谢，果真是这个原因  我记得之前改过了才对
