### ISSUE TITLE
demo运行不起来，cml dev 未babel

### ISSUE THREAD

**Issue by RaySnow** [didi/chameleon#94]
**bug描述**
 ERROR  Failed to compile with 4 errors                                                                                                                                                        11:37:42

 error  in ./node_modules/chameleon-runtime/index.js

Syntax Error: 
   8 |   createPage,
   9 |   createComponent,
> 10 |   ...bootstrap
     |   ^
  11 | }
  12 | 

Add @babel/plugin-proposal-object-rest-spread (https://git.io/vb4Ss) to the 'plugins' section of your Babel config to enable transformation.

**复现bug的步骤**
1. npm i -g chameleon-tool
2. cml init project
3. cml dev

**编译环境信息**
 - chameleon-tool 版本：[0.1.1]
 - nodejs版本、npm版本：[node v11.4.0、npm 6.4.1]
 - 电脑操作系统： [macOS Mojave 10.14.2]

**Comment by beatles-chameleon** [comment]
检查你项目的父级目录是否安装babel-loader, 例如 ~/node_modules/babel-loader。将其删除

**Comment by RaySnow** [comment]
> 父

确实，厉害！

**Comment by RaySnow** [comment]
确实是这样，删了就好了，厉害

**Comment by RaySnow** [comment]
> 检查你项目的父级目录是否安装babel-loader, 例如 ~/node_modules/babel-loader。将其删除

确实是这样，删了就好了，厉害
