### ISSUE TITLE
npm i -g chameleon-tool过程中fsevents编译报错

### ISSUE THREAD

**Issue by hellow7758521** [didi/chameleon#95]
**bug描述**
fsevents编译报错

**复现bug的步骤**
npm i -g chameleon-tool 过程中

**问题截图**
![image](https://user-images.githubusercontent.com/2485998/54964577-faf4f100-4fa7-11e9-9432-a3fce52165ab.png)

**编译环境信息**
 - chameleon-tool 版本：[0.1.1]
 - nodejs版本、npm版本：[node v11.11.0、npm 6.7.0]
 - 电脑操作系统： [e.g. macOS Mojave 10.14.3]

**Comment by hellow7758521** [comment]
是引用的版本不对还是只有Mojave上有这个问题？

**Comment by beatles-chameleon** [comment]
用淘宝源试一下  npm i -g chameleon-tool --registry=https://registry.npm.taobao.org/

**Comment by hellow7758521** [comment]
还是报错

**Comment by beatles-chameleon** [comment]
这样的 应该fsevents@1.2.4 在你的系统上有bug  没有找到对应的二进制文件  之后版本修一下这个问题，关注CHANGE_LOG.md 修的版本我会发到这

**Comment by hellow7758521** [comment]
好的

**Comment by liasica** [comment]
> 还是报错，npm install -g fsevents@1.2.4 安装失败，npm install -g fsevents执行这个是成功的，看到cml的packge.json中指定的是1.2.4的

node版本太高了不支持1.2.4，1.2.4版本太老了。换回node10.x完成安装了
