### ISSUE TITLE
调起小程序自定义分享内容的方法onShareAppMessage时报错

### ISSUE THREAD

**Issue by oldfaceoldmidcure** [didi/chameleon#96]
**bug描述**
调起小程序自定义分享内容的方法onShareAppMessage时报错
且页面右上角的也显示无法转发

**问题截图**
![2019326-192012](https://user-images.githubusercontent.com/14800001/54993192-420cd180-4ffc-11e9-8603-bc65a1064aa5.jpg)
![TIM图片20190326191929](https://user-images.githubusercontent.com/14800001/54993201-446f2b80-4ffc-11e9-9791-a4b4c9aae6f7.png)
![TIM图片20190326192035](https://user-images.githubusercontent.com/14800001/54993208-4638ef00-4ffc-11e9-9aac-8795c122be21.png)

*编译环境信息**
 - chameleon-tool 版本：0.0.16 / 0.1.1

**Comment by xiaomiwujiecao** [comment]
I cant define this function  on  interface file, when I created a file which named share.interface in the component category

**Comment by startheart** [comment]
It has been fixed. try `npm i chameleon-runtime@0.1.2`
