### ISSUE TITLE
weex.android fail 

### ISSUE THREAD

**Issue by Chubby886** [didi/chameleon#97]
**bug描述**

**复现bug的步骤**
Do pre cmd 
Run weex.android fail 
Error: Command failed: npm run dev
npm ERR! missing script: dev

**问题截图**
![image](https://user-images.githubusercontent.com/22902717/55068683-5b298700-50bd-11e9-897c-d83aafc1fdd9.png)
![image](https://user-images.githubusercontent.com/22902717/55068691-6086d180-50bd-11e9-9d6e-b3861f75382f.png)

**编译环境信息**
 - chameleon-tool 版本：
![image](https://user-images.githubusercontent.com/22902717/55068723-77c5bf00-50bd-11e9-8ba4-e5d358c2641b.png)

 - nodejs版本、npm版本：
![image](https://user-images.githubusercontent.com/22902717/55068748-83b18100-50bd-11e9-9975-dff8d4a4634f.png)

 - 电脑操作系统： 
![image](https://user-images.githubusercontent.com/22902717/55068765-9035d980-50bd-11e9-8717-28109458f481.png)

**运行环境信息**
安卓

**Comment by beatles-chameleon** [comment]
npm run dev里面实际执行的是什么命令？
