### ISSUE TITLE
vuex在WX小程序端工作异常

### ISSUE THREAD

**Issue by Martin-Mo** [didi/chameleon#98]
**bug描述**
vuex在WX小程序端工作异常，store实例没有注入到子组件中。H5端正常

**复现bug的步骤**
1. 用cml生成初始工程
2. index.cml里面增加button组件并绑定click事件到testClick处理函数中
3. 在testClick函数中查看this.$store的内容
4. WX小程序端this.$store为undefined, H5端正常

**问题截图**
H5端:
![image](https://user-images.githubusercontent.com/7042961/55141659-dd758200-5175-11e9-8486-ad4bbbdd961d.png)

WX小程序端：
![image](https://user-images.githubusercontent.com/7042961/55141713-0138c800-5176-11e9-876a-a1d7f7f6e671.png)

**编译环境信息**
 - chameleon-tool 版本：0.1.1
 - nodejs版本、npm版本：[node v8.11.4、npm 6.4.1]
 - 电脑操作系统： [e.g. macOS High Sierra 10.14.3]

**运行环境信息**
 微信开发者工具v1.02.1902010
macos chrome v73.0.3683.86

**Comment by beatles-chameleon** [comment]
cml没有提供this.$store这个对象。这个是属于web和weex端的内部实现部分。按照文档的方式使用store就可以
