### ISSUE TITLE
radio组件的change事件在H5端无法法获取到event对象的currentTarget属性

### ISSUE THREAD

**Issue by Bian2017** [didi/chameleon#99]
**bug描述**
radio组件的change事件在H5端无法法获取到event对象的currentTarget属性，其他三个小程序端OK，这样就无法通过currentTarget属性获取传递的参数，代码如下：

```JS
 <radio
     class="radio"
     label="{{option}}"
    c-bind:change="selectSingleOption"
    data-id="{{qa.id}}"
    data-type="{{qa.questionType}}"
/>
```

**问题截图**
![image](https://user-images.githubusercontent.com/28329190/55144444-d6517280-517b-11e9-875b-0b34af386d56.png)

**编译环境信息**

```JSON
   "chameleon-api": "^0.3.0",
    "chameleon-bridge": "^0.1.1",
    "chameleon-runtime": "^0.1.0",
    "chameleon-store": "0.0.3",
    "chameleon-ui-builtin": "^0.1.0",
    "cml-ui": "^0.1.0"
```

**Comment by beatles-chameleon** [comment]
`video`的`change`事件不属于原生事件，属于自定义事件，在H5、weex取不到事件的currentTarget，可以这样获取id
```
     <radio
        class="radio"
        c-bind:change="selectSingleOption($event, qa.id)"
    />
```

**Comment by Bian2017** [comment]
采用如下写法：
![image](https://user-images.githubusercontent.com/28329190/55272710-91ece080-52fb-11e9-84c8-8e23de2e4668.png)
支付宝就会报如下错误：
![image](https://user-images.githubusercontent.com/28329190/55272714-a4ffb080-52fb-11e9-8032-0a4d4deb2b40.png)

**Comment by Bian2017** [comment]
虽然采用推荐方式解决了H5的问题，但支付宝小程序又不开始报错了，在其他两个小程序无此问题

**Comment by beatles-chameleon** [comment]
模板编译的问题，需要升级cli，这个版本解决了 `npm i -g chameleon-tool@0.2.0-alpha.0`
